### ISSUE TITLE
[bug-website module] FlameScans Cloudfare workaround not working

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [dazedcat19/FMD#1012]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11 x64

### Describe the bug

When trying to access a series from FlameScans, it changes the title to "Please wait.." and returns an empty list and cover. When the series is in Favorites and checks for a chapter, it shows as an empty list (i.e. red background and 0 chapters).

I've gone to Options>Websites>Advanced and added the cookies and UserAgent I got from two different browsers (I tried one first, then the other, of course), but it still refuses to work.

**Comment by Slasar41** [comment]
Works fine here.
![image](https://user-images.githubusercontent.com/28888646/174454530-9c01cd9e-587c-4b4e-9312-d012765315bd.png)

**Comment by jpwong2** [comment]
I notice with flamescans the site works on and off, if you leave it for a few days the cloudflare problem stops and things work again.

**Comment by l-l-l-l-l-l** [comment]
To me it's changing between "detected the new Cloudflare challenge, not supported yet" (most often) and "no Cloudflare solution found!" (sometimes) in the logs.

I've checked the websitebypass modules and it seems to have an option for a webbdriver. Is it coded into FMD or is there a way to activate it?

**Comment by l-l-l-l-l-l** [comment]
Like jpwong2 said, it suddenly started working again.
