### ISSUE TITLE
[feature request] Is ther a way to change the link to download from?

### ISSUE THREAD

**Issue by Qizmo** [dazedcat19/FMD#1013]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the current download site can't be used anymore and have to delete it, then download a new one.

**Describe the solution you'd like**
Option to change the link to download from

**Describe alternatives you've considered**
...

**Additional context**
...

In the "Favorites" Page there should be a function to look at the download link same like Change "Save to"
So we can copy the link from a new pages and paste over the old link.

PS. Like right now I have download lot's of manga from "MangaRaw". However they change link to "mcreader.net".
What I have to do is search for the new page, place into "Manga Info", "Add to Favorites", go to "Favorites" look for the previous Favorite from MangaRaw to delete.
If can have the above function I can just go to "Favorites" look for the previous Favorite from MangaRaw and just replace 
https://www.manga-raw.club/12345
with 
https://www.mcreader.net/12345

**Comment by l-l-l-l-l-l** [comment]
AFAIK that's done through the lua module, which should automatically change the link after update.

Option 2, a bit more obtuse, is to find the proper module in the lua folder (if you don't find a module with the name of the site, although MangaRaw does have one, just search for the site in this github and it should return the file), open it with notepad, search every instance of the old url and change them for the new one; there should be just one instance im the first function (Init) in the form `AddWebsiteModule('[moduleid]', '[website name]', '[url]')`

**Comment by Slasar41** [comment]
Usually I'll change the domain and publish the update so the users won't need to do anything, but because MCReader site is already supported I can't do that anymore.
Users need to choose:
- Use `Transfer website` function, select the manga in favorites and then right click.
or
- Like the above comment, edit the module. Locate to `lua\modules\MangaRaw.lua`, delete line 17, change in line 16 from `https://www.manga-raw.club` to `https://www.mcreader.net`. Save it then open FMD again.

**Comment by Qizmo** [comment]
Thx guys. I manage to completely change my link to download now :)

At first I think that "Transfer Website" is for that too, however after trying it in various way, I can't find a way to change it
[https://ibb.co/CK6nWsM](url)

After I read about you guys method using "lua\modules\MangaRaw.lua". After trying several times I finally manage to do it.
My first try delete line 17, change in line 16 from https://www.manga-raw.club to https://www.mcreader.net, result in Websites disappearing. After trying several time with no success, I notice that in my "Options", "Website" the link for  "manga-raw.club" link was removed and "mcreader.net" was tick instead. Guess it auto change from the update.

After I tick "manga-raw.club" and remove "mcreader.net" from the list, then follow your second method, All my manga download from mangaraw immediately turn into McReader.

Thank you very much :)

**Comment by Slasar41** [comment]
I've change the website in your favorites from MangaRaw to MReader.
[favorites.zip](https://github.com/dazedcat19/FMD2/files/9742724/favorites.zip)

I use [this software](https://sqlitebrowser.org/) and modified the script I got from https://github.com/dazedcat19/FMD2/issues/1054#issuecomment-1267733461.
```sql
update favorites
set moduleid=replace(moduleid, '8b08552360e14892a2b715dab6957bfe', 'd297f1eb6b784ded9b50d3b85cee5276'),
id=replace(id, '8b08552360e14892a2b715dab6957bfe/', 'd297f1eb6b784ded9b50d3b85cee5276/')
where moduleid='8b08552360e14892a2b715dab6957bfe'
```
