### ISSUE TITLE
[bug-website module] KLmanga

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD#1023]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7 Ultimate SP1

### Describe the bug

Apparently it has problems displaying the manga information, it doesn't show the chapters and the favorites list doesn't work

![image](https://user-images.githubusercontent.com/53473707/176956839-13850b61-bc99-44dc-999d-6564029ba849.png)

![image](https://user-images.githubusercontent.com/53473707/176956862-4c0711ab-b304-4938-81ba-e4c5d3fba701.png)

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/commit/fbbc5e5b9ddf6acb341ab508ea880ff65326822b
