### ISSUE TITLE
[bug-website module] Welovemanga

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD#1024]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7 Ultimate SP1

### Describe the bug

apparently the "account" function does not work and some sleeves that need it the program can not download them and also have no information

![image](https://user-images.githubusercontent.com/53473707/176958975-a8584e3d-6070-42cf-8a20-af5088d644a1.png)

**without the account, those manga and others cannot be accessed.. use them as an example**

https://welovemanga.one/1643/
![image](https://user-images.githubusercontent.com/53473707/176959312-e3148c0c-afb5-4193-9caf-4b99a1472676.png)

https://welovemanga.one/2382/
![image](https://user-images.githubusercontent.com/53473707/176959371-ddc3fe7e-6fb2-4587-be72-a2eef9a38886.png)

https://welovemanga.one/592/
![image](https://user-images.githubusercontent.com/53473707/176959411-f16b6912-50b1-45a8-9048-8befdd08bd79.png)

**Comment by masaton6** [comment]
I faced exact same issue on welovemanga.one. Hope this get resolved soon.

**Comment by Slasar41** [comment]
![image](https://user-images.githubusercontent.com/28888646/186505455-33bc9462-2f76-470c-ae92-ff04b5516a48.png)
![image](https://user-images.githubusercontent.com/28888646/186505557-e19c4732-8df9-4931-bf2b-b5506007161b.png)

**Comment by masaton6** [comment]
I can see the issue fixed. Thank you!
