### ISSUE TITLE
[bug-website module] mcreader.net not collecting info or downloading

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1027]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

fmd not collecting the info or downloading anymore all of a sudden, not even with cookie work around. it worked 20 min ago before i posted this

it comes out as either N/A or partial info for some, but no downloads show up.

https://www.mcreader.net/manga/in-the-night-consumed-by-blades-i-walk/

**Comment by xx255q** [comment]
Same for me

**Comment by Qizmo** [comment]
Same for me too.

**Comment by Lenoyr** [comment]
Same for me

**Comment by xx255q** [comment]
any updates to this or even basic things someone could do to debugg like a program to run?

**Comment by jillybeans** [comment]
still waiting for a fix or work around as well, i would help if i even remotely understood this, but this too big brain for me

**Comment by xx255q** [comment]
Well the thing we could do is leas big brain and more time wasting. What if
we look up examples of closed big tickets with the same bug we have now.

**Comment by Slasar41** [comment]
The problem is within the FMD app, not the module.
Same thing happened with Batoto and a few other sites too.
I can't fix this.

I know the workaround to make it work again but it's difficult.
You need to somehow able to make this page appear in the browser:
![image](https://user-images.githubusercontent.com/28888646/182252441-4e2e59b5-992d-4b38-9c7d-6adc78aa374f.png)
Maybe you can trigger it by using a VPN.
If that page appear, then you can use cookies workaround.

**Comment by jillybeans** [comment]
im not able to trigger that page even with vpn, the site works fine, is there a different way to trigger it?

**Comment by jillybeans** [comment]
![Untitled](https://user-images.githubusercontent.com/52017476/182253877-61692ee9-c816-46cd-bb8f-07cba7522dcd.png)
welp i managed to get this page, but now im stuck in it

**Comment by jillybeans** [comment]
the moment i closed the vpn i got out of that page, and back on site, but workaround still not working

**Comment by Slasar41** [comment]
What VPN are you using?

**Comment by jillybeans** [comment]
a free one on the chrome store called veepn

**Comment by Slasar41** [comment]
Ah, I think FMD also need to use the same network. So you need a VPN app.

**Comment by jillybeans** [comment]
whats that? sorry im not that technical

**Comment by Slasar41** [comment]
Instead of just affecting a browser, a VPN app is affecting all apps including FMD.
I've tried all servers in Windscribe VPN app but I'm unable to trigger it.

**Comment by jillybeans** [comment]
so i need to download one that's on my desktop and not just the browser?

**Comment by Slasar41** [comment]
Yes.

**Comment by jillybeans** [comment]
once i get that page once do i need to keep the vpn on permanently? and do i need to keep setting it up to use workaround?

**Comment by Slasar41** [comment]
If you found a VPN app that can trigger that page, you can turn on the VPN when you just need to use FMD.

**Comment by jillybeans** [comment]
welp i downloaded a free vpn on my desktop. protonvpn. still dont know how to trigger the page

**Comment by xx255q** [comment]
I use PIA but cant trigger that page either

**Comment by Qizmo** [comment]
Hope this get fixed soon.

**Comment by xx255q** [comment]
Can you tell me how you triggered it with your testing? its been like a month and if this is happening with other sites something needs to be done

**Comment by xx255q** [comment]
Still not working

**Comment by Qizmo** [comment]
same same. Waiting for this to get fix too

**Comment by Qizmo** [comment]
Hi, this site is fixed and can be downloaded normally now.

However this site change from "mcreader.net" to "mreader.co". 
For the old favorites site there is no problem in downloading from mcreader.net.
But all the new series to be added are in mreader.co
How do I edit this change?

**Comment by Slasar41** [comment]
I've updated the module.

**Comment by Qizmo** [comment]
@Slasar41  hi, I see a bit of a problem. The earlier Websites have been removed and now it is all blank. I try using "Transfer Website" and it wouldn't work.

https://ibb.co/rphDZQL

As in picture, it is always shown invalid. did I do something wrong?

**Comment by Slasar41** [comment]
@Qizmo Could you upload your favorites database here?
It's in `userdata\favorites.db`.

**Comment by Qizmo** [comment]
@Slasar41 Oh! so I did correctly :)

https://www.filehosting.org/file/details/16269803/favorites.db

PS. Is this the correct way of uploading files? I never did this before. I have only upload pictures.
I try the "M" icon in the comment section below but it can't upload .db file.

**Comment by Slasar41** [comment]
@Qizmo I got it. Next time you can compress to .zip and place directly into comment box.
I'll answer to your still open issue.

**Comment by Qizmo** [comment]
@Slasar41 Ah! never think of that.

Thank you in advance Slasar41
