### ISSUE TITLE
[bug-website module] comickiba.com unable to work

### ISSUE THREAD

**Issue by azraei97** [dazedcat19/FMD#1036]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Win 10 x64

### Describe the bug

Unable to get manga info compare to it alternative site alltopmanga.com able to works fine
![Untitled](https://user-images.githubusercontent.com/40983245/180206056-5d4bd47a-9909-42e5-826b-7609c583f283.png)

**Comment by jillybeans** [comment]
site works on fmd? https://comickiba.com/manga/cultivator-against-hero-society/

might just be that manga

**Comment by azraei97** [comment]
Not working in all my manga. All update module
![Untitled](https://user-images.githubusercontent.com/40983245/184481186-11001a8d-e6b4-4952-8406-a6938bf2ed0f.png)

**Comment by azraei97** [comment]
Not working in all my manga. All update module
![Untitled](https://user-images.githubusercontent.com/40983245/184481695-2ebc3eb2-bd53-49f3-a1a9-de7eb9d1dcc4.png)

**Comment by jillybeans** [comment]
that is weird cause I'm testing it with the ones on your list and it all downloads properly on my end.

**Comment by azraei97** [comment]
I just check again now I found what cause the error. It turn out just missing "/" symbol
![saas1](https://user-images.githubusercontent.com/40983245/184584584-3a625bdb-ef0c-45f4-99e3-df1a8826b07e.png)

Fixed
![saas2](https://user-images.githubusercontent.com/40983245/184584617-1d2f86b9-6b40-4bfd-b68a-9990753fd700.png)

.

**Comment by Slasar41** [comment]
Have you fix the favorites yourself?

**Comment by azraei97** [comment]
> Have you fix the favorites yourself?

Yea. Manually

**Comment by Slasar41** [comment]
Great.
Next time something happen again and can be fixed with editing the url, you can try Transfer Website function.
It should fix it by replacing the old url to new url.
