### ISSUE TITLE
[bug-website module] TraducionesAmistosas

### ISSUE THREAD

**Issue by djgerman10** [dazedcat19/FMD#1049]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 LTSB

### Describe the bug

problem when checking for new manga, it seems to download all the chapters and not the new chapter

![Screenshot_1](https://user-images.githubusercontent.com/48584512/181920573-155b3be4-3f42-4175-8098-e1cf7c71264e.png)

### Log

https://nartag.com/bl/segunda-vida-del-gangster/

**Comment by Slasar41** [comment]
This happens when FMD detect the chapter url has been changed in the website and then making FMD think there's a new chapter.
You can let FMD continue downloading all of them, FMD will only download the missing chapter.
