### ISSUE TITLE
[bug-website module] [yugenmangas]

### ISSUE THREAD

**Issue by horacio881** [dazedcat19/FMD#1054]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

On the yugenmangas.com website they made changes and one of those changes was the URLs.

For example:

Before:
https://yugenmangas.com/series/cazador-suicida-de-clase-sss/

After:
https://yugenmangas.com/bl/cazador-suicida-de-clase-sss/

Is there any way to change all the urls? Because now I can't know if there are updates.

**Comment by rs3mk** [comment]
```
MANGAINFO.URL=MaybeFillHost(MODULE.RootURL, URL)
if MODULE.ID == 'ac42a85566244b7e836679491ce679e6' then
   MANGAINFO.URL = MANGAINFO.URL:gsub('/series/', '/bl/')
end
```

Replace in line 14 from Madara.lua

**Comment by Slasar41** [comment]
You can use @rs3mk tips but it'll be gone when there's a module update.
You can try to make use of Transfer Website function.

**Comment by horacio881** [comment]
hello, here again. they changed the directories again, from /bl/ to /series/, as it was before.

For example:

Before:
https://yugenmangas.com/bl/cazador-suicida-de-clase-sss/

After:
https://yugenmangas.com/series/cazador-suicida-de-clase-sss/

Transfer Website does not work.

Last time I had to manually change each of the manhua I follow from that site, but now there are more than 100 and I wonder if there is an easier way, some files that I can open and search and replace /bl/ by /series/? o alguna otra solución?

**Comment by Slasar41** [comment]
Could you upload your favorites here?

**Comment by horacio881** [comment]
> Could you upload your favorites here?


[favorites.zip](https://github.com/dazedcat19/FMD2/files/9689292/favorites.zip)

**Comment by Slasar41** [comment]
I've changed the links for YugenMangas.
[favorites.zip](https://github.com/dazedcat19/FMD2/files/9689343/favorites.zip)

If you want to do it yourself, here's what I do:
- Use [DB Browser for SQLite](https://sqlitebrowser.org/)
- Open `favorites.db` with that program.
- Sort the `moduleid`, and search for `ac42a85566244b7e836679491ce679e6` (It's the ID for YugenMangas).
- Select all the items in `link` column you want to change, then copy it.
![image](https://user-images.githubusercontent.com/28888646/193378876-c0a17e6e-ae56-43d4-addf-529544c75159.png)
- Paste to Notepad, do replace all, then copy it.
![image](https://user-images.githubusercontent.com/28888646/193378925-033b0b7c-c873-4479-ab26-bed6c397a25d.png)
- Back to DB Browser, paste it to `link` column.
- Then press `Write Changes` button.
![image](https://user-images.githubusercontent.com/28888646/193379039-4f60afe4-490c-461a-8cef-7f37c83a9c0a.png)

**Comment by horacio881** [comment]
Thank you very much!!! It worked perfectly.
And thanks for the program, if it changes again I will try on my own.

Regards

**Comment by Slasar41** [comment]
I'll close this issue.

**Comment by rs3mk** [comment]
from this: https://github.com/riderkick/FMD/issues/1283#issuecomment-398511717

use:

```sql
update favorites
set link=replace(link, '/bl/', '/series/'),
id=replace(id, '/bl/', '/series/')
where moduleid='ac42a85566244b7e836679491ce679e6'
```

**Comment by Slasar41** [comment]
@rs3mk Nice script.
I don't know how to it so I do it in a complicated way. :3
From now on I'll suggest this way.
