### ISSUE TITLE
[bug-website module] Mangatown.com change it's domain

### ISSUE THREAD

**Issue by Israld** [dazedcat19/FMD#1055]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Pro 21H2 64X

### Describe the bug

Mangatown.com change it's domain to manga.town

**Comment by Slasar41** [comment]
www.mangatown.com is still working.
![image](https://user-images.githubusercontent.com/28888646/186512438-29363e41-9a40-4600-956d-dc3aae875c41.png)
