### ISSUE TITLE
[bug-website module] comick.fun

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1057]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Pro 21H1

### Describe the bug

FMD2 is unable to retrieve chapter details and therefore unable to download chapters
![imagen](https://user-images.githubusercontent.com/65477084/183877351-427f6af5-2340-4caf-ae69-28c62fb37e47.png)

### Log

![imagen](https://user-images.githubusercontent.com/65477084/183877524-daa99e65-bde4-4e83-b746-8c434c8e8ae1.png)

Source example
https://comick.fun/comic/annarasumanara

**Comment by Slasar41** [comment]
Check your ComicK language setting.

**Comment by Lenoyr** [comment]
> Check your ComicK language setting.

Thanks, bro
