### ISSUE TITLE
[bug-website module] TraduccionesAmistosas

### ISSUE THREAD

**Issue by djgerman10** [dazedcat19/FMD#1063]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 LTSB

### Describe the bug

problem download the chapters all with the name of %CHAPTER%
![Screenshot_1](https://user-images.githubusercontent.com/48584512/184551189-726348e4-652e-4410-abe6-c15082520225.png)

### Log

[https://nartag.com/l/adopte-al-protagonista/](https://nartag.com/l/adopte-al-protagonista/)

**Comment by Slasar41** [comment]
Update the module and try it again.
