### ISSUE TITLE
[bug] Can't make CBZ files when downloading "full" manga from NHentai.net

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD#1066]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Win 10 64bit

**Describe the bug**
The images files downloaded normally but it's not making any CBZ files and the state on FMD were failed. Mostly happen to manga that has 100+ pages. (Mostly happen to "full book" manga that has cover, when I'm downloading only part or manga that has few (under 100) images it works normally)

**To Reproduce**
1. Download normally from NHentai
2. The images fully downloaded (ex: from web it has 170 images they were all downloaded to my pc)
3. Download failed but FMD keep retrying to finish it (loop in 170/170 download)
4. I checked my folder only contain image files.

**Expected behavior**
My downloaded files only contain CBZ files instead folder with image files

**Screenshots**
![error 1](https://user-images.githubusercontent.com/26659986/185004834-1793e276-05e6-4870-947c-f8d8f9264f3a.png)
![error 2](https://user-images.githubusercontent.com/26659986/185004813-78e1c8a9-46d2-4a45-be17-874c9b7eec8d.png)
![error 3](https://user-images.githubusercontent.com/26659986/185004816-ccabf4e1-5a1c-40a3-b031-c6b93a875398.png)
As you can see on the screenshots _E Roman_ has 140 images and my folder also contains 140 images but it's not CBZ file

**Additional context**
- I could see the status "Compressing.." for like half a second before FMD retrying to download and failed.
- I'm using workaround (copy cookies and user agent).

**Comment by Slasar41** [comment]
I've found the issue. I think it's because the file name is too long.
To resolve this, you can navigate to Options > Save to and then disable `Auto generate chapter folder` option.

**Comment by Plegmatis** [comment]
it doesnt work. i tried some rename settings and last i set the settings to this
iirc there are some manga that doesnt have long name but it still failed and vice versa (long name but cbz made)
![error 4](https://user-images.githubusercontent.com/26659986/185265781-b8732397-ac0e-4d3e-bd69-c77cc4e9b551.png)

**Comment by Slasar41** [comment]
Have you tried start download from manga info?
Don't resume from the error entries, just delete those.

**Comment by Plegmatis** [comment]
yeah i tried it, resume, delete files and fresh start but still failed to make CBZ

**Comment by Slasar41** [comment]
Try following my settings and fresh start again:
![image](https://user-images.githubusercontent.com/28888646/185717432-4dc6ab5e-0891-42f1-adf3-bf803cc647bd.png)

Last resort: Make cbz file manually.
Compress all the images to zip and rename to cbz.
