### ISSUE TITLE
[bug] reaperscans.com not loading

### ISSUE THREAD

**Issue by Qizmo** [dazedcat19/FMD#1080]
- [Yes ] I'm using the latest version.
- [Yes ] All website modules are up to date.

- [Yes ] This is not temporary server issue.

**System information**
Windows 10 Home

**Describe the bug**
The website can be logged in normally, however when open in FMD it cannot be opened when open the link, it show as "Title:
N/A"

**To Reproduce**
1. Go to 'https://reaperscans.com/series/990k-ex-life-hunter/' or
2. Go to 'https://reaperscans.com/series/leveling-with-the-gods-manhwa/'
3. See error

**Expected behavior**
The download page information shown below is always "Title: N/A"

**Screenshots**
[<a href="https://ibb.co/Msf7Vqv"><img src="https://i.ibb.co/yXpqyL9/Delete.png" alt="Delete" border="0"></a>](url)

**Comment by Slasar41** [comment]
Looks like it's website issue, I can't access the website with browser.
