### ISSUE TITLE
[bug] reaperscans.com

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1082]
**Prerequisite**
- [yes ] I'm using the latest version.
- [ yes] All website modules are up to date.

- [ yes] This is not temporary server issue.

**System information**
Windows 10 Pro

**Describe the bug**
The website can be logged in normally, however when open in FMD it cannot be opened when open the link, it show as "Title:
N/A"

**To Reproduce**

    Go to 'https://reaperscans.com/series/how-to-live-as-a-villain/' or
    Go to 'https://reaperscans.com/series/the-rebirth-of-an-8th-circled-wizard/
    See error

**Expected behavior**
The download page information shown below is always "Title: N/A"

**Screenshots**
![imagen](https://user-images.githubusercontent.com/65477084/189277969-d928f26d-5c99-4fb5-870b-c6ca2842823d.png)

**Additional context**

**Comment by ap-sensei** [comment]
More Info:
Recently, they've had a site issue and it's still in **maintenance mode**. Opening in browser is not a problem, changing **user-agent** and applying **custom settings** in FMD doesn't work either.

I enabled the logging, and here's the result:

17:06:47:757 WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://reaperscans.com/wp-admin/admin-ajax.php
17:06:45:440 WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://reaperscans.com/series/mercenary-enrollment/ajax/chapters
17:06:23:133 WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://reaperscans.com/series/mercenary-enrollment/

I hope it helps. Thanks!

**Comment by ap-sensei** [comment]
The problem still exists. Obviously, they changed the website's theme, and it seems they no longer use WordPress.

The modules are all updated. You can download the manga list, but the chapter list is not shown.

20:07:09:941 WebsitBypass[cloudflare]: no Cloudflare solution found!
https://reaperscans.com/comics/535459-mercenary-enrollment

**Comment by Slasar41** [comment]
@AlirezaAmoupour Works fine here.
![image](https://user-images.githubusercontent.com/28888646/194987292-bb884396-a9ac-4c13-b717-168142505fd9.png)
You got the wrong url.

**Comment by ap-sensei** [comment]
@Slasar41 The number in the url is generated randomly. I tried it in the Chrome browser, and entered the new url. Again there was nothing.

Should I change the user-agent or cookies in the settings?

**Comment by Slasar41** [comment]
@AlirezaAmoupour Is it random?
I tried again the same link and it's still working fine.
https://reaperscans.com/comics/6251-mercenary-enrollment

I didn't do any workaround.

**Comment by ap-sensei** [comment]
So, I'm writing this for future visitors.

Whenever you have this problem, just hit the "**Update Manga List**". Then select the series you want to download.

If you don't see the chapter list, refresh it again. If that doesn't work, you should visit the URL in a **browser**. Then it forwards you to the **new URL** (_possibly with different numbers_), then you can enter it on FMD.

If that also doesn't work, close FMD and open again. Check your internet connection. Also you can change the "**user-agent**" of your FMD (_check options -> connection_) to the recent **Chrome** user-agent, which is:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`

I hope that helps! Thanks!
