### ISSUE TITLE
[bug] Readcomiconline download issue

### ISSUE THREAD

**Issue by EpicLunchBox** [dazedcat19/FMD#1089]
**Prerequisite**
- ✅ I'm using the latest version.
-  ✅ All website modules are up to date.

- ✅ This is not temporary server issue.

**System information**
Win10

**Describe the bug**
I can't download any comic from the website. In status shows "Failed, try resuming task!" I tried that and nothing changed at all. 

**Screenshots**
![Captura de pantalla (31)](https://user-images.githubusercontent.com/29029681/190548007-9f73e348-6468-4281-a8e3-b2e7d4a2b0aa.png)

**Comment by cobaltsardine** [comment]
I think this is related to the beau function in https://readcomiconline.li/Scripts/rguard.min.js?v=1.2.4 which obfuscates the image urls

**Comment by cobaltsardine** [comment]
@Slasar41 Could you help test this fix? 

Based on the rguard.min.js version 1.2.4 file and a previous issue in https://github.com/Xonshiz/comic-dl/issues/299, I figured out the code to de-obfuscate a single image identifier based on :

```wv = wv.replace(/_x236/g, "d").replace(/_x945/g, "g");
        if (wv.indexOf("https") !== 0) {
            var m = wv;
            var containsS = m.indexOf("=s0?") > 0
            var x = m.substring(m.indexOf("?"));
            if (containsS) {
            	m = m.substring(0, m.indexOf("=s0?"));
            } else {
            	m = m.substring(0, m.indexOf("=s1600?"));
            }
            m = m.substring(4, 22) + m.substring(25)
            m = m.substring(0, m.length - 6) + m[m.length - 2] + m[m.length - 1];
            m = decodeURIComponent(escape(atob(m)));
            m = m.substring(0, 13) + m.substring(17);
            if (containsS) {
            	m = m.substring(0, m.length - 2) + "=s0";
        	} else {
        		m = m.substring(0, m.length - 2) + "=s1600";
        	}
            m = m + x;
            wv = "https://2.bp.blogspot.com/" + m;
        }
```

I then put it through a javascript to lua converter online, and then put it into the GetPageNumber() function in ReadComicOnline.lua:

```
function GetPageNumber()
	local u = MaybeFillHost(MODULE.RootURL, URL .. '&quality=hq')
	if MODULE.GetOption('datasaver') then
		u = MaybeFillHost(MODULE.RootURL, URL .. '&quality=lq')
	end
	sleep(3000)
	if HTTP.GET(u) then
		local body = HTTP.Document.ToString()
		local s = body:match('var%s+lstImages%s+.-;(.-)%s+var%s')
		local i; for i in s:gmatch('%('(.-)'%)') do
			--new code based on view-source:https://readcomiconline.li/Scripts/rguard.min.js?v=1.2.4
			wv = i:gsub("_x236", "d")
			wv = wv:gsub("_x945", "g")
			if wv.indexOf("https") ~= 0 then
			    local m = wv
			    local containsS = m.indexOf("=s0?") > 0
			    local x = m.substring(m.indexOf("?"))
			    if containsS then
			        m = m.substring(0, m.indexOf("=s0?"))
			    else
			        m = m.substring(0, m.indexOf("=s1600?"))
			    end
			    m = m.substring(4, 22) + m.substring(25)
			    m = m.substring(0, m.length - 6) + m[m.length - 2] + m[m.length - 1]
			    m = decodeURIComponent(escape(atob(m)))
			    m = m.substring(0, 13) + m.substring(17)
			    if containsS then
			        m = m.substring(0, m.length - 2) + "=s0"
			    else
			        m = m.substring(0, m.length - 2) + "=s1600"
			    end
			    m = m + x
			    wv = "https://2.bp.blogspot.com/" + m
			end
			TASK.PageLinks.Add(wv)
		end
		return true
	else
		return false
	end
end
```

However, I run into problems trying to test it on fmd2. Do I have to install lua or compile fmd2 from source? I tried running fmd.exe after changing lua/modules/ReadComicOnline.lua directly but now it won't show up in the list of websites.

**Comment by Slasar41** [comment]
@cobaltsardine There's no need to compile FMD yourself to test a website module.
You can check `Options -> Misc. -> Logs` to see what happen with a failed website module.
