### ISSUE TITLE
[bug-website module] TuMangaOnline & Lectormanga doesn't work

### ISSUE THREAD

**Issue by Yoanlle** [dazedcat19/FMD#1097]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

**TuManagaOnline:** https://lectortmo.com/

Shows the Manga page, but without  cover or chapters. Just title, genres, author...

**LectorManga:** https://lectormanga.com/

Shows nothing, dont update manga list or anything.

**Comment by Slasar41** [comment]
Duplicate of https://github.com/dazedcat19/FMD2/issues/522 https://github.com/dazedcat19/FMD2/issues/523
