### ISSUE TITLE
[bug-website module] mcreader changed their domain again

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1100]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21h1 x64

### Describe the bug

mcreader changed their domain again. previously was https://www.mcreader.net/

now it is https://www.mreader.co/

example mangas the old one works on some
https://www.mcreader.net/manga/ochikobore-1-mahou-tsukai-wa-kyou-mo-muishiki-ni-cheat-wo-tsukau-manga/

https://www.mreader.co/manga/archmage-transcending-through-regression/

prob best to add new one with the old one since alot of mangas havnt been fully transfered over from what it seems, like what you guys did with manga-raw.club and mcreader

**Comment by Slasar41** [comment]
I checked both sites and the content in the home page is identical.
Maybe wait for the old domain to dies.

**Comment by jillybeans** [comment]
i only bring up because certain mangas get redirected to new one and fmd isnt picking up the new site
