### ISSUE TITLE
[website module request] readmanganato.com

### ISSUE THREAD

**Issue by IzumiMiyamura98** [dazedcat19/FMD#1109]
### Name

manganato

### Root URL

readmanganato.com

### Directory list URL

https://manganato.com/

### Example manga info URL

https://chapmanganato.com/manga-iz985608

### Example chapter URL

https://chapmanganato.com/manga-iz985608/chapter-126

### Language

English

### Website relationship

might be related to Mangakakalot.com

### Additional details

website was working in previous update but not now tried reinstalling but same problem.

{URL not supported}

**Comment by Slasar41** [comment]
readmanganato has been changed to chapmanganato https://github.com/dazedcat19/FMD2/commit/c2564801af1b5ebb509d8d649f02fa3da5487abf

**Comment by IzumiMiyamura98** [comment]
yes its been changed.
