### ISSUE TITLE
[URL Change] Manganato

### ISSUE THREAD

**Issue by Israld** [dazedcat19/FMD#1116]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

URL Change manganato to https://chapmanganato.com/
while it still can downloaded but the speed become almost non existence

**Comment by Slasar41** [comment]
Has been changed since a week ago. https://github.com/dazedcat19/FMD2/commit/c2564801af1b5ebb509d8d649f02fa3da5487abf
