### ISSUE TITLE
[bug-website module] Komikcast.me changed domain

### ISSUE THREAD

**Issue by Enryougoku** [dazedcat19/FMD#1120]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7 Ultimate 64Bit

### Describe the bug

Komikcast changed domain
From Komikcast.me into Komikcast.site
Download still works if i changed the domain manually on the address bar

**Comment by MIRVOUS** [comment]
now it doesn't work at all, please change
