### ISSUE TITLE
[bug] Can not load WebP codec

### ISSUE THREAD

**Issue by temp1366** [dazedcat19/FMD#1142]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 11 22h2

### Describe the bug

After opening the app it says:
Can not load WebP codec library "D:\En Manga\fmd2\libwebp.dll". Check your installation.

the solution in https://github.com/dazedcat19/FMD2/issues/756 is not working

### To Reproduce

    Download, unpack fmd_2.0.31.0_x86_64-win64.7z and start FMD2
    See error

### Expected behavior

 Run the program without errors

### Screenshots

![image](https://user-images.githubusercontent.com/29550019/204366782-02901c06-f15a-444a-a059-25c6f919ba38.png)

**Comment by Slasar41** [comment]
Try this one: https://github.com/dazedcat19/FMD2/blob/2b18d0140f5f1ba49ff77f7057234d9060bc852e/dist/x86_64-win64/libwebp.dll

**Comment by quixotic120** [comment]
that fixed it for me where the old fix did not, windows 10 22h2, thanks!
