### ISSUE TITLE
[feature request] Bulk relocation of downladed manga to another folder.

### ISSUE THREAD

**Issue by Anonym121** [dazedcat19/FMD#1146]
Hi,

I have downloaded more than 1500 mangas and I usually store them in two different folders in one drive.
Recently, free space in that drive is lacking so I wanted to relocate them to a new drive.
However, deleting the chapters and the manga from favorites and adding each manga again to favorites+redownload would be too much time consuming.

I checked and I didn't find an option that does something similar to this.
So I am requesting an option to select several manga in bulk in the favorites tab and move them to another folder while keeping the "check for new chapters option" enabled.

**Comment by Slasar41** [comment]
Try [this](https://github.com/dazedcat19/FMD2/issues/805#issuecomment-968738400).

**Comment by Anonym121** [comment]
hmm I cant try it, the "change save to" option is in gray color like it is blocked. Why can that be?

**Comment by Slasar41** [comment]
You must select the items first.

**Comment by Anonym121** [comment]
I'm selecting them with control+shift and control+click though. I dont see any boxes to tick, is there any other way of selection I am missing?

**Comment by Anonym121** [comment]
![image](https://user-images.githubusercontent.com/82741119/205241323-437086cf-9e28-4f2d-b6c9-4e3a227b238a.png)

**Comment by Slasar41** [comment]
Stop the check for favorites process.

**Comment by Anonym121** [comment]
Thank you, it works now.
｡^‿^｡

**Comment by Anonym121** [comment]
Okay, sorry for necroposting; but this apparently only changes where new chapters will be downloaded to. It doesn't autimatically move older downloads.
Is it fine to move them manually to the new folder or will there be any issue? Is there a way to do it automatically?
The series I want to move likely arent available anymore due to mangadex dmca, so I cannot redownload.

**Comment by Slasar41** [comment]
Yes, it's fine to manually move older downloads to new folder.
FMD only able to change the path for new download and doesn't move the older downloads.
