### ISSUE TITLE
[website module request] mangabuddy

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#1154]
### Name

mangabuddy

### Root URL

https://mangabuddy.com/

### Directory list URL

https://mangabuddy.com/latest

### Example manga info URL

https://mangabuddy.com/i-randomly-have-a-new-career-every-week

### Example chapter URL

https://mangabuddy.com/i-randomly-have-a-new-career-every-week/chapter-1

### Language

English

**Comment by Slasar41** [comment]
Duplicate of https://github.com/dazedcat19/FMD2/issues/896
