### ISSUE TITLE
[feature request] Higher res icon (potential replacement provided)

### ISSUE THREAD

**Issue by jesuscc1993** [dazedcat19/FMD#1168]
**Is your feature request related to a problem? Please describe.**
App currently only includes a 16px icon, which looks blurry in most situations.

**Describe the solution you'd like**
Higher res icons should be bundled with the app.

**Describe alternatives you've considered**
I have made an HD version of the icon, keeping it as close as posible to the original.
Feel free to do whatever you want with it, I won't demand any credit.
[md-ico.zip](https://github.com/dazedcat19/FMD2/files/10298797/md-ico.zip)

**Additional context**
Attached icon includes resolutions 16, 24, 32, 48 and 256, which should cover all use cases for Windows machines.

**Comment by Slasar41** [comment]
Thanks!
I'll use it for the next release.
