### ISSUE TITLE
[website module request] chapmanganelo

### ISSUE THREAD

**Issue by IzumiMiyamura98** [dazedcat19/FMD#1172]
### Name

chapmanganelo

### Root URL

chapmanganelo.com

### Directory list URL

https://m.manganelo.com/genre-all-update-latest

### Example manga info URL

https://chapmanganelo.com/manga-jm123932

### Example chapter URL

https://chapmanganelo.com/manga-jm123932/chapter-109

### Language

English

**Comment by ghost** [comment]
Yes please
