### ISSUE TITLE
[website module request] Mangaesp

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1177]
### Name

Mangaesp

### Root URL

https://mangaesp.co/

### Directory list URL

https://mangaesp.co/comic

### Example manga info URL

https://mangaesp.co/ver/t4c1t/

### Example chapter URL

https://mangaesp.co/ver/t4c1t/49

### Language

Spanish

**Comment by xx255q** [comment]
All i get is an access denied with trying to connect to this site

**Comment by Lenoyr** [comment]
> All i get is an access denied with trying to connect to this site

I have no problems viewing the website
![imagen](https://user-images.githubusercontent.com/65477084/230710689-914b1dc6-daed-4d29-ad16-dbf7cd2f1275.png)

They changed the URL of the posted manhwa, and now it's like this

![imagen](https://user-images.githubusercontent.com/65477084/230710833-fc4d5de6-7e45-445e-8e64-4a96a12a2b18.png)


### Example manga info URL
https://mangaesp.co/ver/t4c1t

### Example chapter URL
https://mangaesp.co/ver/t4c1t/49
