### ISSUE TITLE
[bug-website module] Hiperdex changed back its domain to Hiperdex.com

### ISSUE THREAD

**Issue by zillafox** [dazedcat19/FMD#1178]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Pro 21H1 build 19043.2364

### Describe the bug

https://1sthiperdex.com/ has changed back its urls to https://hiperdex.com/ for whatever reasons

now cannot update list from Hiperdex due to this reason. it refuses to download or discover manga from the website

**Comment by Slasar41** [comment]
Reverted https://github.com/dazedcat19/FMD2/commit/368ed242ce91f5bb3c3bcc5bc39344b477f8c182

**Comment by zillafox** [comment]
this is happening once again, they changed back its urls from  https://hiperdex.com/ to https://1sthiperdex.com/

is there anyway to somehow make both domain work nicely even if they recycle its domain?
