### ISSUE TITLE
[website module request] Mangastk18

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1179]
### Name

Mangastk18

### Root URL

https://mangastk18.com/

### Directory list URL

https://mangastk18.com/serie/

### Example manga info URL

https://mangastk18.com/serie/cosplay-lascivo-con-marin/

### Example chapter URL

 https://mangastk18.com/serie/cosplay-lascivo-con-marin/capitulo-1/

### Language

Spanish

**Comment by xx255q** [comment]
#1226
