### ISSUE TITLE
[website module request] Mangastk

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1180]
### Name

Mangastk

### Root URL

https://mangastk.xyz/

### Directory list URL

https://mangastk.xyz/serie/

### Example manga info URL

https://mangastk.xyz/serie/revelacion-de-la-juventud/

### Example chapter URL

https://mangastk.xyz/serie/revelacion-de-la-juventud/1/

### Language

Spanish

**Comment by xx255q** [comment]
#1225

**Comment by Lenoyr** [comment]
Dead Site
"Good evening/good day/good afternoon, please receive a warm greeting everyone. This message is to inform you that 'MANGASTK' is permanently closed. We reserve our privacy policy. Thank you and goodbye." 
It is a message from your Telegram.

![imagen](https://github.com/dazedcat19/FMD2/assets/65477084/c6c338c7-8632-4fd7-bc99-f80a5d24e0f3)
