### ISSUE TITLE
[bug-website module] Nitro Scans is now darkscans

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1182]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21h1 x64

### Describe the bug

nitroscans https://nitroscans.com/
is now darkscans https://darkscans.com/
they changed their site so the module needs to be updated

**Comment by jillybeans** [comment]
i fixed it myself by editing the module in madara, and replacing the nitoscans with darkscans, and it worked for anyone wanting a quick fix until an official one come through

**Comment by xx255q** [comment]
#1224

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/commit/e55c30c1d6ce4638e1e6288c4358f5a4d1438314
