### ISSUE TITLE
[bug-website module] https://www.mreader.co/ changed its domain

### ISSUE THREAD

**Issue by zartzaku** [dazedcat19/FMD#1192]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 7

### Describe the bug

https://www.mreader.co/ changed its domain into https://www.mangageko.com/

**Comment by jillybeans** [comment]
i did a minor fixed by replacing the mreader,co, with the mangageko.com in the lua. everything is still the same just a change in domain

**Comment by Qizmo** [comment]
> i did a minor fixed by replacing the mreader,co, with the mangageko.com in the lua. everything is still the same just a change in domain

A question please. For this change,
Do I only change inside the part "	m.RootURL                    = 'https://www.mreader.co'" only?
Or do I also need to change the "MReader.lua" on the file itself?

**Comment by xx255q** [comment]
#1219
