### ISSUE TITLE
[bug-website module] Hiperdex changed back its domain (Again)

### ISSUE THREAD

**Issue by zillafox** [dazedcat19/FMD#1195]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Pro 21H1 build 19043.2364

### Describe the bug

this is happening once again, they changed back its urls from https://hiperdex.com/ to https://1sthiperdex.com/

is there anyway to somehow make both domain work nicely even if they recycle its domain to either both?

**Comment by xx255q** [comment]
Seems its currently at https://hiperdex.com/, are you still having issues?

**Comment by Slasar41** [comment]
It changed to .net and I've pushed the update. https://github.com/dazedcat19/FMD2/commit/bfb8035778ee83f81c959b3811a91ee6cffd6fbe
