### ISSUE TITLE
[bug-website module] Legionasia domain changed 

### ISSUE THREAD

**Issue by horacio881** [dazedcat19/FMD#1196]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windowa 10

### Describe the bug

https://legionasia.com/ changed its domain into https://mhscans.com/

Example:

Old: https://legionasia.com/manga/infinite-leveling-murim/
New: https://mhscans.com/manga/infinite-leveling-murim/

**Comment by xx255q** [comment]
mhscans has been added #1221
