### ISSUE TITLE
[bug] Modules list is blank! 

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD#1197]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 20H2 x64

### Describe the bug

The entire module lists is blank so unable to check for updates!   So far everything else seems to be working but I have no idea if any of the websites are out of date or not as you can see from the screenshot below. 

I had to lie on checkbox all website modules are up to date as I am unable to check.

### To Reproduce

1. Go to Module Lists and see no modules to update or any modules at all

### Expected behavior

List of modules installed with the time they were last updated

### Screenshots

![Module Lists Blank](https://user-images.githubusercontent.com/16074561/219918951-014a1c1d-064a-4fa0-9cad-636c01e9229e.jpg)

Seems the auto updater has not been working for a while now when I look at last update for any of the databases, so I have archived the entire folder and put up on Mega so you can see if you can determine why this happened. Right now I am downloading app again and will copy over my db for favorites and other configs and let it download all modules. 

FMD 2.0 Archive
https://mega.nz/file/rZQS0JQC#iQvFgfozIrMA7g_UYOpkRPyITAqPXV7oG0zbYjZ8f2o

**Comment by xx255q** [comment]
Did downloading the app again work?

**Comment by molitar** [comment]
Yes I redownloaded the app and only moved over my downloaded and favorite databases to get it working again
