### ISSUE TITLE
[website module request] 

### ISSUE THREAD

**Issue by flysk1** [dazedcat19/FMD#1198]
### Name

manhuavn.top

### Root URL

https://manhuavn.top/index.html

### Directory list URL

It's come from IOS or Android apk

### Example manga info URL

It's come from IOS or Android apk

### Example chapter URL

It's come from IOS or Android apk

### Language

Vietnamese

### Website relationship

No.

### Additional details

I want download manga from this app to my computer, if chapters free -> download normal, if chapters vip, can login by my account already buy these chapters vip and download.

If this request need to pay for add this site to fmd as private, I'm ready pay for it!

**Comment by nghyane** [comment]
Same request
