### ISSUE TITLE
[bug-website module] manhuas not working

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#1203]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Lite 64-bit 

### Describe the bug

Maybe because manhuas changed the domain from .net to .com it's not working anymore. The site is running fine. 
![image](https://user-images.githubusercontent.com/24958560/221436226-0c6af54f-66b5-48b5-8de0-663573410f68.png)
![image](https://user-images.githubusercontent.com/24958560/221436238-d8c6d00b-3ee4-4e5f-8ef1-24d12862f803.png)

**Comment by xx255q** [comment]
Is it working now? I just tried your same link and checked the module which seems to have updated to .com and seems to work

<img width="672" alt="Capture" src="https://user-images.githubusercontent.com/42384590/229212685-c161056a-1371-400d-a0e6-97a263cb9dcc.PNG">

**Comment by Souravi785** [comment]
Yeah. It's working now.
