### ISSUE TITLE
[bug-website module] Olympusscans domain changed

### ISSUE THREAD

**Issue by rs3mk** [dazedcat19/FMD#1205]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11

### Describe the bug

Now use api: https://dashboard.olympusscans.com/api

Info: https://dashboard.olympusscans.com/api/series/realmente-no-quiero-renacer/chapters/32410?type=comic
Chapters: https://dashboard.olympusscans.com/api/series/apotheosis/chapters?page=1&per_page=100&direction=desc&type=comic
Last: https://dashboard.olympusscans.com/api/new-chapters?page=1
Comics: https://dashboard.olympusscans.com/api/series?page=1&direction=asc&type=comic

**Comment by Rhisk** [comment]
Olympusscans change from https://olympusscanlation.com/ to https://olympusscans.com
before for list of chapters the links was as shown in the following example:
https://olympusscanlation.com/manga/el-rey-del-apocalipsis/ 
now is
https://olympusscans.com/series/comic-el-rey-del-apocalipsis

**Comment by djgerman10** [comment]
justo lo iba a reportar xD

**Comment by xx255q** [comment]
Can you confirm that the correct API, I just going to it and get 404 error. Also, I have done some testing and when I updated the URL for the site the module still had issues but if I used a direct link to a manga I was able to successfully download it
