### ISSUE TITLE
[bug-website module] KomikIndoID change its domain

### ISSUE THREAD

**Issue by iyuzuri** [dazedcat19/FMD#1208]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 x64

### Describe the bug

KomikIndoID change its domain from `komikindo.id` to `komikindo.pro`

**Comment by xx255q** [comment]
I did switch the website link to https://komikindo.pro but it seems to not have made a difference, still getting 404 error

**Comment by xx255q** [comment]
#1222 the domain needing to be updated ot .pro and the list for manga had a change. downloading list from the server fails but you can download the list and direct link to manga works now
