### ISSUE TITLE
[website module request] Mangaeffect (Madara template)

### ISSUE THREAD

**Issue by HiP1** [dazedcat19/FMD#1218]
### Name

MangaEffect

### Root URL

https://mangaeffect.com/

### Directory list URL

https://mangaeffect.com/manga/

### Example manga info URL

https://mangaeffect.com/manga/the-irregular-of-the-royal-academy-of-magic/

### Example chapter URL

https://mangaeffect.com/manga/the-irregular-of-the-royal-academy-of-magic/chapter-80/

### Language

English

### Website relationship

Uses the "madara" template.

**Comment by HiP1** [comment]
in the meantime, i replaced the URL of one i didn't use in the madara.lua file, and it worked. only the initial manga list from server didn't work, but updating the list worked.

**Comment by xx255q** [comment]
#1220

**Comment by HiP1** [comment]
we can probably close this then. we don't really need the manga list from server if the update list works ?

**Comment by xx255q** [comment]
We should keep this open until the pull is merged
