### ISSUE TITLE
[bug-website module]  Phoenix Fansub - Phoenix Mangas

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1241]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Pro 21H1

### Describe the bug

They changed their site from "https://phoenixfansub.com/" to "https://phoenixmangas.com/."

Root URL:  https://phoenixmangas.com
Updated Directory list URL: https://phoenixmangas.com/manga/
Example of new manga info URL: https://phoenixmangas.com/manga/release-that-witch/
Example chapter URL: https://phoenixmangas.com/manga/release-that-witch/capitulo-498/

Thanks, great job you do.

**Comment by Trollam** [comment]
All the domains seem to be for sale.
@Lenoyr Do you know if they changed the domain again?

**Comment by Lenoyr** [comment]
Website is dead
