### ISSUE TITLE
[bug] can't catch on hiperdex

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1259]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

windows 10

### Describe the bug

can't catch the chapter from hiperdex.com
it's fix when changing the domain from .com to .net
but now it's doesnt work anymore
the cover and description can be catch, but the chapter is blank
![Screenshot 2023-05-26 032209](https://github.com/dazedcat19/FMD2/assets/89280778/a3ba2fd5-17d7-4f7b-a9f3-eabe69570f6b)

### To Reproduce

1. go to the website
2. copy paste the link on the fmd
3. it's doesnt work to catch the chapter

### Expected behavior

it's can work like usually again, the aplication can capture all the chapter again from the .com domain n .net domain from hiperdex

**Comment by Slasar41** [comment]
The domain changed again so I revert it. https://github.com/dazedcat19/FMD2/commit/a041b8441344816c8063cfb373b0366e25a6644f
