### ISSUE TITLE
[bug-website module] Realm Scans domain change

### ISSUE THREAD

**Issue by Purplem** [dazedcat19/FMD#1286]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22h2 x64

### Describe the bug

Realm Scans changed their domain
Old: https://realmscans.com

New: https://realmscans.xyz/

**Comment by jpwong2** [comment]
Also just want to note that if you update the module to use the new site, the way they've got their page code working, every series on the site ends up being "The Little Brother Is The Academy's Hotshot" when you try to download/add to favourites.

Ended up having to add the following to the getTitle in the MangaShiro lua to get the program to grab the correct titles

`if MODULE.ID == '3593adad980d454abe489c42e7158032' then title = x.XPathString('//h1[@class="entry-title"]') end -- RealmScans`
