### ISSUE TITLE
[bug-website module] Asurascans domain changed

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#1296]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 64-bit

### Describe the bug

https://asurascans.com/ became https://asura.gg/ and I can't update the manga list or load, as well as download them. 

Root URL: https://asura.gg/
Updated Directory list URL: https://asura.gg/manga/?page=1&order=update
Example of new manga info URL: https://asura.gg/manga/0223090894-the-knight-king-who-returned-with-a-god/

**Comment by jillybeans** [comment]
do you know which module/lua it is under?

**Comment by jillybeans** [comment]
a simple fix since nothing was changed but the domain. go to the mangashiro.lua and search asura scans, change the previous https://asurascans.com to the new https://asura.gg.
and it should work like it used to

**Comment by Souravi785** [comment]
Can you change it? I'm a beginner at this.

**Comment by TechTrooper** [comment]
> a simple fix since nothing was changed but the domain. go to the mangashiro.lua and search asura scans, change the previous https://asurascans.com to the new https://asura.gg. and it should work like it used to

Modified
`AddWebsiteModule('7103ae6839ea46ec80cdfc2c4b37c803', 'AsuraScans', 'https://www.asurascans.com')`
to
`AddWebsiteModule('7103ae6839ea46ec80cdfc2c4b37c803', 'AsuraScans', 'https://www.asura.gg')`

Result
![image](https://github.com/dazedcat19/FMD2/assets/3955313/89ca1b87-0c4e-40dc-a7a8-bf240fbd2e8b)

**Comment by Souravi785** [comment]
I tried changing the domain name and it's working now.

**Comment by Souravi785** [comment]
Asura changed the domain again. Now it's https://asura.nacm.xyz/

I tried to change it myself, but somehow I couldn't find asura.gg on Mangashiro.lua. Can somebody change the domain name again?

**Comment by Stabilostick** [comment]
> I tried to change it myself, but somehow I couldn't find asura.gg on Mangashiro.lua. Can somebody change the domain name again?

```
	cat = 'English-Scanlation'
	AddWebsiteModule('7103ae6839ea46ec80cdfc2c4b37c803', 'AsuraScans', 'https://asura.nacm.xyz')
```
