### ISSUE TITLE
[website module request] NicoManga RAW 

### ISSUE THREAD

**Issue by Dgraid12** [dazedcat19/FMD#1305]
### Name

NicoManga

### Root URL

https://nicomanga.com/

### Directory list URL

https://nicomanga.com/manga-list.html

### Example manga info URL

https://nicomanga.com/manga-katainaka-no-ossan-ken-hijiri-ni-naru.html

### Example chapter URL

https://nicomanga.com/read-katainaka-no-ossan-ken-hijiri-ni-naru-chapter-21.html

### Language

Raw

### Website relationship

It is related to welovemanga (https://welovemanga.one/)

**Comment by TienVer** [comment]
Already here:
https://github.com/dazedcat19/FMD2/issues/1263

**Comment by ujjwalg55** [comment]
> Already here: #1263

download from server not working, also new modules not downloading. i'm using latest version. also when i download fmd 2 again from server no website show in manga info. please help
![Screenshot (130)](https://github.com/dazedcat19/FMD2/assets/143864490/49c93c95-7d21-4fc2-aa84-3f3af21b9ff6)
![Screenshot (129)](https://github.com/dazedcat19/FMD2/assets/143864490/7dd85e60-c280-4699-8221-7d990615a7d1)
