### ISSUE TITLE
[bug-website module] FMD is not grabbing the title of webtoon from asura scans

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1315]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21h1 x64

### Describe the bug

![214](https://github.com/dazedcat19/FMD2/assets/52017476/757f1880-1f6f-4c24-b0af-51fe0a852ea3)
https://asuracomics.com/ is not grabbing the title, i dont know if lua was updated but ive changed it to the updated site myself sometime ago. but the title once it grabs becomes like the picture only started today.

https://asuracomics.com/manga/9141111445-demonic-evolution/

**Comment by BottomTierDev** [comment]
I don't know how to fix it the proper way but in your /lua/modules/MangaShiro.lua file, find
```function getTitle(x)```
then after after 
```if title == '' then title = x.XPathString('//h2') end"```
add
```if title == 'asura scans manhwa comic' then title = x.XPathString('//h1[@class="entry-title"]') end```
I haven't fully tested it but after fixing this weeks broken favourites it seems to work.

**Comment by jillybeans** [comment]
seems to work, so far. i only tested on a few

**Comment by Slasar41** [comment]
Issue not appearing again.
