### ISSUE TITLE
[bug-website module] Asurascans manga name not appearing

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#1319]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 64-bit

### Describe the bug

When downloading from asurascans, instead of the manga name, the title appears as 'asura scans manhwa comic.' 

![image](https://github.com/dazedcat19/FMD2/assets/24958560/ac08ca30-a64a-4462-a5b0-b6a66414914f)
![image](https://github.com/dazedcat19/FMD2/assets/24958560/50fa0c92-3427-4a0c-a3d0-44131c709ad0)

What's happening here?

**Comment by jpwong2** [comment]
Asura changed their layout and the manga title part now looks similar to how realmscans is doing their manga titles.

if you add this to the getTitle(x) section in the mangashiro lua in front of the other if statements it should start grabbing the title again.
if MODULE.ID == '7103ae6839ea46ec80cdfc2c4b37c803' then title = x.XPathString('//h1[@class="entry-title"]') end -- AsuraScans

**Comment by Souravi785** [comment]
Not working.

Am I doing it wrongly?

![image](https://github.com/dazedcat19/FMD2/assets/24958560/da55fba7-bc69-4526-9b8f-ddb1cf1cdfa7)

**Comment by Souravi785** [comment]
The manga title is showing, but it's not downloading. 

![image](https://github.com/dazedcat19/FMD2/assets/24958560/9fc84e99-c347-4153-bb52-6ca336935a5b)
![image](https://github.com/dazedcat19/FMD2/assets/24958560/4ea9d591-e6c7-4794-8de8-371e166d71fd)

It's downloading only the cover page.

**Comment by Souravi785** [comment]
This manhwa is working for some reason.

![image](https://github.com/dazedcat19/FMD2/assets/24958560/05213a92-f348-4a34-915e-51b8de7a3a57)

**Comment by jpwong2** [comment]
> The manga title is showing, but it's not downloading.
> 
> ![image](https://user-images.githubusercontent.com/24958560/277031061-9fc84e99-c347-4153-bb52-6ca336935a5b.png) ![image](https://user-images.githubusercontent.com/24958560/277031146-4ea9d591-e6c7-4794-8de8-371e166d71fd.png)
> 
> It's downloading only the cover page.

There's a fix for that listed over here https://github.com/dazedcat19/FMD2/issues/1336

**Comment by jillybeans** [comment]
welp recent update to lua broke the title again

**Comment by Souravi785** [comment]
Any fix?

**Comment by jpwong2** [comment]
> Any fix?

If you want Asura's stuff to work again if you got the new update, you need to apply the fix listed in this thread, the fix listed in 1336, and update the address of their site to the current address in the mangashiro lua file.

**Comment by Souravi785** [comment]
![image](https://github.com/dazedcat19/FMD2/assets/24958560/e6d57013-7448-42be-a8a3-c55299529bfb)
![image](https://github.com/dazedcat19/FMD2/assets/24958560/b53da1ca-6fc0-441e-b915-cc98ea9dbb80)
![image](https://github.com/dazedcat19/FMD2/assets/24958560/430dace1-cb2e-4fc5-82c4-06241d39c948)

Can't find the third one.

**Comment by jpwong2** [comment]
The third item would be what's referenced in issue #1336 
It's in the GetPageNumber() section, you have to update the xpath for asura's reader.

**Comment by Souravi785** [comment]
![image](https://github.com/dazedcat19/FMD2/assets/24958560/2464c05a-70ba-4d32-ae5a-50f77175f0a5)
![image](https://github.com/dazedcat19/FMD2/assets/24958560/ccecd701-227a-48ff-9261-8ebca1dbc484)

Not working.

**Comment by jpwong2** [comment]
Did you completely close out the application and restart it after you made the changes?  If you update the modules while FMD is running it won't pick up the changes until after you shut it down and restart the program

**Comment by Souravi785** [comment]
Oh, I overlooked that. It's working now. Thanks.

**Comment by Slasar41** [comment]
The issue doesn't appear again.
