### ISSUE TITLE
[bug-website module] hiperdex domain changed address to hiperdex.xyz

### ISSUE THREAD

**Issue by zillafox** [dazedcat19/FMD#1325]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 64bit

### Describe the bug

Hiperdex sometimes change its domain from hiperdex.com changed its address to hiperdex.xyz

and it changed back after sometime (maybe in a month)
just now the working one is hiperdex.xyz thus our module that based on hiperdex.com isnt working

**Comment by joeb2000** [comment]
I looked just now and the .com domain is still working perfectly fine for me.

I even tried manually going to the .xyz domain and it forwards back to the .com.
