### ISSUE TITLE
Workaround for cloudflare protected websites

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD#1329]
**This workaround only works on Windows x64.**

- Download [Python](https://www.python.org/). Enable "Add python.exe to PATH" from the Python installation screen
- Open CMD and type `pip install requests` or `python -m pip install requests`
- Download [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr). Extract to `lua\websitebypass`
- Create a file named `use_webdriver` in `lua\websitebypass`
- Run `flaresolverr.exe` in `lua\websitebypass\flaresolverr` everytime FMD need to access cloudflare protected websites

**Comment by mastafrooper** [comment]
I assume because the actual program can't be updated it can't be modified to use an already existing FlareSolverr instance then?

I'll get this fired up then.

**Comment by alzamer2** [comment]
hello
i want to ask
after the update 
should i Download [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr). Extract to lua\websitebypass?
because there is no note in changelog or in lua\websitebypass tell me to do that

**Comment by l-l-l-l-l-l** [comment]
Is there no way to automatically run FlareSoverr when needed?

**Comment by Tmp341** [comment]
> Is there no way to automatically run FlareSoverr when needed?

On windows, you can create a batch file for your benefits, and let it run on startup/at specific time/when an app launched etc.

**Comment by Black-Dalek** [comment]
No cigar, flaresovver is running, but no conecctions: 
![imagen](https://github.com/dazedcat19/FMD2/assets/36430844/ba420f2e-588c-46fc-9808-a95becbcbef5)

**Comment by alzamer2** [comment]
just making sure you
> * Create a file named `use_webdriver` in `lua\websitebypass`

right?

**Comment by Black-Dalek** [comment]
> just making sure you
> 
> > * Create a file named `use_webdriver` in `lua\websitebypass`
> 
> right?

Yes: 
![imagen](https://github.com/dazedcat19/FMD2/assets/36430844/57989734-3ec8-4e07-a116-59e072623dc5)

now, i only got an " 500 internal server error"

**Comment by alzamer2** [comment]
[customcloudflare.zip](https://github.com/dazedcat19/FMD2/files/13767105/customcloudflare.zip)
use this file instead
this one has logger added
and it will tell you if code is running or not

this file was not changed it was only logger added

**Comment by alzamer2** [comment]
> > just making sure you
> > > * Create a file named `use_webdriver` in `lua\websitebypass`
> > 
> > 
> > right?
> 
> Yes: ![imagen](https://private-user-images.githubusercontent.com/36430844/292604621-57989734-3ec8-4e07-a116-59e072623dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDQ0ODksIm5iZiI6MTcwMzY0NDE4OSwicGF0aCI6Ii8zNjQzMDg0NC8yOTI2MDQ2MjEtNTc5ODk3MzQtM2VjOC00ZTA3LWExMTYtNTllMDcyNjIzZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAyMjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjY2IyNTliZjFkN2MwMTUwYzY2ZTUxNDliNjE5MTVhZTViNjIzOGY5YjVlMDAwZjkwOGFhMzlhOGJjNGRhOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r847FehgRKrIgnHcPJEpPONFa2rHn6yGX_lW25RiOWc)
> 
> now, i only got an " 500 internal server error"

i just checked code
is the flaresolver executable directory "lua\websitebypass\flaresolverr\flaresolverr.exe"?

**Comment by Black-Dalek** [comment]
> > > just making sure you
> > > > * Create a file named `use_webdriver` in `lua\websitebypass`
> > > 
> > > 
> > > right?
> > 
> > 
> > Yes: ![imagen](https://private-user-images.githubusercontent.com/36430844/292604621-57989734-3ec8-4e07-a116-59e072623dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDQ0ODksIm5iZiI6MTcwMzY0NDE4OSwicGF0aCI6Ii8zNjQzMDg0NC8yOTI2MDQ2MjEtNTc5ODk3MzQtM2VjOC00ZTA3LWExMTYtNTllMDcyNjIzZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAyMjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjY2IyNTliZjFkN2MwMTUwYzY2ZTUxNDliNjE5MTVhZTViNjIzOGY5YjVlMDAwZjkwOGFhMzlhOGJjNGRhOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r847FehgRKrIgnHcPJEpPONFa2rHn6yGX_lW25RiOWc)
> > now, i only got an " 500 internal server error"
> 
> i just checked code is the flaresolver executable directory "lua\websitebypass\flaresolverr\flaresolverr.exe"?

yes: lua\websitebypass\flaresolverr

**Comment by mooglestiltzkin** [comment]
assuming "lua\websitebypass\flaresolverr\flaresolverr.exe" is correct.

then "lua\websitebypass\" is where u put the 
checkantibot.lua
cloudflarebot.lua
cloudflare.js
cloudflare.lua
cloudflare.py
customcloudflare.py
ddos-guard-lua
use_webdriver.lua
websitebypass.lua

because if it isn't there, fmd will complain it's missing and suggest you download it to there.

https://github.com/dazedcat19/FMD2/tree/master/lua/websitebypass

**Comment by Plegmatis** [comment]
i have everything set perfectly but still can't manage to download normally, either its jsut failed, cookies getting deleted, completed but broken images, etc

this is my flaresolverr, it said successful but nothing happened after that 
![image](https://github.com/dazedcat19/FMD2/assets/26659986/ce2d5b6a-b561-4208-99bf-26a3e1ae6909)

**Comment by Miri-Gzl** [comment]
I don't understand how to do it, can someone help me?

**Comment by Slasar41** [comment]
New workaround in the pinned issue
