### ISSUE TITLE
[bug] Filters no longer work in 2.0.32.0

### ISSUE THREAD

**Issue by swisscheez** [dazedcat19/FMD#1330]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 HOme 10.0.19045

### Describe the bug

On the Manga Info tab, Filters no longer work.  After entering any filter criteria, pressing the filter button does not filter the results on the left.  

### To Reproduce

go to manga info, 
select 'filter' from the tabs on the right middle of the screen,
update any filter criteria,
press filter button
expected result - the filter is applied, actual result - no filter applied.

### Expected behavior

Filters are applied after pressing the Filter button

**Comment by swisscheez** [comment]
Now i'm not sure what's going on. i reverted back to 2.0.31.0 and that filter process seems to have stopped working as well. Then i relaunched 2.0.32.0 and the filtering partially worked when clicking on a genre and filtering.  i'm going to close this ticket and open another if i can isolate specific scenarios.

**Comment by boppen** [comment]
I've had the same problem, looking in the logs there were a bunch of sqlite errors and the one that stood out most to me was 
`EXCEPTION: TDBDataProcess[8e7bd7b38aa041aa9bc1bddeec33b6f4].AttachAllSites.Error! try to attach 'LeviatanScansEN' TSQLite3ConnectionH : too many attached databases - max 10`

I've reverted the sqlite3 dll to the one from 2.0.30.0 and for now it looks like the searching works well.
