### ISSUE TITLE
[bug-website module] Webtoon cant load new list

### ISSUE THREAD

**Issue by zillafox** [dazedcat19/FMD#1331]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 64 bit

### Describe the bug

Only some address from webtoon is working and updating its list, but most of them doesn't work . This has been everytime i tried to check the new chapters

![Capture](https://github.com/dazedcat19/FMD2/assets/24423458/0f9492a2-721c-48ec-94eb-b681b0bc4434)
![Capture2](https://github.com/dazedcat19/FMD2/assets/24423458/7d5121e8-5210-46b3-8267-8c6848d31d33)

**Comment by rs3mk** [comment]
The same happened to me. It happened after the program was updated to 2.0.32.0

To fix it, you need to download the previous version 2.0.31.0 and replace the main executable. And disable the update until they fix that problem in the new version.

https://github.com/dazedcat19/FMD2/releases/tag/2.0.31.0

![image](https://github.com/dazedcat19/FMD2/assets/19628943/a04c0a46-7c7a-4447-9e3a-ae492facddc1)

**Comment by Slasar41** [comment]
Could you give a link for the working and not working one?

**Comment by zillafox** [comment]
Hi creator, thanks for the response! 

pls find some of what i have found as belows
working: 
https://www.webtoons.com/en/horror/everything-is-fine/list?title_no=2578
https://www.webtoons.com/en/romance/love-or-sex/list?title_no=5395

not working:
https://www.webtoons.com/en/action/wind-breaker/list?title_no=372
https://www.webtoons.com/en/supernatural/flawed-almighty/list?title_no=3577
https://www.webtoons.com/en/fantasy/questism/list?title_no=3767

**Comment by NhKPaNdA** [comment]
Don't know why the module was working in the previous build but it was causing infinite looping in the latest build since it was grabbing every page link for chapters instead of only the immediate next.

You can fix it yourself by changing on line 27 `following-sibling::a/@href` to `following-sibling::a[1]/@href` for build 2.032.0 or what for a module update.

**Comment by Uroth** [comment]
> You can fix it yourself by changing on line 27 `following-sibling::a/@href` to `following-sibling::a[1]/@href` for build 2.032.0 or what for a module update.

I can confirm, this worked for me.
\lua\modules\WebToons.lua
