### ISSUE TITLE
[bug-website module] Rawkuma.com cannot download manga list (404 Error)

### ISSUE THREAD

**Issue by kamikaze00007** [dazedcat19/FMD#1332]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Trying to download the manga list from rawkuma.com returns a 404 error constantly.

**Comment by Slasar41** [comment]
Fixed by https://github.com/dazedcat19/FMD2-DB/commit/f82dc9d584042061e93df2fd8cfba7a04ee69c21
