### ISSUE TITLE
[bug] Filters no longer work

### ISSUE THREAD

**Issue by greenaar** [dazedcat19/FMD#1334]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 11

### Describe the bug

Manga Info/Filter - none of the options do anything in 2.0.32.0.  The list does not update to show filtered items.  The exact same steps in 2.0.31.0 work properly.

### To Reproduce

Go to Manga Info/Filter.

Select anything.  Hit filter.

### Expected behavior

The manga list should filter to the selected item(s).  In 2.0.32.0, this does not happen.  Nothing happens.

### Additional context

As mentioned above, this is a new bug with the latest version, and is not present in the previous version.

**Comment by Slasar41** [comment]
Did you mean this?
![image](https://github.com/dazedcat19/FMD2/assets/28888646/583c6039-73a5-4918-beb9-523c3885f4c6)
Works fine here.

**Comment by iu3kxa** [comment]
I have exact the same problem and the same situation, as described from Greenar, except i'm running windows 10 ltsc.
At least is there a way to rollback?

edit: solved by downgrading sqlite3.dll as described in this thread.

**Comment by iu3kxa** [comment]
04:39:41:721 CALL STACK: TSQLite3ConnectionH Error 1: no such column: 2
                 $0048C7FE
                 $0048CA0A
                 $006A33F1
                 $006A614C
                 $00474BCD
                 $00501428
                 $0059B7FA
                 $0059BE30
                 $00587BCC
                 $0059B729
                 $0040FDB1
                 $004F66FB
                 $005F526A
                 $0057CA05
                 $0057D081
                 $7630137B
                 $762F834A
                 $762F7F4A
                 $762FBB0F
                 $77024F6D
04:39:41:722 EXCEPTION: TDBDataProcess[0d3653a8d9b747a381374f32e0a1641e].Filter.Error!
SQL:
SELECT * FROM
(
SELECT *, "-1" AS "website" FROM "masterlist"
WHERE
"title" LIKE '%southern%'
UNION ALL
SELECT *, "0" AS "website" FROM "8e7bd7b38aa041aa9bc1bddeec33b6f4"."masterlist"
WHERE
"title" LIKE '%southern%'
UNION ALL
SELECT *, "1" AS "website" FROM "de4684706931463da794bb45377f4c3e"."masterlist"
WHERE
"title" LIKE '%southern%'
UNION ALL
SELECT *, "2" AS "website" FROM "e9f4e7fe53bc4ff6921db6d67c9b9fb2"."masterlist"
WHERE
"title" LIKE '%southern%'
)
ORDER BY "title" COLLATE NATCMP
 TSQLite3ConnectionH : no such column: 2

**Comment by TanookiSama** [comment]
By my testing, the filters are broken, but only when **"Search only new manga"** or **"Search in all manga sites"** are checked.

**Comment by Irfan-Luthfi** [comment]
Yeah, same with me, even if we don't click any filter and just check the 'Search only new manga' option, it will not be updated. I actually want to know, from the recent updates, what are the new manga/comics when using the 'Search only new manga' feature.

**Comment by boppen** [comment]
Going to copy what I wrote in another ticket about filters (#1330), will hopefully work for others as well.

I've had the same problem, looking in the logs there were a bunch of sqlite errors and the one that stood out most to me was
`EXCEPTION: TDBDataProcess[8e7bd7b38aa041aa9bc1bddeec33b6f4].AttachAllSites.Error! try to attach 'LeviatanScansEN' TSQLite3ConnectionH : too many attached databases - max 10`

I've reverted the sqlite3 dll to the one from 2.0.30.0 and for now it looks like the searching works well.

**Comment by TanookiSama** [comment]
Huh. Tired the sqlite3.dll from 2.0.31.0 just now, and that worked. Did #441 probably break this in some unexpected way?

**Comment by soultaco83** [comment]
I have tried sqllite.dll from both 2.0.31.0 and 2.0.30.0 but no use. Search only partly works using the older versions. I can not use the search all sites. I have to use the search for a single site via the left side of the selections.

**Comment by fizzywiz** [comment]
Replacing the 2.0.31.0 sqlite3.dll fixed this for me.

**Comment by molitar** [comment]
yeah hope to be fixed soon

**Comment by Beanux** [comment]
According to the readme from the dist:
https://github.com/dazedcat19/FMD2/tree/dc4240f10045d88d564d9bb39afff71afb27075d/dist
The sqlite embded was a custom build with '-DSQLITE_LIMIT_ATTACHED=125'

With the method given by sqlite, i've rebuild it with the last version (with 300 instead of only 125, it wasn't enougth sometimes).
https://www.sqlite.org/howtocompile.html#building_a_windows_dll
```
apt install mingw-w64
wget https://www.sqlite.org/2023/sqlite-autoconf-3440000.tar.gz
tar xzf sqlite-autoconf-3440000.tar.gz
cd sqlite-autoconf-3440000
x86_64-w64-mingw32-gcc -DSQLITE_LIMIT_ATTACHED=300 -shared sqlite3.c -o sqlite3.dll
```

By using the new dll, it was fixed.
So that could mean the packaged dll wasn't the one from the folder from dist.


Here is the builded lib, **but you shouldn't trust me and build it yourself** on a WSL debian/ubuntu to be safe.
[sqlite3.zip](https://github.com/dazedcat19/FMD2/files/13402961/sqlite3.zip)

**Comment by Slasar41** [comment]
@Beanux Does your instructions also build 32 bit version?

**Comment by Beanux** [comment]
Normaly to be built in 32 bit, it should be **i686-w64-mingw32-gcc** to be used instead of x86_64-w64-mingw32-gcc.
I didn't tested it, but i builded it, and it should be promising.
A fast check of the build for 32 bit, and we have a "Intel 80386", that's the 386 architecture:
> root@XXX:/XXX/sqlite-autoconf-3440000# file sqlite3.dll
> sqlite3.dll: PE32 executable (DLL) (console) Intel 80386, for MS Windows

And for the 64 bit, "x86-64":
> root@XXX:/XXX/sqlite-autoconf-3440000# file sqlite3.dll
> sqlite3.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows

Edit:
Instructions for 32 bit:
```
apt install mingw-w64
wget https://www.sqlite.org/2023/sqlite-autoconf-3440000.tar.gz
tar xzf sqlite-autoconf-3440000.tar.gz
cd sqlite-autoconf-3440000
i686-w64-mingw32-gcc -DSQLITE_LIMIT_ATTACHED=300 -shared sqlite3.c -o sqlite3.dll
```

**Comment by Slasar41** [comment]
@Beanux Just build it myself and it's working for me too.
Do you want to create a PR?

**Comment by Slasar41** [comment]
Will be fixed in the next release.
