### ISSUE TITLE
[bug-website module] Westmanga.info (Sorry, you have been blocked)

### ISSUE THREAD

**Issue by reivatin** [dazedcat19/FMD#1335]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Win 11 22H2 64

### Describe the bug

![westmanga](https://github.com/dazedcat19/FMD2/assets/31089191/d83bfc4b-1ba8-4cb2-bef9-c120b4ea96d0)
as title suggest, i'm screening some manga and try to open the download page on westmanga.info
and after long loading, i got the title as pic above
I'm using Indihome ISP + WARP, both active or deactive the results is same..
I'm normally open the website via chrome or firefox, there is "captcha" one on first time opening the web, but after that it open normally in browser, still can't open in FMD2

funny things is, my last updated downloaded manga from the website is less than 12 hours ago,,,,

add, the check for new update page, is bold on red for westmanga, means FMD2 can't access it

**Comment by Slasar41** [comment]
Still can't access the site?
