### ISSUE TITLE
bug-website module] FMD is not grabbing past the first page of asura scans webtoon chapters

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1336]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21h1 x64

### Describe the bug

https://asuratoon.com/ on fmd is only grabbing and showing the first page on every webtoon and chapter and ignoring the rest

https://asuratoon.com/manga/2122552102-the-priest-of-corruption/
![1](https://github.com/dazedcat19/FMD2/assets/52017476/76d7abd4-9b02-4dbb-9c8e-d030be2a94aa)
![2](https://github.com/dazedcat19/FMD2/assets/52017476/5bd7c038-3fc2-4bf7-b665-f99ff2682047)

**Comment by BottomTierDev** [comment]
I don't know what the old version's like but I'm assuming they changed the code a little, in readerarea they have the cover page and only the cover page under ```<p>[image]</p>```, and the rest is outside of it. 

In MangaShiro.lua, find ```function GetPageNumber()``` and go down to the AsuraScans section.
Inside you'll find ```local v for v in x.XPath('//*[@id="readerarea"]/p/img').Get() do```
Replace that line with ```local v for v in x.XPath('//*[@id="readerarea"]/p/img|//*[@id="readerarea"]/img').Get() do```

If you're worried about making permanent changes, you can comment the line out by putting ```--``` at the start.
It seems to get all the images, including the cover but excluding the ad at the bottom. If you don't want the cover then just change the string to ```//*[@id="readerarea"]/img```

**Comment by jillybeans** [comment]
thank you appreciate you always giving fixes for asura scans :D

**Comment by BottomTierDev** [comment]
They've been simple fixes so far, I don't even know lua and I only know the basics of xpath. I'd look into pushing module updates if I knew I was doing it correctly.

**Comment by jillybeans** [comment]
title broken again from lua update after this fix, fixed it,
