### ISSUE TITLE
[bug] Transfer websites not working

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [dazedcat19/FMD#1338]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Widows 11 x64 2H22

### Describe the bug

Whenever I try to change the source to download a manga, the application doesn't detect the series as valid (it's there with the name given) or "invalid" (it's not there or not with that name), so the transfer can't happen.

### To Reproduce

1. Go to "Favorites"
2. Right click on a series
3. Choose "Transfer website"
4. Choose any website from the list

### Expected behavior

It should detect it as "valid" or "invalid", allowing for the source to be changed.

**Comment by knapah** [comment]
The website has changed its domain from westmanga.info to westmanga.org

**Comment by knapah** [comment]
Sorry for my previous reply, that was for another issue.

**Comment by l-l-l-l-l-l** [comment]
Still not working. Any news on the fix?

**Comment by Slasar41** [comment]
Nothing. The people that can fix FMD has disappear.

**Comment by Slasar41** [comment]
Fixed in the next release.
