### ISSUE TITLE
[website module request] Carteldemanhwas

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1349]
### Name

Carteldemanhwas

### Root URL

https://carteldemanhwas.com/

### Directory list URL

https://carteldemanhwas.com/series/

### Example manga info URL

https://carteldemanhwas.com/series/la-nina-cenicienta-es-la-princesa-de-la-luz/

### Example chapter URL

https://carteldemanhwas.com/la-nina-cenicienta-es-la-princesa-de-la-luz-capitulo-25/

### Language

Spanish

**Comment by Slasar41** [comment]
Added. https://github.com/dazedcat19/FMD2/commit/4c028895c6767bc2c2e82b2a12f9a542b61af3d2
