### ISSUE TITLE
[website module request] Miaucomics

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#1350]
### Name

Miaucomics

### Root URL

https://miaucomics.org/

### Directory list URL

https://miaucomics.org/manga/

### Example manga info URL

https://miaucomics.org/manga/blancanieves-es-tomado-por-la-reina/

### Example chapter URL

https://miaucomics.org/blancanieves-es-tomado-por-la-reina-capitulo-4/

### Language

Spanish

**Comment by Slasar41** [comment]
Added. https://github.com/dazedcat19/FMD2/commit/b5711fc02b735b1b5dced4900021f6324db66b6a
