### ISSUE TITLE
[bug-website module] Komiktap changed their domain and changed their template

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD#1357]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Komiktap changed their domain and changed their template

before : komiktap.in
after : komiktap.me

**Comment by Slasar41** [comment]
Domain and template has been changed but still doesn't work.
There's a notice to turn on JavaScript in FMD instead.

**Comment by enjoe842** [comment]
![image](https://github.com/dazedcat19/FMD2/assets/33560815/7a54159d-c3fb-42ca-8157-919aeca2d7cf)
It looks like you have to enable JavaScript to access it
