### ISSUE TITLE
chapmanganato.to

### ISSUE THREAD

**Issue by VijayThagriya** [dazedcat19/FMD#1358]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Window 11

### Describe the bug

it was working before the update , not working any more , cant download manga from https://chapmanganato.to/

### Log

https://chapmanganato.to was working in FMD not anymore , please can you add again

**Comment by Slasar41** [comment]
The domain has changed.

**Comment by VijayThagriya** [comment]
will be added again or not?

**Comment by Slasar41** [comment]
It's not removed but the domain just changed and I already fixed it.
