### ISSUE TITLE
[bug-website module] yugenmangas

### ISSUE THREAD

**Issue by hidalg25** [dazedcat19/FMD#1361]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

Doesn't let you download
![Captura de pantalla 2023-12-28 114540](https://github.com/dazedcat19/FMD2/assets/115298872/347e57c8-9e53-4bfe-bcdf-f7454d4dec1d)
![Captura de pantalla 2023-12-28 115114](https://github.com/dazedcat19/FMD2/assets/115298872/5dc49767-6c4b-4ab6-838f-2cae8e0db079)

### Log

https://yugenmangas.lat/home

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/a62b7049-a97e-4ad9-848a-93dd59fc5c88)

**Comment by Slasar41** [comment]
The images are broken.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/e45ae5ea-fd7f-4f75-b431-0193a4c826bf)
