### ISSUE TITLE
[website module request] 

### ISSUE THREAD

**Issue by LittleDaoist** [dazedcat19/FMD#1367]
### Name

ComicK

### Root URL

https://comick.cc/home

### Directory list URL

https://comick.cc/genres

### Example manga info URL

https://comick.cc/comic/01-reality-quest

### Example chapter URL

https://comick.cc/comic/01-reality-quest/sHQiGUyv-chapter-1-en

### Language

English

### Website relationship

Alternative domain of ComicK.app. The module for comicK.app isn't working anymore.

**Comment by Slasar41** [comment]
If it's a domain change then create bug-website module.
