### ISSUE TITLE
[bug-website module] madara.lua issues

### ISSUE THREAD

**Issue by UnnamedOtaku** [dazedcat19/FMD#1370]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7 x64

### Describe the bug

Traducciones Amistosas from madara.lua is not working. When i press the update manga list butom, it doesn't update it, actually doesn't do anything, so, when i try opening a manga, the name turns to N/A and doesn't show the chapter list. i tryed another scanlations like GodsRealmScan and PlotTwistNoFansub and it showed the same issue, but some others is working like KnightNoFansub and CopyPasteScanlation
edit:
actually, forget about CopyPasteScanlation, some mangas load fine, but others are becoming N/A. the problem is updating the manga list

**Comment by Slasar41** [comment]
- Traducciones Amistosas: will be fixed
- GodsRealmScan: changed url or dead
- PlotTwistNoFansub: no website, only app
- CopyPasteScanlation: manga list will be updated
