### ISSUE TITLE
[website module-request] 

### ISSUE THREAD

**Issue by shedman214** [dazedcat19/FMD#1383]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11

### Describe the bug

Can we add this site, please? Mangafire
https://mangafire.to/home

**Comment by Slasar41** [comment]
Still wrong. Select [Website module request](https://github.com/dazedcat19/FMD2/issues/new?assignees=&labels=&projects=&template=website-module-request.yml&title=%5Bwebsite+module+request%5D+) when requesting a new website.
