### ISSUE TITLE
[website module request] MangaFire

### ISSUE THREAD

**Issue by shedman214** [dazedcat19/FMD#1384]
### Name

Mangafire

### Root URL

https://mangafire.to/

### Directory list URL

https://mangafire.to/home

### Example manga info URL

https://mangafire.to/manga/mato-seihei-no-slave.pj5p9

### Example chapter URL

https://mangafire.to/read/mato-seihei-no-slave.pj5p9/en/chapter-1

### Language

English

**Comment by hstraten** [comment]
There is a Tachiyomi/Aniyomi/Mihon extension for MangaFire, maybe that can be used to figure out how to get the mangainfo, chapters etc.
https://github.com/keiyoushi/extensions-source/tree/main/src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire

**Comment by shedman214** [comment]
any update on adding this site?

**Comment by Slasar41** [comment]
The chapter images are scrambled. While FMD supported descrambling the images, I don't know how to do it.

**Comment by hstraten** [comment]
@Slasar41 can you share what you have so far somewhere? Maybe we can look together to find out?

**Comment by Slasar41** [comment]
@hstraten I haven't started yet. If you can help me then I'll try create it.

**Comment by hstraten** [comment]
@Slasar41 I have some programming experience but not in lua or the setup for these modules.
But I think I would be able to help.
I will read and try to understand how these modules are setup and how they work.

**Comment by Slasar41** [comment]
I've create the module and pick a random title but I don't see any images being scrambled.
Could you test with more titles?
[MangaFire.zip](https://github.com/user-attachments/files/17892371/MangaFire.zip)

**Comment by hstraten** [comment]
Tested a few titles, looked good to me, I could only get them by pasting the URL, the download list from server option didn't work for me.
I thought it was due to a missing / as prefix here: `DirectoryPagination = 'newest?page=' ` but that didn't fix it.
My knowledge on lua and XPath was (is) not good enough (yet) to troubleshoot properly.
I'll continue to fiddle around with it.

**Comment by Slasar41** [comment]
It's because I haven't done with the manga list function `GetNameAndLink()` yet. Language support and what type to read (chapter or volume) also need to be added.
You can test more titles, maybe test with the older title/chapter too. Mihon still have the descrambling image function.

**Comment by Slasar41** [comment]
You can take a look at this reference made by SDXC. It's made when there's no FMD2 yet but it's not too different.
[LuaReference.zip](https://github.com/user-attachments/files/17894096/LuaReference.zip)

**Comment by hstraten** [comment]
Ah ok makes sense, the scramble js referenced by mihon (https://mangafire.to/assets/t1/min/all.js) doesn't exist (or at least I'm unable to access it) even when mirroring (part of) the site locally I could not find a reference for it., so I think it isn't done anymore.
Tested a few oldies, seems ok. I'll just keep clicking random and let FMD do the downloading, and I'll check them manually.

Thanks for the reference file, I'll have a look there as well. Never to old to learn something new :)

**Comment by Slasar41** [comment]
I hope so. I haven't touch this request because I'm looking at the other app implementation and see the need to descramble image.
If there really no need to do that then I'll push the update after I'm done with the module.
Thanks for your help.
