### ISSUE TITLE
[bug-website module] Mangadex

### ISSUE THREAD

**Issue by muto4013** [dazedcat19/FMD#1387]
Update of the mangalist online is extreme slow takes several hours to complete with errors. 
Problem exists in FMD v2.0.31.0 and in v2.0.32.0, tested on different installations (old or fresh), different computers with different winVer, different netprovider. 
edit: the update took more the 12 hours, this seems too long.
### Log
i started FMD, went direct to "manga info", selected MangaDex and pushed "Update manga list, the result is seen in the log,
I have deleted repetitive entries and marked this with [...].  

=== Log Session Started at 17-Jan-24 16:12:59 by Free Manga Downloader ===
15:12:59:998 INFO: "Free Manga Downloader" started [PID:2692]
15:12:59:998 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.31.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 17763
               FPC Version       : 3.3.1
               LCL Version       : 2.1.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2021/03/21 14:33:22
               Path              : C:\Program Files\fmd\fmd.exe
               Process ID        : 2692
               MainThread ID     : 1072
17:06:30:150 INFO: Total Over Max Limit: 6740 are over the max limit!
17:06:35:669 INFO: Total Over Max Limit: 6740 are over the max limit!
17:06:41:225 INFO: Total Over Max Limit: 6740 are over the max limit!
[...] repetitive entries deleted
17:15:30:567 INFO: Total Over Max Limit: 6740 are over the max limit!
17:15:36:639 INFO: Total Over Max Limit: 6741 are over the max limit!
17:26:17:194 INFO: Total Over Max Limit: 2937 are over the max limit!
[...] repetitive entries deleted
17:33:35:794 INFO: Total Over Max Limit: 2937 are over the max limit!
17:33:41:298 INFO: Total Over Max Limit: 2937 are over the max limit!
17:33:46:833 INFO: Total Over Max Limit: 2937 are over the max limit!
17:34:51:906 INFO: List could not be fetched. Please check if you can access the Manga page and read the chapter in your browser.
17:35:20:789 EXCEPTION: LUA>DoGetInfo("MangaDex.lua")> LuaCallFunction("GetInfo") LUA_ERRRUN: C:\Program Files\fmd\lua\modules\MangaDex.lua:252: attempt to perform arithmetic on a nil value
17:36:41:487 EXCEPTION: LUA>DoGetInfo("MangaDex.lua")> LuaCallFunction("GetInfo") LUA_ERRRUN: C:\Program Files\fmd\lua\modules\MangaDex.lua:252: attempt to perform arithmetic on a nil value
22:20:15:774 INFO: error: Manga `342811b9-2c86-4b5e-8276-8b77913f1896` not found.
22:38:22:972 INFO: error: Manga `b92925d0-e41d-4edc-a3d9-479501fdb772` not found.
00:53:38:124 INFO: error: Manga `f82f862b-a954-4db0-9b17-885562b8f4c7` not found.
01:34:15:997 INFO: error: Manga `5755bd67-4cf1-408c-a4d2-723bdc5f088e` not found.

=== Mangadex UPDATE ended at 18-Jan-24 03:40:12  ===

**Comment by Slasar41** [comment]
It's the restriction of MangaDex API.
If it too fast then FMD would get rate limited.
I try to reduce the delay a bit in the next module update.
