### ISSUE TITLE
[bug-website module] 

### ISSUE THREAD

**Issue by chybbud** [dazedcat19/FMD#1388]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [x] This is not temporary server issue.

### System information

win 11 pro 23h2 64bit

### Describe the bug

westmanga domain update
form
https://westmanga.org/ or https://westmanga.info/
to
https://westmanga.fun/

can you update the module?

and 
https://kiryuu.id/ work on chrome but not work in FMD, is it because cloudflare's bot check?

### Log

.

**Comment by Slasar41** [comment]
For Kiryuu, the site increased their cf protection so use cloudflare workaround.
