### ISSUE TITLE
[bug-website module] hiperdex doesnt pull the chapter list, only headers

### ISSUE THREAD

**Issue by zillafox** [dazedcat19/FMD#1389]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10

### Describe the bug

trying to download from hiperdex website

i did cookies work around and usually it works as to where all the chapter list shows up
![cookies](https://github.com/dazedcat19/FMD2/assets/24423458/92d36612-44eb-4b24-bd16-cb50e5abc7cd)

but this time no matter how many times i tried to restart my browser to get the newer cookies , it just doesnt work.
headers showed up like this but no chapters being generated. and all the same to all other titles
![Capture](https://github.com/dazedcat19/FMD2/assets/24423458/657af423-e96f-4ad9-b29f-f89a3b962f0d)

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/76584078-3f26-4e11-a0ad-39438d8ecdb4)
![image](https://github.com/dazedcat19/FMD2/assets/28888646/62ba1544-645d-4782-9210-e385073a7d8d)

**Comment by zillafox** [comment]
![12](https://github.com/dazedcat19/FMD2/assets/24423458/6169a3f7-6167-4a22-882a-d2a3b8e9404e)
![222](https://github.com/dazedcat19/FMD2/assets/24423458/dee246df-b3ac-4714-aac8-2f7d66b9379c)
![33](https://github.com/dazedcat19/FMD2/assets/24423458/b1fa530b-912c-41c3-91f4-e1c5d02d4596)


Did i pull it from the wrong sources? may i know from which point that you got that cookies?

**Comment by Slasar41** [comment]
I got the cookies from here:
![image](https://github.com/dazedcat19/FMD2/assets/28888646/59bf1578-25f9-415f-b0ef-60ea120533af)
![image](https://github.com/dazedcat19/FMD2/assets/28888646/df1017e4-a73a-4a76-9629-2172a6db858d)

**Comment by zillafox** [comment]
Thanks for the reply. it seems that i also took the cookies from the same place but mine is always started from "cf_clearance xxxxxx" onwards. and i dont know if that could affect the process or not

it still doesnt work for me but my internet browser could show everything just fine

**Comment by zillafox** [comment]
it was solved but itself after a single click to modem reset. maybe it was about connection around. now it runs smoothly as it used too. thank you tho for your kind assistance

**Comment by Slasar41** [comment]
Nice you got it working now.
