### ISSUE TITLE
[bug-website module] Rizzcomic cloudfare 

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#1390]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 64-bit

### Describe the bug

I was downloading all hail the sect leader from Rizz Comic and everything was going well until a power outage happened. After the power was back, it's not working anymore. Even the manga info is not loading anymore. Did the Cloudflare workaround stop working?

![image](https://github.com/dazedcat19/FMD2/assets/24958560/1aa1c1ea-aa9a-49ad-93d8-59d975656d2b)

This thing's appearing as well.

![image](https://github.com/dazedcat19/FMD2/assets/24958560/477c2464-6018-4533-a200-6e66af38a399)

**Comment by Slasar41** [comment]
Maybe the database corrupted?
Try restoring from `backup` folder.

**Comment by Souravi785** [comment]
It's fixed.

**Comment by Souravi785** [comment]
Back again. Tried restoring from backup but not working.

**Comment by Slasar41** [comment]
What happen?

**Comment by Souravi785** [comment]
The same problem (manga info not loading) I mean. But it's fixed again by itself. I don't know what's going on.

**Comment by Slasar41** [comment]
Rizzcomic turn on and off the cf protection.
If it happen again, use cloudflare workaround.
