### ISSUE TITLE
[bug] Manganato slows down to a crawl

### ISSUE THREAD

**Issue by ghost** [dazedcat19/FMD#1393]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows Server 2022 (Win 10)

### Describe the bug

This problem was raised in 2021 by issue https://github.com/dazedcat19/FMD2/issues/643, how is this not fixed by now ?

### To Reproduce

1. Add Manganato
2. Download any Manga with it
3. Wait for some downloads
4. Now enjoy your 100kbs download speed

### Expected behavior

Full Speed the entire time, it starts with 5-10mbps and then goes down to like 100-400kbs

**Comment by ghost** [comment]
As a Example MangaSee stays at 15-50mbps the entire time.
Lets say One Piece, it took 7 minutes to download on MangaSee, while it took more then an hour on Manganato...

**Comment by Slasar41** [comment]
I don't know how to fix it, maybe someone else can.
And this issue is duplicated of https://github.com/dazedcat19/FMD2/issues/643.

**Comment by ghost** [comment]
Dont know how to fix so you just mark it as completed. Lol what the fuck ?

**Comment by Slasar41** [comment]
Duplicated.
You could just comment on the still open issue.
