### ISSUE TITLE
Nhentai workaround cookies keep getting deleted when downloading old tasks [bug-website module] 

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD#1394]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Win 10 64bit 

### Describe the bug

I tried to redownload hundreds of old hentai that i downloaded last year, I always use cookies workaround for it. but the cookies field in settings keep deleted everytime I start the tasks

![Screenshot 2024-01-26 045337](https://github.com/dazedcat19/FMD2/assets/26659986/0c98e874-3c19-4495-bf29-d5c94131419f)

**Comment by Slasar41** [comment]
Do your ISP block access to nhentai site and you have to set up a DNS?

**Comment by Plegmatis** [comment]
yes, i had to use DNS settings or use VPN, both has this problem

**Comment by Slasar41** [comment]
Try use [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) instead, run `2_any_country_dnsredir.cmd`.
I also had the same issue before discovering that method.

**Comment by Plegmatis** [comment]
it works now, thanks, i remember a year ago my disk corrupted and i had to redownload all of my manga, this problem didnt happen back then
