### ISSUE TITLE
[bug-website module] rizzcomic.com download not working

### ISSUE THREAD

**Issue by MauroAs24** [dazedcat19/FMD#1397]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Pro 22H2 x64

### Describe the bug

I can't download from Rizzcomic. The manhwa info is loading fine but the download isn't working.

![Rizzcomics 1](https://github.com/dazedcat19/FMD2/assets/56060358/580b72aa-7e4a-44a5-b6fa-b357261f3aaa)

![Rizzcomics 2](https://github.com/dazedcat19/FMD2/assets/56060358/00ad79ad-5d81-44be-949c-4de741d5bb7f)

![Rizzcomics 3](https://github.com/dazedcat19/FMD2/assets/56060358/0b2f7535-a483-4020-9092-8c77e4086a2f)

**Comment by mooglestiltzkin** [comment]
it worked before, but recently it doesn't anymore. so somethings changed.

**Comment by jpwong2** [comment]
Seems to have something to do with the referer http header when it tries to download the images.  If I put the entry for rizzcomics back into the ExMangaShiro.lua the downloads work again.

**Comment by Slasar41** [comment]
Is this still an issue?
Just tested and it's works fine.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/c6e2a1d9-3fdb-4737-b0da-08887ca9ac3a)

**Comment by jpwong2** [comment]
> Is this still an issue?

Doesn't seem like it, if you open one of the image links directly in a browser now it's not giving a cloudflare error anymore, so they've likely disabled the requirement that the referrer header list their site to access the images.

**Comment by Slasar41** [comment]
Okay, I'll just added that just in case the next time they increase the security again.
