### ISSUE TITLE
[bug-website module] mgeko (use to be MangaNeko) stopped working

### ISSUE THREAD

**Issue by xx255q** [dazedcat19/FMD#1400]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 latest

### Describe the bug

Any past bookmarks or even a lookup to a new series will have a blank search result with the title just showing N/A

**Comment by xx255q** [comment]
Example URL: https://www.mgeko.com/manga/21-century-retrogression/

**Comment by Slasar41** [comment]
Could you upload your favorites database here?
Located in userdata folder.

**Comment by xx255q** [comment]
here

**Comment by xx255q** [comment]
[favorites.zip](https://github.com/dazedcat19/FMD2/files/14173002/favorites.zip)
now try

**Comment by Slasar41** [comment]
I can't open the archive.

**Comment by xx255q** [comment]
I think you have to change the ext from zip to db

**Comment by Slasar41** [comment]
Next time add the database file to archive properly instead of just changing the extension file.

So I ran check new chapter with your favorites and it's working fine.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/d8b6dbe3-8553-4dc4-9a8b-4373f78714bc)

**Comment by xx255q** [comment]
When I submitted the ticket only that website and all favorites from that
site error/fail

**Comment by Slasar41** [comment]
Have you try it again?
