### ISSUE TITLE
[bug-website module] Mangadex

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [dazedcat19/FMD#1404]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Widows 11 x64 2H23

### Describe the bug

Since some hours ago (this morning it still worked), whenever FMD tries to connect to mangadex, ir gives an error and asks me to check my connection. It only happens with Mangadex and I can access the site normally with my browser. I've tried adding the cookies and UserAgent like it was done before for certain sites (like LHTranslations), and while it was a bit more difficult due to the current MD security concealing the cookies, I managed to do it; still no dice.

I tried checking the log, but it doesn't log any trouble: just says that the program opened correctly and that I clsed it properly afterwards. At most, when I tried to update the list just to receive some response in the log, I got this line: `INFO: List could not be fetched. Please check if you can access the Manga page and read the chapter in your browser.`

Like I said, I can access the site without issue on my browser(s).

### Log

=== Log Session Started at 07/02/2024 23:44:09 by Free Manga Downloader ===
23:44:09:379 INFO: "Free Manga Downloader" started [PID:12352]
23:44:09:384 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.32.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 22631
               FPC Version       : 3.2.2
               LCL Version       : 2.2.6.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2023/09/21 08:07:57
               Path              : C:\Free Manga Downloader\fmd.exe
               Process ID        : 12352
               MainThread ID     : 3160
23:44:40:680 INFO: List could not be fetched. Please check if you can access the Manga page and read the chapter in your browser.
23:45:23:559 INFO: TMainForm.FormClose
23:45:24:310 VALUE: NormalExit = True
23:45:24:491 INFO: "Free Manga Downloader" exit normally [PID:12352]

**Comment by SDXC** [comment]
The User-Agent FMD uses is not allowed anymore on MD. You can work around this issue by setting the UserAgent to "FreeMangaDownloader" in "Options\Websites\Advanced\MangaDex\HTTP\UserAgent"

**Comment by l-l-l-l-l-l** [comment]
Working. Thanks!

**Comment by Nitrousoxide** [comment]
> The User-Agent FMD uses is not allowed anymore on MD. You can work around this issue by setting the UserAgent to "FreeMangaDownloader" in "Options\Websites\Advanced\MangaDex\HTTP\UserAgent"

I was also experiencing this issue.  Changing the UA as described here fixed it immediately.
