### ISSUE TITLE
[bug] MangaDex source not loading

### ISSUE THREAD

**Issue by Type-Ghost** [dazedcat19/FMD#1405]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 Home 22H2 x64

### Describe the bug

MangaDex manga stopped loading today, yesterday was fine. At first, checking manga on the info panel loaded the cover, title and stuff like that, but not the chapters. 

So I updated manga list first. Took a few hours to complete, after 30 minutes I changed the max number of update and background threads from 1 to 5, then to the maximum of 32 for no more then 10 seconds, then back to 5. Once that was done, nothing had changed. I tried downloading manga list from server, and at this point I got a new error: "Cannot get manga info. Please check your internet connection and try again."

### To Reproduce

1. Open FMD2
2. Check manga info for any entry on mangadex
3. Loads improperly
4. Update manga list
5. Fiddle with max update and background threads
6. Download manga list from server
7. Get new error

### Expected behavior

Manga list gets updated, manga info goes back to normal.

### Additional context

Checking with mangadex support, turns out I got IP banned. They tell me fmd2 might be spoofing the user-agent and/or ignoring 4xx status codes. To be clear, I'm not here trying to complain about getting banned. I was told it's temporary, which is fine. What's not fine is that being possible to happen, just by updating the manga list.

Anyway, I would rather have done this through some other form of contact, an email or discord, so if this doesn't belong here, please let me know how I can reach the devs

**Comment by zillafox** [comment]
Same here , I experienced the same problem as yours. It failed to load manga info.

but i can browse the website from my web browser just fine

**Comment by Black-Dalek** [comment]
Same issue

**Comment by arbiter9605** [comment]
it worked fine at 10pm last night now i get failed to load today. Don't think its ip ban as even via vpn it doesn't work unless its being detected and banned on connect.
