### ISSUE TITLE
[bug-website module] Mangadex

### ISSUE THREAD

**Issue by GelgoogGuy** [dazedcat19/FMD#1406]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11 Build 22621

### Describe the bug

Having the same issue described in #1404 and #1405. I attempted the fix described in 1404 and was unsuccessful. I saw 1405 and downloaded the new lua, replaced, restarted FMD2 and still receiving "Cannot get manga info. Please check your internet connection and try again." 

I also downloaded and set up a clean install of FMD2 and received the same result.

*Edit, I can access the website fine via browser.

**Comment by jpwong2** [comment]
You may have been temporarily IP banned by mangadex.  Not sure if it extends every time you try to access the site or not, but it started to work for me again after I shut down the program for a few hours.

**Comment by anonimuskai** [comment]
in my case, after doing what #1404 & #1405 fix describe , the module is somehow able to access some series but  just displaying some chapter of the series

**Comment by GelgoogGuy** [comment]
> You may have been temporarily IP banned by mangadex. Not sure if it extends every time you try to access the site or not, but it started to work for me again after I shut down the program for a few hours.

I totally forgot to mention, I can access MangaDex just fine via browser.

**Comment by GelgoogGuy** [comment]
Issue seems resolved as of this morning (2/9/2024).
