### ISSUE TITLE
[website module request] Temple Scan

### ISSUE THREAD

**Issue by ElectroShade** [dazedcat19/FMD#1415]
### Name

Temple Scan

### Root URL

https://templescan.net/

### Directory list URL

https://templescan.net/comics

### Example manga info URL

https://templescan.net/comic/age-of-arrogance

### Example chapter URL

https://templescan.net/comic/age-of-arrogance/92727-chapter-1

### Language

English

**Comment by Slasar41** [comment]
Already supported.
