### ISSUE TITLE
[website module request] 

### ISSUE THREAD

**Issue by kuvoid** [dazedcat19/FMD#1420]
### Name

carteldemanhwas

### Root URL

https://carteldemanhwas.com/

### Directory list URL

https://carteldemanhwas.com/series/

### Example manga info URL

https://carteldemanhwas.com/series/el-secreto-de-la-duquesa-sapphire/

### Example chapter URL

https://carteldemanhwas.com/el-secreto-de-la-duquesa-sapphire-capitulo-0/

### Language

Spanish

### Website relationship

is used the MangaThemesia template

**Comment by Slasar41** [comment]
Added. https://github.com/dazedcat19/FMD2/commit/4c028895c6767bc2c2e82b2a12f9a542b61af3d2
