### ISSUE TITLE
[bug-website module] Can't download from H2R and Tsumino

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD#1422]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Win 10 64bit 

### Describe the bug

I can't download from Hentai2Read and Tsumino even though it works fine on browser and in-app manga info
I tried using cookie workaround it doesn't seems affect anything. because i can see the manga info fine without it.
In H2R case i only can download some of them. 

Ex. manga that i CAN download
- https://hentai2read.com/allure_x_rouge/
- https://hentai2read.com/everyday_work/

and manga that i CANNOT download
- https://hentai2read.com/muramatasans_secret/
- https://hentai2read.com/wakuwaku_oneesans/

also, some TSUMINO links example
- https://www.tsumino.com/Book/Info/41105/yorinuki-waai-land-
- https://www.tsumino.com/Book/Info/36409/prisoners-high-aru-onna-kanshu-no-antantaru-matsuro-

in app manga info
![image](https://github.com/dazedcat19/FMD2/assets/26659986/cab21dfa-740b-4291-8aa7-6a00147fc175)
![image](https://github.com/dazedcat19/FMD2/assets/26659986/782c6ebf-b762-4bb5-9c8e-821ba5603d0c)

browser
![image](https://github.com/dazedcat19/FMD2/assets/26659986/589e7796-ddef-49bc-a63b-1ad859462f02)

**Comment by Slasar41** [comment]
I can download from the link of H2R that you cannot download just fine.
I also can't download from Tsumino.
Question for Tsumino, where do you get the link that contain `/Book/Info/` in the link?

**Comment by Plegmatis** [comment]
thank you for the reply, it was old download, i lost all my files and redownloading it, probably from more than 5 years ago
