### ISSUE TITLE
[bug-website module] hiperdex can't catch up

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1429]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 22h lastest

### Describe the bug

before just changing the user agent with the same our browser this can fix (bypass cloudflare check), but now they can't

**Comment by darkflee** [comment]
solved!
my connection ISP's blocking the website.
so before, i'm using ultrasurf > FMD2 solve
n then they patch it using cloudflare
n then im still using ultrasurf > FMD2 + changing the user agent browser solve
n then they patch it
.
i try using flaresolver it's just looping never ending 
the ending : it's solve just changing my connection DNS device
so FMD2 running smoothly without third party

**Comment by darkflee** [comment]
report :
idk they had some spy or not but this got patch already so yeah the fmd can't catch up again, the other tools such as extreme picture finder cant catching up as well, even updating the newsest template for hiperdex downloader is no hope 
w3ell idk it's just me with my ISP problem or all ppl feel the sameway

**Comment by Slasar41** [comment]
It's working fine now.
![image](https://github.com/user-attachments/assets/4ff78a81-1650-43de-b5ab-0d48073a49c5)
