### ISSUE TITLE
[website module request] Gourmetsupremacy.com

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#1439]
### Name

Gourmetsupremacy

### Root URL

https://gourmetsupremacy.com/

### Directory list URL

https://gourmetsupremacy.com/project/

### Example manga info URL

https://gourmetsupremacy.com/project/time-to-change-the-genre/

### Example chapter URL

https://gourmetsupremacy.com/project/time-to-change-the-genre/chapter-90/

### Language

English

### Website relationship

This site was previously known as gourmetscans.net.

**Comment by Slasar41** [comment]
You need to install [Node.js](https://nodejs.org/en) first.
