### ISSUE TITLE
[bug-website module] Mangageko webtoon name showing as NA on all of them

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1443]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21h1 x64

### Describe the bug

https://www.mgeko.com/manga/the-first-sequence/

everying webtoon or manga is showing as NA on title. this happend today was working yesterday

![Untitled](https://github.com/dazedcat19/FMD2/assets/52017476/e247b03c-6264-4731-a116-798678f5c379)

they can still download just they all lose there titles and folders come out as NA

**Comment by hieijr** [comment]
i can confirm the bug, it also stops you from adding any new favourite from mgeko since having N/A as title is not possible and it's not possible to put a custom title to override the problem

**Comment by jillybeans** [comment]
this is my only workaround to this issue, but its the most tedious one.

![save](https://github.com/dazedcat19/FMD2/assets/52017476/fb257296-1069-4ee5-9811-e2898456c8a4)
![save2](https://github.com/dazedcat19/FMD2/assets/52017476/04edd47d-407b-47a8-9e74-a9244e6f2ade)
gotta add your own title manually in the save to, for each DL so yeah very tedious when you reading hundreds of different webtoons :p

**Comment by xx255q** [comment]
Yes very important this is fixed!
