### ISSUE TITLE
[website module request] Void-scans changed to hivescans

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#1445]
### Name

Hivescans

### Root URL

https://hivescans.com/

### Directory list URL

https://hivescans.com/projects/

### Example manga info URL

https://hivescans.com/manga/the-constellations-are-my-disciples/

### Example chapter URL

https://hivescans.com/the-constellations-are-my-disciples-chapter-60/

### Language

English

### Website relationship

voic-scans.com changed name to hivescans.com

**Comment by hesoyamma785** [comment]
you can get the series this way 
first add the voidscans from manga
.
![11](https://github.com/dazedcat19/FMD2/assets/77359705/cb9a876c-37cb-48ce-8f91-7df5197ad75c)
.
![22](https://github.com/dazedcat19/FMD2/assets/77359705/027e272f-5438-46b1-a7bd-dc065c4f0942)
then go to the manga info tab and find voidscans and do the following steps :

![33](https://github.com/dazedcat19/FMD2/assets/77359705/da21d00c-9fa4-470f-bb0e-b66eb888b5b4)
at last in search title search the manhwa you want to download and that's it
