### ISSUE TITLE
[bug-website module] Mangadex - doesn't find a particular title

### ISSUE THREAD

**Issue by Shajirr** [dazedcat19/FMD#1452]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7 SP1 Ultimate x64

### Describe the bug

This particular title:
https://mangadex.org/title/cf58401e-91ae-452f-b79a-5c83f34f6804/dark-summoner-to-dekiteiru
Cannot be found via the search bar in Manga Info tab. 
No matter which parts of the title I search, there are no results.
Tried "download manga list from the server" command, didn't help.
If I copy this link, and post it in the Info tab on the right side directly, then it gets recognized and loads up the available chapters.

**Comment by Qizmo** [comment]
I also got a bit of a problem in some manga too.
I can download manga like normal. However some of the manga have a few pages changed into the requesting to read from mangadex instead. When I follow the link to the chapters with issue, all pages are normal, but when I download it, always the same problem.
So far I have got 3 manga with this problem already.
PS. Sorry I can't remember which manga is it. If I see it again will post up here.

**Comment by Shajirr** [comment]
More titles that can't be found via FMD:
https://mangadex.org/title/db0ac526-46c9-41ea-be96-1959bc26a314/a-cool-older-lady-that-makes-me-crazy
https://mangadex.org/title/c9c0f16b-7bd3-4da6-bd58-fcb4bd10112f/onnamaou-sama-wa-yuusha-kun-o-taosenai
https://mangadex.org/title/b0ed1506-f76d-4d95-b9d2-77463be576c0/the-story-of-a-succubus-who-came-to-the-human-world

Pretty much anything copied from the "Popular New Titles" section can't be found via FMD, so its search became kinda useless

**Comment by Slasar41** [comment]
I've updated the manga list to the latest. https://github.com/dazedcat19/FMD2-DB/commit/642cd07def318dd117a964e4ff42a7ea099aa880
