### ISSUE TITLE
[bug-website module] Comick 

### ISSUE THREAD

**Issue by LittleDaoist** [dazedcat19/FMD#1453]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

![1](https://github.com/dazedcat19/FMD2/assets/48300166/5dab2f27-5d5c-4cd5-bb33-7dbdc0ece6be)
It only shows the chapters in the first page and the remaining chapters are missing https://comick.io/comic/dosanko-gyaru-is-mega-cute
![comick io_comic_dosanko-gyaru-is-mega-cute](https://github.com/dazedcat19/FMD2/assets/48300166/9b0f9801-2d0f-47e5-b2b8-2471b305aa3c)

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/7b7222dd-e854-4b01-b054-aa98e888eb2b)
