### ISSUE TITLE
[bug] Can't Transfer Manga to Another Website in Favorite

### ISSUE THREAD

**Issue by 6io** [dazedcat19/FMD#1454]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 11 Pro 23H2

### Describe the bug

Can't Transfer Manga to Another Website in Favorite

### To Reproduce

1. Go to Favorite
2. select manga 
3. klik right mouse 
4. select tranfer website
5. select website you want transfer

### Expected behavior

there was 
![1](https://github.com/dazedcat19/FMD2/assets/48039722/8c38f8fb-35b5-4be7-abd6-a47470adc667)
 if manga is find in transfer website
there was 
![2](https://github.com/dazedcat19/FMD2/assets/48039722/ce26d603-a592-4440-a77f-e08e3b71845f)
 if manga is not find in transfer website

### Screenshots

![3](https://github.com/dazedcat19/FMD2/assets/48039722/a7f395f8-f243-44ba-8d3e-59068df60bbf)

**Comment by ghost** [comment]
Can confirm, moving Favorites does not work

**Comment by Slasar41** [comment]
Fixed in the next release.
