### ISSUE TITLE
[bug-website module] reset-scans.us changed to reset-scans.xyz

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#1465]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 64-bit

### Describe the bug

I haven't used reset-scans for a while, so I didn't notice they changed their domain name and so it's not working on FMD.

**Comment by Slasar41** [comment]
Looks like the site has been closed.

**Comment by jpwong2** [comment]
If it's reset scans, I believe their new web site is now at https://reset-scans.co
