### ISSUE TITLE
[bug-website module] tumangaonline

### ISSUE THREAD

**Issue by hidalg25** [dazedcat19/FMD#1467]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

They cannot be viewed or downloaded.
![t](https://github.com/dazedcat19/FMD2/assets/115298872/ae301a90-0ad8-424a-b3f0-fa9c69258224)

**Comment by Slasar41** [comment]
Duplicate of https://github.com/dazedcat19/FMD2/issues/522
