### ISSUE TITLE
[bug-website module] mangaplus.shueisha.co.jp

### ISSUE THREAD

**Issue by JayAyyBee** [dazedcat19/FMD#1472]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

Manga Info is unable to populate the chapter list.

**Comment by Geese1** [comment]
Can confirm I'm having the same issue. Hopefully it's an easy fix.

**Comment by Type-Ghost** [comment]
Same here, not working for a few days now

**Comment by MrTyton** [comment]
+1. Is there a way to grab logs and see what's going on?

**Comment by fuzzfactory0** [comment]
Same problem, FMD is unable to connect to MangaPlus.
I identified the issue being that the CDN API version changed: FMD is hitting https://jumpg-webapi.tokyo-cdn.com/api/title_detail to get the manga info, but the website hits https://jumpg-webapi.tokyo-cdn.com/api/title_detailV3. The old URL just returns a 404.

The data format seems to have changed too. `firstChapterList` and `lastChapterList` aren't coming in the response anymore when hitting the new endpoint.

**Comment by fuzzfactory0** [comment]
Raised https://github.com/dazedcat19/FMD2/pull/1475 to address the changes in the MangaPlus API.
