### ISSUE TITLE
[bug-website module] Mangadex unable to pull any chapters

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD#1477]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Unable to pull any chapter information from mangadex ongoing for a week now not fixed.  Log is totally blank for trying to pull chapter from mangadex like log is not created though it's enabled.  Seems it now requires a login for it and the log is not even working at all as you can see that is all that is showing in log below. 

![image](https://github.com/dazedcat19/FMD2/assets/16074561/d2e579cf-259d-4e10-bc2b-38a43672318c)

### Log

=== Log Session Started at 6/4/2024 13:52:50 by Free Manga Downloader ===
13:52:50:542 INFO: "Free Manga Downloader" started [PID:108064]
13:52:50:542 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.32.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 19044
               FPC Version       : 3.2.2
               LCL Version       : 2.2.6.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2023/09/21 08:07:57
               Path              : C:\DOS\fmd 2.0\fmd.exe
               Process ID        : 108064
               MainThread ID     : 115976
13:53:14:774 INFO: TMainForm.FormClose
13:53:14:798 VALUE: NormalExit = True
13:53:14:857 INFO: "Free Manga Downloader" exit normally [PID:108064]
=== Log Session Started at 6/4/2024 13:53:19 by Free Manga Downloader ===
13:53:19:038 INFO: "Free Manga Downloader" started [PID:19464]
13:53:19:038 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.32.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 19044
               FPC Version       : 3.2.2
               LCL Version       : 2.2.6.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2023/09/21 08:07:57
               Path              : C:\DOS\fmd 2.0\fmd.exe
               Process ID        : 19464
               MainThread ID     : 26044

**Comment by Slasar41** [comment]
Check MangaDex language settings. https://github.com/dazedcat19/FMD2/issues/1474#issuecomment-2144854884
