### ISSUE TITLE
[bug-website module] samuraiscan

### ISSUE THREAD

**Issue by Jacobo-Estanol-Hernandez** [dazedcat19/FMD#1481]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 22H2 ultima actualizacion

### Describe the bug

El administrador de samuraiscan  a mudado otra vez la pagina de servidor y los nuevos links no estan soportados por FMD 
los links originales eran https://samuraiscan.org
pero los nuevos son https://spanish.visorsmr.com/
espero se pueda  corregir esto de antemano muchas gracias por mantener funcionando FMD me encanta el programa

### Log

![image](https://github.com/dazedcat19/FMD2/assets/25963845/bc7a3784-6cbe-4fed-97a2-e2f9fb46ffb8)

**Comment by Slasar41** [comment]
I'll fix it later.
Could you help me mark the spanish sites in `\lua\Madara.lua` which one is still working, dead, or has changed url?
I'm in the middle of moving all madara sites to its own module file and use a template.

**Comment by Jacobo-Estanol-Hernandez** [comment]
yo no se programar, pero te digo cuales ya no funcionan
YA NO FUNCIONA:

DarkskyProjects
GodsRealmScan
GrafiManga
hatsukimanga
LazyBoysScan
LeerManhua
MangaDoor
MangaHispano
MangAs
Nightow
SDLGFansub
Sksubs
TrueColorsScan
XAnimeSeduccion
ZManga

SIGUEN FUNCIONANDO
HerenScan
InManga
MenudoFansub
NiAddES: no carga las portadas
NineMangaES: tiene fallas de carga muchos titulos ya no estan disponibles y no actualiza lista
NoraNoFansub: no carga las portadas
PatyScans
PCNet
SeinagiAdultoFansub
SeinagiFansub
TopComicPorno
TuMangaOnline: funciona parcialmente mangas nuevos tienen nuevo url https://visortmo.com/
VerComicsPorno: solo muestra contenido en ingles
VerMangasPorno

CAMBIO DE URL         NUEVA URL

HitomiLa                     https://hitomi.la/index-spanish.html
knightnoscanlation     https://lectorkns.com/
KuManga                    https://www.kumanga.com/
LeviatanScans             https://manhuaus.com/leviatanscans/
lolivault                       https://lector.lolivault.net/
LectorManga              https://lectormanga.lat/
CopyPasteScanlation  https://www.cpscan.xyz/
SamuraiScan               https://spanish.visorsmr.com/
Mangasubes               https://mangasubes.wixsite.com/mangasubes/biblioteca
LeerManga                  https://leermanga.net/biblioteca
MundoWuxia              http://www.reinowuxia.com/p/todas-las-novelas.html
NeoProjectScan          https://visortmo.com/groups/145/neoproject-scanlation
PhoenixFansub            https://visortmo.com/groups/21845/phoenix-fansub
PlotTwistNoFansub     https://www.plotfansub.com/
Pzykosis666HFansub  https://lector.pzykosis666hfansub.com/
RagnarokScan             https://ragnarokscanlation.net/manga/
RavensScans                https://ravenscans.com/
SolitarioNoFansub       https://visortmo.com/groups/942/solitario-no-fansub
TvYManga                    https://tvymanga3.com/


espero que con esto te puedas ayudar a mantener FMD funcionando

**Comment by Jacobo-Estanol-Hernandez** [comment]
> Lo arreglaré más tarde. ¿Podrías ayudarme a marcar los sitios españoles en `\lua\Madara.lua`los que alguno sigue funcionando, muerto o ha cambiado de URL? Estoy moviendo todos los sitios de Madara a su propio archivo de módulo y usando una plantilla.

yo no se programar, pero te digo cuales ya no funcionan

YA NO FUNCIONA: pagina web borrada

DarkskyProjects
GodsRealmScan
GrafiManga
hatsukimanga
LazyBoysScan
LeerManhua
MangaDoor
MangaHispano
MangAs
Nightow
SDLGFansub
Sksubs
TrueColorsScan
XAnimeSeduccion
ZManga

SIGUEN FUNCIONANDO
HerenScan
InManga
MenudoFansub
NiAddES: no carga las portadas
NineMangaES: tiene fallas de carga muchos títulos ya no están disponibles y no actualiza lista
NoraNoFansub: no carga las portadas
PatyScans
PCNet
SeinagiAdultoFansub
SeinagiFansub
TopComicPorno
TuMangaOnline: funciona parcialmente mangas nuevos tienen nueva url [https:/ /visortmo.com/](https://visortmo.com/)
VerComicsPorno: solo muestra contenido en inglés
VerMangasPorno

CAMBIO DE URL NUEVA URL

HitomiLa https://hitomi.la/index-spanish.html
Knightnoscanlation https://lectorkns.com/
KuManga https://www.kumanga.com/
LeviatanScans https://manhuaus.com/leviatanscans/
lolivault [https:// lector.lolivault.net/](https://lector.lolivault.net/)
LectorManga https://lectormanga.lat/
CopyPasteScanlation https://www.cpscan.xyz/
SamuraiScan https://spanish.visorsmr.com/
Mangasubes [https://mangasubes.wixsite.com/mangasubes/ biblioteca](https://mangasubes.wixsite.com/mangasubes/biblioteca)
LeerManga https://leermanga.net/biblioteca
MundoWuxia http://www.reinowuxia.com/p/todas-las-novelas.html
NeoProjectScan https://visortmo.com/groups/145/neoproject-scanlation
PhoenixFansub [https: //visortmo.com/groups/21845/phoenix-fansub](https://visortmo.com/groups/21845/phoenix-fansub)
PlotTwistNoFansub https://www.plotfansub.com/
Pzykosis666HFansub https://lector.pzykosis666hfansub.com/
RagnarokScan https://ragnarokscanlation.net/manga/
RavensScans [https:/ /ravenscans.com/](https://ravenscans.com/)
SolitarioNoFansub https://visortmo.com/groups/942/solitario-no-fansub
TvYManga https://tvymanga3.com/

Espero que con esto te puedas ayudar a mantener FMD funcionando

**Comment by Slasar41** [comment]
Thanks for the list.
I'll make an update later.
