### ISSUE TITLE
[bug-website module] Mangaworld

### ISSUE THREAD

**Issue by stluc** [dazedcat19/FMD#1483]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11

### Describe the bug

Mangaworld list cannot be found on server and an update only returns broken or empty mangas (and just 75 entries).
The root address is .in in the LUA module. Currently it should be .ac, but also changing it does not solve the problem.
I think the issue lies in the pagination, only first page gets properly downloaded.

![image](https://github.com/dazedcat19/FMD2/assets/38380407/5f93d5c8-18a3-481c-ba68-c990013ae058)

**Comment by bubez81** [comment]
Same problem here!
