### ISSUE TITLE
[bug-website module] doujindesu.tv - The download is always wrong

### ISSUE THREAD

**Issue by enjoe842** [dazedcat19/FMD#1485]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Whatever title I download on this website (doujindesu.tv).

The download result from FMD always downloads 1 chapter from 1 manhwa title, namely:
Series: A World That I Rule (doujindesu.tv/manga/a-world-that-i-rule/)
Chapter: 36 (doujindesu.tv/2020/08/15/a-world-that-i-rule-chapter-36)

Maybe my explanation is difficult to understand, but you will know after trying it yourself.

Please fix it
Thanks and keep up the good work!

**Comment by enjoe842** [comment]
@Slasar41

**Comment by Slasar41** [comment]
Yeah I know. I just don't know how to fix it.
