### ISSUE TITLE
[bug-website module] bato.to downloads are empty or fail

### ISSUE THREAD

**Issue by quixotic120** [dazedcat19/FMD#1487]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

docker VNC image running on unraid

### Describe the bug

when downloading a chapter it fails. it creates a folder structure that looks correct (e.g. folders for each chapter with correct name) but images never download and cbz files are never created. 

happens with every series i've tried 

app version 2.0.23.0 revision 5625
not sure how to check module version but last updated 6/12/2024 (reinstalled the docker 2 days ago and updated modules)

i don't believe it's a temporary server issue because I am able to still rip the chapters with hakuneko

### Log

<img width="1039" alt="Screenshot 2024-06-14 at 5 31 05 PM" src="https://github.com/dazedcat19/FMD2/assets/16725261/b0ccddd8-76f8-448e-b3b7-72127d928f60">
example of one page source that didnt work:
https://bato.to/chapter/1268500 (page source was too long for pasting, hope thats okay)

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/76609e1f-c10f-4eb2-ae3c-2d8f12e86e83)

**Comment by quixotic120** [comment]
<img width="1076" alt="Screenshot 2024-06-18 at 3 03 09 PM" src="https://github.com/dazedcat19/FMD2/assets/16725261/6f3a03d9-fdd2-4249-8150-9ab7bdc5ce8f">
it must be an issue with the docker/vnc then bc it's still failing on my end. some more logs from attempting more chapters and the same hxh chapter just in case that helps. for what its worth other modules are working fine, only bato seems to have this issue although to be fair I have not tested them all of course

**Comment by Slasar41** [comment]
Open `lua\modules\Batoto.lua` and put `HTTP.Document.SaveToFile("batoto.html")` to line 81 and then try to download a chapter.
There should be `batoto.html` in FMD root folder, upload it here.

**Comment by quixotic120** [comment]
added this but it won't write the file. log says access denied. unsure why, permissions should be okay but apparently I am incorrect there. and I apologize - apparently this is a known issue for the docker image for some time https://github.com/Banh-Canh/docker-FMD2/issues/10 . the lua is clearly fine and the problem is with that setup

**Comment by impishlucy** [comment]
@quixotic120 if youre still using docker-fmd and are still getting that error please, try out my alpine fork, then drop me a issue on my fork if you still get it, i can try to get behind it and try to fix the permission issue.
