### ISSUE TITLE
[website module request] kanzenin.info

### ISSUE THREAD

**Issue by wow2134** [dazedcat19/FMD#1492]
### Name

kanzenin

### Root URL

kanzenin.info

### Directory list URL

https://kanzenin.info/a-z-list/

### Example manga info URL

https://kanzenin.info/manga/a-personal-vendetta/

### Example chapter URL

https://kanzenin.info/a-personal-vendetta-chapter-14/

### Language

Indonesian

### Website relationship

http://komiktap.me/
https://mangasusuku.xyz/

### Additional details

hello..
sirr.. i think you can remove some website from you'r list
like:
ManhwaTaro
KomikMama
KoMBatch
KomikSave
Manhwaid

Because they are no longer operational. I checked their fan page and they have not been active for a long time, and their website cannot be accessed. Instead, could you please add kanzenin.info

**Comment by wow2134** [comment]
thankyou

**Comment by youlanchris-collab** [comment]
waw

**Comment by youlanchris-collab** [comment]
waw

**Comment by youlanchris-collab** [comment]
waw
