### ISSUE TITLE
[website module request] Mangabuddy

### ISSUE THREAD

**Issue by Aviean** [dazedcat19/FMD#1497]
### Name

MangaBuddy

### Root URL

https://mangabuddy.com

### Directory list URL

https://mangabuddy.com/az-list

### Example manga info URL

https://mangabuddy.com/the-ten-great-emperors-at-the-beginning-are-all-my-apprentices

### Example chapter URL

https://mangabuddy.com/the-ten-great-emperors-at-the-beginning-are-all-my-apprentices/chapter-1

### Language

English

**Comment by Slasar41** [comment]
Duplicate of https://github.com/dazedcat19/FMD2/issues/896
