### ISSUE TITLE
[bug-website module] ManyToonCom manga does not loaded and workaround does not work

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD#1499]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Win 10 64bit 

### Describe the bug

I have a problem with downloading from manytoon recently, it seems I cant load the chapters like usual. It does not happen like 1-2 week ago. I can access Manytoon.com normally. like this for example
https://manytoon.com/comic/the-female-professor-and-the-nude-artist/
but the when I tried to open it in FMD i got this
![image](https://github.com/dazedcat19/FMD2/assets/26659986/813b1ea3-fac0-4861-b89c-3c97ebbc222a)
I tried the cookie workaround but it doesnt work either

**Comment by Plegmatis** [comment]
it works now but well, its not really broken bug but its kinda bothers me. when i first add the manhwa to be downloaded the task name became like this 
![image](https://github.com/dazedcat19/FMD2/assets/26659986/6f22b6ac-933b-43e6-8275-0f93c4a6f023)
there is a "NEW" added on every manhwa that i download (probably it was marked new on the site) so it changed the folder names too

**Comment by Slasar41** [comment]
Please create a new issue for that.
