### ISSUE TITLE
[bug-website module] NicoManga.com missing or invisible chapters

### ISSUE THREAD

**Issue by TienVer** [dazedcat19/FMD#1500]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Version 22H2 (OS Build 19045.4529) 64-bit

### Describe the bug

I have been very delighted to see that NicoManga is now supported by FMD2 and I have thus spent the last couple of days batch-downloading the series I've been missing out on since the site switched its domain from WeLoveManga.one to NicoManga.com.

_However_, I've noticed that for certain series, not all chapters are shown in the series' page.

Take for example (there are others, but this one showed up today, so I'm using it):
_https://nicomanga.com/manga-kamigakushi-no-rakuen.html_

Inputting that link into the Manga Info's URL tab will only show two chapters (ch.1 and ch.7), but if you switch to a normal browser and follow the link, you'll actually be greeted by _twenty-three_ chapters (maybe 24, I didn't double-check). There's something like twenty of them that FMD2 isn't displaying. The latest chapter to date (dropped in today) is ch.13.1.

Another example: _https://nicomanga.com/manga-kamigami-no-kago-de-seisan-kakumei-raw.html_
7 chapters visible on FMD2, more than 24 on Internet browser.

I have everything up to date _and_ I have also implemented the cookie trick in the NicoManga settings (or else the download function itself doesn't work properly):
_Cookies (actual values withheld)_: userId=(u); userName=(v); PHPSESSID=(w); hash=(x); ct_anti_ddos_key=(y); _GPSLSC=(z)
_UserAgent:_ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
_Enabled:_ True

Could you please find out what's happening and why there are chapters slipping through the cracks? Thanks and keep up the good work!

**Comment by TienVer** [comment]
Just a small heads-up: the website is presenting some quirky behavior that may puzzle a few visitors.

Do NOT click on the links I posted above - if you do, the website will hide all chapters and leave you with a small message ("Access denied from the Nicomanga.com domain") at the bottom of the page.

_Instead_, **copy and paste** the URLs into your browser's address bar: that will cause the series page to properly display the chapter links.

**Comment by Slasar41** [comment]
I still don't know how to fix it but I know what the cause. Somehow FMD wont show a chapter with a decimal number on the URL.
Example chapter URL: `https://nicomanga.com/read-kamigakushi-no-rakuen-chapter-2.1.html`.
If I create a code that remove the decimal number like: `:gsub('.1', '')`, then the chapter will show up.
![image](https://github.com/dazedcat19/FMD2/assets/28888646/dcf7e393-6785-49fe-9408-ffb3a75e89ae)
This is the first time I encounter this bug. Other sites with a decimal number on the URL is working fine, but not on NicoManga.
This will remain not fixed until someone else fix it.

**Comment by TienVer** [comment]
That'll be a bit problematic, given that a good portion of the series on that website use multi-part chapters with decimals (I even saw a couple of them going to "chapter x.6" and "chapter x.7" and even further than that). Nicomanga does offer a manual direct download option for each chapter, but TBH I greatly prefer FMD's more convenient automation.

Well, at least the cause of the issue is known - didn't piece it together myself. Thanks.
