### ISSUE TITLE
[bug-website module] Asura Scanlations Domain Changed

### ISSUE THREAD

**Issue by isamudysan** [dazedcat19/FMD#1512]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2

### Describe the bug

FMD2 unable to retrieve titles due to change in domain and sub-domain changes, e.g, https://asuracomic.net/series/absolute-necromancer-895344fd.

secondly, is there a tutorial on how create or update the module(s) on our own?

thank you.

### Log

Unhandled exception!
Application       : Free Manga Downloader
Version           : 2.0.32.0
Product Version   : Win64
Host Machine      : Windows 10 64-bit Build 19045
FPC Version       : 3.2.2
LCL Version       : 2.2.6.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2023/09/21 08:07:57
Path              : C:\program files (x86)\fmd2\fmd.exe
Process ID        : 11732
MainThread ID     : 22628
Thread ID         : 22628
Time              : 04/07/2024 01:41:52.221
Exception Object  : 000000000A00D760
Exception Class   : EAccessViolation
Message           : Access violation

Unhandled exception!
Application       : Free Manga Downloader
Version           : 2.0.32.0
Product Version   : Win64
Host Machine      : Windows 10 64-bit Build 19045
FPC Version       : 3.2.2
LCL Version       : 2.2.6.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2023/09/21 08:07:57
Path              : C:\program files (x86)\fmd2\fmd.exe
Process ID        : 5772
MainThread ID     : 5336
Thread ID         : 5336
Time              : 21/07/2024 00:06:39.981
Exception Object  : 00000000016A8DC0
Exception Class   : EAccessViolation
Message           : Access violation

**Comment by Slasar41** [comment]
What's the different from https://asuratoon.com?
FMD can still access it just fine.

I got no tutorial when started.
I just looking at the `\lua\modules\*.lua` files and familiarize myself.
There's also [LuaReference.zip](https://github.com/user-attachments/files/16351640/LuaReference.zip) made by SDXC to look for reference.

**Comment by jillybeans** [comment]
i don't know if its a domain change but it doesn't grab the info or chapters even with https://asuracomic.net/ in the lua. doesn't work with the cookie work around either.

https://asuracomic.net/series/martial-god-regressed-to-level-2-d75ad672

![New Bitmap Image](https://github.com/user-attachments/assets/b6b9bb4e-0f4b-4b54-81c6-83d2037fdea4)

**Comment by isamudysan** [comment]
> What's the different from https://asuratoon.com? FMD can still access it just fine.
> 
> I got no tutorial when started. I just looking at the `\lua\modules\*.lua` files and familiarize myself. There's also [LuaReference.zip](https://github.com/user-attachments/files/16351640/LuaReference.zip) made by SDXC to look for reference.

i'm using fmd2.  the screenshot below shows that there are no "current" chapters from asura scans.

![fmd2](https://github.com/user-attachments/assets/db173418-a916-4c6f-8e48-ab5de9c39901)

**Comment by jpwong2** [comment]
Looking at Asura's web page source, I think the problem is they've changed their web site template so the module can't find any of the data anymore.  This is not something just changing the URL in the lua file is going to fix.

**Comment by Slasar41** [comment]
Please upload favorites database here.

**Comment by Slasar41** [comment]
The series link is different, old: `/manga/1908287720-logging-10000-years-into-the-future` new: `/series/logging-10000-years-into-the-future-da6ea458`, so you must re-add your favorites.

**Comment by isamudysan** [comment]
thank you all.  appreciate your assistance.
