### ISSUE TITLE
[bug-website module] ReaperScans new layout lua stopped working

### ISSUE THREAD

**Issue by jpwong2** [dazedcat19/FMD#1525]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

ReaperScans released a new version of their web site and it's broken the module for their site.

Tried to check the html code behind, but seems like the new site is calling the chapter list on demand somehow (though javascript?), so I'm not sure if the lua can be updated to handle their new layout.  The actual chapters appear to have all the img tags in the html code behind though, although that's changed as well (see below for the relevant html code)

https://reaperscans.com/series/arcane-sniper
https://reaperscans.com/series/arcane-sniper/chapter-153

`<div class="flex flex-col justify-center items-center"><img class src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/000 ars copia.jpg" data-src /><img class src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/01.jpg" data-src /></div><div class="flex flex-col justify-center items-center"><img class src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/02.jpg" data-src /><img class src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/03.jpg" data-src /></div><div class="flex flex-col justify-center items-center"><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/04.jpg" /><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/05.jpg" /></div><div class="flex flex-col justify-center items-center"><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/06.jpg" /><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/07.jpg" /></div><div class="flex flex-col justify-center items-center"><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/08.jpg" /><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/09.jpg" /></div><div class="flex flex-col justify-center items-center"><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/10.jpg" /><img class="lazy" src data-src="https://media.reaperscans.com/file/4SRBHm//comics/ba81b4c2-9c66-4943-8b77-f1c9f503384e/chapters/74ae1da1-51ab-47ac-a884-6749cd4d504a/999.jpg" /></div>`

**Comment by Slasar41** [comment]
You need to re-add your favorites.
