### ISSUE TITLE
[bug-website module] asura scans again not downloading chapter

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1536]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21h1 x64

### Describe the bug

asura scans grabs the info and you can set the download. but when actually download it doesn't grab anything

https://asuracomic.net/series/player-who-returned-10000-years-later-88bd4b5a

![1](https://github.com/user-attachments/assets/1a8aee3d-0a21-4622-a661-674f4803da04)

**Comment by Qizmo** [comment]
Same problem ^^
