### ISSUE TITLE
[bug-website module] drake scans changed site

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1543]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21h1 x64

### Describe the bug

was drake-scans before. even when changing the RootURL  to the new one it still doesn't grab the info.

https://drakecomic.com/

https://drakecomic.com/manga/my-disciples-are-all-big-villains/

**Comment by Slasar41** [comment]
Just changed the URL and it's works fine.
![image](https://github.com/user-attachments/assets/887903a1-5926-476e-87fe-c128d9af4343)
