### ISSUE TITLE
[bug] MangaGeko/mgeko.cc No longer works

### ISSUE THREAD

**Issue by xx255q** [dazedcat19/FMD#1547]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 latest

### Describe the bug

Link to website/series is broken. Does not matter if it is a favorite from before or new url it no longer loads.

### To Reproduce

Try to go to any link it watch it fail to load

### Expected behavior

You see chapters, poster, details

### Screenshots

![image](https://github.com/user-attachments/assets/47be0d01-90d7-47cc-8548-1274fd21d75e)

**Comment by Slasar41** [comment]
Do cookies workaround.
![image](https://github.com/user-attachments/assets/a66c93d1-0c95-4d3d-87d8-de8183a69ecc)

**Comment by xx255q** [comment]
what is cookie workaround?

**Comment by Slasar41** [comment]
This one: https://github.com/dazedcat19/FMD2/issues/1329
If you want to do it manually: https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964
