### ISSUE TITLE
[bug-website module] asurascans.lua chapter numbers missing

### ISSUE THREAD

**Issue by inheritno** [dazedcat19/FMD#1562]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

win 11

### Describe the bug

![asurag](https://github.com/user-attachments/assets/6cdfd414-9073-4da5-88e3-a0b131151e6e)

**Comment by jpwong2** [comment]
How odd, I'm on Win10 and the numbers are showing up fine with the most up to date lua module.

**Comment by Slasar41** [comment]
It's working on my end.
Try deleting `AsuraScans.lua` so FMD will re-download it.
