### ISSUE TITLE
[bug] Thank you Slasar41

### ISSUE THREAD

**Issue by xx255q** [dazedcat19/FMD#1583]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows

### Describe the bug

I just wanted to say thank you for all the work you have been doing lately. I may only use one site but with your support you have fixed that and added many others to this program lately which is great!

Glad to have your support

### To Reproduce

Apples

### Expected behavior

A dev abandon the GitHub project

**Comment by Slasar41** [comment]
Thank you for your appreciation message. I have a bit free time right now and I just do what I can do about those open issue.
I'll close this.
