### ISSUE TITLE
[bug-website module] Hiperdex not working

### ISSUE THREAD

**Issue by TheJvict** [dazedcat19/FMD#1584]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Hiperdex links are not being recognized. It used to work after manually changing the module's .top to .com, but it stopped working. Here's what it looks like when I try to load a link:
![image](https://github.com/user-attachments/assets/0860bc1d-a311-4b22-add4-bf673318abd8)

**Comment by Slasar41** [comment]
Do cloudflare workaround.
![image](https://github.com/user-attachments/assets/ab45d97c-9394-4039-b0ef-d9f206438eee)
