### ISSUE TITLE
[bug-website module] SetsuScans; only imaizumi series change domain

### ISSUE THREAD

**Issue by user1705** [dazedcat19/FMD#1587]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Win 10 22H2 x64

### Describe the bug

SetsuScans domain still the same. Only imaizumi series has been moved to new domain. If open with browser it will redirect to new domain.

[Series Link](https://setsuscans.com/manga/imaizumins-house-is-a-place-for-gals-to-gather/)
![image](https://github.com/user-attachments/assets/d8c19534-a98f-444d-98b3-3b8b4ac72ca3)

[Redirect Link](https://kurumizaka.online/)
![image](https://github.com/user-attachments/assets/ac47aa7f-a30f-46bc-84be-53dd696f2a2d)

**Comment by Slasar41** [comment]
Because the series URL is just like that, to workaround you need add `imaizumi` to the URL.
So it'll be like this: `https://kurumizaka.online/imaizumi`

**Comment by user1705** [comment]
> Because the series URL is just like that, to workaround you need add `imaizumi` to the URL. So it'll be like this: `https://kurumizaka.online/imaizumi`

ok now the URL works fine but the images downloaded in wrong order. the website is using single digit as image filenames (as I open the image in new tab and i noticed it) so the ordering in dowloaded chapters is wrong.

website page 2
![image](https://github.com/user-attachments/assets/c636908d-d24d-4ea7-8bd0-311ff3c0abb9)

downloaded page 2 is at page 12
![image](https://github.com/user-attachments/assets/f9c23d38-768e-43d5-8f18-1f22f00d3e18)


P/S: do i need to open new issue? or i can just follow up in this thread?
