### ISSUE TITLE
[website module request] mangabuddy.com

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1633]
### Name

mangabuddy.com

### Root URL

https://mangabuddy.com/home

### Directory list URL

https://mangabuddy.com/manga-list

### Example manga info URL

https://mangabuddy.com/grand-blue

### Example chapter URL

https://mangabuddy.com/grand-blue/chapter-96

### Language

English

### Scanlation

No

**Comment by Slasar41** [comment]
Duplicate of https://github.com/dazedcat19/FMD2/issues/896
