### ISSUE TITLE
[bug-website module] hentai2read.com

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1634]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 11 64bit lastest build update

### Describe the bug

it's maybe a feature from this website.
sometimes there's some manga who can open (get to see the chapters) when you're login to your account on this web.
for example :
https://hentai2read.com/my_dear_sister_is_mine/
this can be see the chapters without login
so on fmd who are not login account the chapters can't be capture
.
maybe fmd team can adding login account on this website

**Comment by Slasar41** [comment]
I can't add login account support but there's a way to show the chapter by doing cookies workaround.

**Comment by darkflee** [comment]
oh okay ty it's helpfull

**Comment by Slasar41** [comment]
Alright I've been testing and seems to be able to add account support.
