### ISSUE TITLE
[bug-website module] crotpedia

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1671]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 11 64bit lastest build update

### Describe the bug

somehow some of their manga can't be capture by fmd n becomes unknown.
it's not because the block(filter) ip/proxy from isp because using other vpn/proxy still the same unknown catch
.
trying input the useragent n cookies still the same
.
for example this one :
https://crotpedia.net/baca/series/onee-chan-no-shiawase-amayakashi-keikaku/
.
btw they had free guest account login

**Comment by Slasar41** [comment]
Works fine after logged in.
I'll fix the login support.
![image](https://github.com/user-attachments/assets/80d29ee2-80fa-4438-a725-b61db7ea97c8)
