### ISSUE TITLE
[bug-website module] mangahub.io, mangafox.fun, mangakalot.fun, mangareader.site, mangahere.onl - all having issues

### ISSUE THREAD

**Issue by SauceyNuggets420** [dazedcat19/FMD#1675]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11 23H2 x64

### Describe the bug

Basically https://mangahub.io, https://mangareader.site, https://mangafox.fun, https://mangakakalot.fun, and https://mangahere.onl are all not working as expected. The app can fetch the title, author, artist, genres and status, but the chapters section is never populated
![mangahub](https://github.com/user-attachments/assets/2778516a-1734-42d0-ab8f-48323dbbe23a)

**Comment by SauceyNuggets420** [comment]
Not very good with lua, but I did manage to add a few changes to get the chapters and their names to show inside the chapter tab, now they just fail to download. 
I had to update the getinfo() function:
```
function getinfo()
    MANGAINFO.URL = MaybeFillHost(MODULE.RootURL, URL)

    if HTTP.GET(MANGAINFO.URL) then
        local x = CreateTXQuery(HTTP.Document)

        -- Extract manga details
        MANGAINFO.Title     = x.XPathString('//div[@id="mangadetail"]//h1/text()')
        MANGAINFO.CoverLink = x.XPathString('//div[@id="mangadetail"]//img/@src')
        MANGAINFO.Authors   = x.XPathString('//div[@id="mangadetail"]//div/span[contains(., "Author")]/following-sibling::span')
        MANGAINFO.Artists   = x.XPathString('//div[@id="mangadetail"]//div/span[contains(., "Artist")]/following-sibling::span')
        MANGAINFO.Genres    = x.XPathStringAll('//div[@id="mangadetail"]//div/p/a')
        MANGAINFO.Status    = MangaInfoStatusIfPos(x.XPathString('//div[@id="mangadetail"]//div/span[contains(., "Status")]/following-sibling::span'))
        MANGAINFO.Summary   = x.XPathString('//meta[@name="description"]/@content')

        -- Extract chapter information from all chapter groups
        local groups = x.XPathCount('//div[starts-with(@id, "chapters-tab-pane-")]')
        for i = 1, groups do
            local v for v in x.XPath('//div[@id="chapters-tab-pane-' .. i .. '"]//ul[contains(@class, "MWqeC")]/li//a[@class="_3pfyN"]').Get() do
                local chapterLink = v.GetAttribute('href')
                local chapterName = x.XPathString('.//span[@class="_2IG5P"]', v)
                log_debug(chapterLink)
                log_debug(chapterName)
                MANGAINFO.ChapterLinks.Add(chapterLink)
                MANGAINFO.ChapterNames.Add(chapterName)

            end
        end
        
        MANGAINFO.ChapterLinks.Reverse()
        MANGAINFO.ChapterNames.Reverse()
        
        return no_error
    else
        return net_problem
    end
end
```
Im way out of my element but I figured this might be a useful start.

**Comment by SauceyNuggets420** [comment]
@Slasar41 Apologies for tagging you, not very familiar with git, but I spent the day messing around with the old mangahub lua file and I managed to update it to download chapters again. I had to change the getinfo and getpagenumber functions but I believe it works well now. I have put the code in this pastebin: https://pastebin.com/5ESHkZft

**Comment by Slasar41** [comment]
Still not quiet working. If you scrap directly from the site instead of using the API, FMD will only get 6 images.
As for the chapter list, this code is simpler:
```lua
		local v for v in x.XPath('//li[contains(@class, "list-group-item")]//a[not(@rel)]').Get() do
			MANGAINFO.ChapterLinks.Add(v.GetAttribute('href'))
			MANGAINFO.ChapterNames.Add(x.XPathString('span/span[1]', v))
		end
```

I also spent hours tried fixing the download but no luck.

**Comment by googleitffs** [comment]
Same for me. Also, mangadex too. Is the dev not working on the app anymore?

**Comment by Slasar41** [comment]
@googleitffs If you don't see the chapter list in MangaDex, go to Options -> Websites -> Options -> MangaDex and change the language.

**Comment by googleitffs** [comment]
> @googleitffs If you don't see the chapter list in MangaDex, go to Options -> Websites -> Options -> MangaDex and change the language.

Lol, it was showing Czech for some reason. Now I changed it to English and the chapters are showing and downloading again! Thanks!
