### ISSUE TITLE
[bug-website module]  mgeko not grabbing info or chapters

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#1687]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 22H2 x64

### Describe the bug

mgeko.cc is not grabbing the info or chapters and the workaround isn't working either. worked recently around 3-4 days ago

https://www.mgeko.cc/manga/evolution-from-carp-to-divine-dragon/

https://www.mgeko.cc/manga/grand-dwarf/

**Comment by Slasar41** [comment]
Works fine here.
![image](https://github.com/user-attachments/assets/ea575327-02a8-4861-8142-46ab5f77321c)

**Comment by jillybeans** [comment]
> Works fine here. ![image](https://private-user-images.githubusercontent.com/28888646/371368289-ea575327-02a8-4861-8142-46ab5f77321c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDYzOTQsIm5iZiI6MTcyNzQwNjA5NCwicGF0aCI6Ii8yODg4ODY0Ni8zNzEzNjgyODktZWE1NzUzMjctMDJhOC00ODYxLTgxNDItNDZhYjVmNzczMjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAzMDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZDFiYTA3Mjg4MDI5NWFlOTA1MjlkMTU0MjA0NTA5OTZlNzg1MmJhYThjYmEyYjVkODFkZWQxMDkyMGIzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b9zu2EVx8K4zRPDJDV4gyyUn7vTpiqaAggqom2cRLgw)

yeah it works now for me too, but was broken before, oh wells, thanks for checking
