### ISSUE TITLE
[bug-website module] mangacanblog.com

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1688]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 11 64bit lastest build update

### Describe the bug

mangacanblog.com can detect the chapter but failed to download

**Comment by Slasar41** [comment]
Works fine here.
![image](https://github.com/user-attachments/assets/09919b8e-3eeb-4b65-a6c4-cd007d2048b9)
