### ISSUE TITLE
[bug-website module] komikcast website domain changed and fail to load/download pages

### ISSUE THREAD

**Issue by Enryougoku** [dazedcat19/FMD#1691]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11

### Describe the bug

The Website has changed domain to (dot)cz and probably have changed their layout too

**Comment by Slasar41** [comment]
Already updated. https://github.com/dazedcat19/FMD2/commit/602c3d4d94a105b823123b15dd04439ca69da1a6
