### ISSUE TITLE
[bug-website module] WeebCentral Preview missing

### ISSUE THREAD

**Issue by impishlucy** [dazedcat19/FMD#1695]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Server

### Describe the bug

![{8F3CE87A-85B6-4E3C-ABB0-264F8DA62EBA}](https://github.com/user-attachments/assets/ef99bc08-738d-4737-af89-721aa2735f92)

**Comment by Slasar41** [comment]
Works fine here.
![image](https://github.com/user-attachments/assets/ad35579f-3039-42cd-8b73-7a23557b2f07)

**Comment by impishlucy** [comment]
alright then idk
