### ISSUE TITLE
[bug-website module] MangaDex - cannot find manga that does exists on the site via search

### ISSUE THREAD

**Issue by Shajirr** [dazedcat19/FMD#1699]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

When I search the following on MangaDex in the "Manga Info" tab:

> **Kanojo no Sore ni Yarareteru** 

I get zero results. Meanwhile, this manga is on the site, here:

https://mangadex.org/title/43abd2e4-cbb0-4368-aa0d-6bb2c04caf96/kanojo-no-sore-ni-yarareteru

Another example:

**Dark Summoner** - no results, but its here:

https://mangadex.org/title/cf58401e-91ae-452f-b79a-5c83f34f6804/dark-summoner-to-dekiteiru

**Comment by Slasar41** [comment]
Update your manga list.
![image](https://github.com/user-attachments/assets/a0fe9096-7d9c-4631-88ec-a1b8b7a3a628)
