### ISSUE TITLE
[bug] Cannot change the download path of downloaded mangas

### ISSUE THREAD

**Issue by isamudysan** [dazedcat19/FMD#1704]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Under Options > Save to > Choose the default download path it was previously E:\Manga on my old PC.  I want to change that download path to F:\Manga.  I updated the download path, but when the mangas are downloaded the download path retains the old E:\Manga path and does not reflect the new F:\Manga path.

### To Reproduce

Options > Save to > Choose the default download path

### Expected behavior

The download path to have been updated and download to the correct drive.

### Screenshots

![download_path](https://github.com/user-attachments/assets/ad25198e-1828-48b1-a603-ff8a9cd5e663)
![download_path_old](https://github.com/user-attachments/assets/cc980078-9bfa-4bb9-a4ea-e93fff317f1b)

**Comment by Slasar41** [comment]
That setting only applied for the new manga.
If you want to change the path for the manga you already downloaded, go to Favorites -> Select a manga and right click -> Change "save to". You can select multiple mangas at once too.

**Comment by isamudysan** [comment]
Thank you. Thank you. Learned something new that I’m not aware of.
