### ISSUE TITLE
[bug] Search in all sites exception error

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD#1705]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 22H2 x64

### Describe the bug

When trying to search in all manga sites get exception error

```
Program exception!
Application       : Free Manga Downloader
Version           : 2.0.33.0
Product Version   : Win64
Host Machine      : Windows 10 64-bit Build 19045
FPC Version       : 3.2.3
LCL Version       : 3.4.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2024/10/05 21:25:46
Path              : C:\DOS\fmd 2.0\fmd.exe
Process ID        : 84216
MainThread ID     : 117700
Thread ID         : 117700
Time              : 07/10/2024 05:23:25.188
Exception Object  : 0000000005E4AFE0
Exception Class   : EDatabaseError
Message           : Invalid type conversion to Integer in field website
```

### To Reproduce

1. Manga Info > Filter tab
2. Settings checked search all genre and search in all manga sites
3. Searched for 'Haite Kudasai'

Get exception error

### Expected behavior

Search will find sites with the title

### Screenshots

![image](https://github.com/user-attachments/assets/be8f7327-9a96-4e4a-93bb-0b40c26c89f6)

**Comment by Slasar41** [comment]
Will be fixed in the next release.
