### ISSUE TITLE
[bug-website module] kappabeast.com

### ISSUE THREAD

**Issue by 7h3Cub3** [dazedcat19/FMD#1707]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11

### Describe the bug

Hello,

I saw that this site isn't working anymore, from what i've seen they added cloudflare, i tried the manual method and webdriver method but without success. I also saw that they changed the url to the manga 

from https://kappabeast.com/series/list-mode/ to https://kappabeast.com/manga/list-mode/

Thanks in advance for your support.
Cheers.

**Comment by Geese1** [comment]
Just came here to see if anyone else was having issues with the site. I know they were doing server maintenance over the weekend, and ever since it came back up today I haven't been able to connect.

**Comment by Slasar41** [comment]
Works fine using manual workaround.
![image](https://github.com/user-attachments/assets/28162958-c3e1-4463-808b-a177f719a74d)
I'll fix the missing manga info and wrong sorting in chapter list.
