### ISSUE TITLE
[website module request] The Blank Comics

### ISSUE THREAD

**Issue by jokosablenk** [dazedcat19/FMD#1709]
### Name

The Blank Comics

### Root URL

https://theblank.net/

### Directory list URL

https://theblank.net/manga/

### Example manga info URL

https://theblank.net/manga/god-of-pleasure/

### Example chapter URL

https://theblank.net/manga/god-of-pleasure/chapter-1/

### Language

English

### Scanlation

Yes

**Comment by Slasar41** [comment]
Already supported.

**Comment by jokosablenk** [comment]
Sorry. It already supported but I cannot update manga list or download any manga. I'll open new issue
