### ISSUE TITLE
filter search not working on Release: 2.0.33.0

### ISSUE THREAD

**Issue by ves6666** [dazedcat19/FMD#1711]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 22H2 Build 19045.5011

### Describe the bug

When performing a search with "Search in all manga sites" enable I receive the following error "Invalid type conversion to Integer in field website". The full error dialog is:
Program exception!
Application       : Free Manga Downloader
Version           : 2.0.33.0
Product Version   : Win64
Host Machine      : Windows 10 64-bit Build 19045
FPC Version       : 3.2.3
LCL Version       : 3.4.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : x86_64-Win64
Build Time        : 2024/10/05 21:25:46
Path              : G:\fmd_2.0.33.0_x86_64-win64\fmd.exe
Process ID        : 1680
MainThread ID     : 21480
Thread ID         : 21480
Time              : 09/10/2024 18:33:31.348
Exception Object  : 000000000688C9E0
Exception Class   : EDatabaseError
Message           : Invalid type conversion to Integer in field website

I have not updated an old version but downloaded latest version, updates all modules and then I updated two of the default sites already loaded. Search work on single site.
Let me know if I an doing anything wrong. 

### To Reproduce

1-Download new Release: 2.0.33.0 from GitHub
2-Unpack zipped file in its own directory
3-Download all modules
4-run update all list at once until FanFox and MangaHere are updated
5-run a search for any word with Search in all manga sites enabled

### Expected behavior

Search result displayed as in Release: 2.0.31.0

### Screenshots

![Clipboard Image](https://github.com/user-attachments/assets/a79147c8-ec02-432c-9bae-0247aaee18ab)

**Comment by impishlucy** [comment]
Search for manga you want to do on the websites and then either search the name or paste the url into the url bar.
FMD2 is basically only getting Module updates, the app itself only recently got a new programmer, but the code is bad, so this likely wont get fixed anytime soon (if at all)

**Comment by impishlucy** [comment]
Just a workaround, you are free to report the bugs, but just fyi that it very likely wont get fixed

**Comment by Slasar41** [comment]
Fixed in the next release soon.

**Comment by impishlucy** [comment]
That i did not expect lol
