### ISSUE TITLE
[bug] Filename cut off after a certain length

### ISSUE THREAD

**Issue by impishlucy** [dazedcat19/FMD#1712]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Wine Experimental

### Describe the bug

Very long filenames get cut off, Folders dont seem to be affected.

### To Reproduce

1. Find a Manga with a excessivly long name
2. Download it
3. The files will get overwritten as the filename is so long that it gets cut off

### Expected behavior

It downloads the files with the full filename.

### Screenshots

![{F81D57E2-A3D4-4720-945B-9148DE83E84B}](https://github.com/user-attachments/assets/0188c02a-119e-47ea-b92e-6f37904827fd)
![{5088A22B-0F5F-4AE5-A899-281470872836}](https://github.com/user-attachments/assets/69a3bfb4-7d5a-49e6-845b-9789c5ddedda)

### Additional context

We dont talk about what the manga is about :P

**Comment by Slasar41** [comment]
How do you create the .cbz file as one title?

**Comment by impishlucy** [comment]
> How do you create the .cbz file as one title?

![{C7C21401-F0DF-40E1-95CF-DF73E9F4857D}](https://github.com/user-attachments/assets/e815e505-fab5-455c-8262-06d4e6a7cb33)

**Comment by impishlucy** [comment]
I hope that is what you mean

**Comment by impishlucy** [comment]
This issue still persists but i have found a workaround, if you add the Manga as a Favorite you cant rightlick it to change the Name & Download Folder so technically you could give it a shorter name to avoid this

**Comment by Slasar41** [comment]
Okay I can reproduce it. If you also put `%MANGA%` to chapter name then you can uncheck `Auto generate folder based...` and the filename will not be cut off. Maybe there's an intended limit.

**Comment by impishlucy** [comment]
> then you can uncheck Auto generate folder based...

nope i cannot, then the manga all land in the download folder, i want each manga to be in its each folder inside the download path, way more manageable that way, also my Manga Client needs it that way anyways

**Comment by Slasar41** [comment]
Try with this.
Go to Options -> General, enable `Enable long name paths`.
Test it with other sites and titles too.
[fmd.zip](https://github.com/user-attachments/files/17413350/fmd.zip)

**Comment by impishlucy** [comment]
> Try with this. Go to Options -> General, enable `Enable long name paths`. Test it with other sites and titles too. [fmd.zip](https://github.com/user-attachments/files/17413350/fmd.zip)

seems to work

**Comment by Slasar41** [comment]
Nice. Will be added to more people in the next release.
