### ISSUE TITLE
[bug-website module] Cannot Download from The Blank Comics

### ISSUE THREAD

**Issue by jokosablenk** [dazedcat19/FMD#1714]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

I cannot update manga list or downlaod any manga from the site

![Untitled](https://github.com/user-attachments/assets/0c7e72eb-1da5-41bd-a391-3abf78c64f4d)

**Comment by Slasar41** [comment]
Do manual cookie workaround or check the pinned issue.
