### ISSUE TITLE
[bug-website module] WeebCentral Advanced Controls crash FMD2

### ISSUE THREAD

**Issue by impishlucy** [dazedcat19/FMD#1718]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Wine

### Describe the bug

if i try to enable the Advanced Controls for WeebCentral FMD2 Crashes without any Error.
![{F16B059C-857D-4D32-B2B5-33D027AC92C5}](https://github.com/user-attachments/assets/daf1ce45-73c3-4129-b3e8-d2bacd17673b)

**Comment by Slasar41** [comment]
Works fine on my end.

**Comment by impishlucy** [comment]
Tested it again on my pc, seems to be something with my docker container, i back up my settings and reinstall it fully
