### ISSUE TITLE
[bug-website module] hentainexus

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1729]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 11 64bit lastest build update

### Describe the bug

https://hentainexus.com/
some manga/doujinshi can't downloaded perfectly
for example some of other series can all downloaded on other series it's done but we just got 1 page cover on the front only
like this one https://hentainexus.com/view/17263
.
btw this web had their own features download n compress it to .zip

**Comment by Slasar41** [comment]
Works fine here.
![image](https://github.com/user-attachments/assets/81904390-b0f7-4eff-8b10-3ad07d2ace52)

**Comment by darkflee** [comment]
> Works fine here. ![image](https://private-user-images.githubusercontent.com/28888646/376016570-81904390-b0f7-4eff-8b10-3ad07d2ace52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjE0ODYsIm5iZiI6MTcyODgyMTE4NiwicGF0aCI6Ii8yODg4ODY0Ni8zNzYwMTY1NzAtODE5MDQzOTAtYjBmNy00ZWZmLThiMTAtM2FkMDdkMmFjZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEyMDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYmMxYjNhOTU5YTllZWJmYzRhZDllMTBhZGZjY2ViMmE0MTQ1MGI5OGU3NDI3YmIwMzE1MWZkMzRlZTE0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IFPqyXyjCcWIhXgh-i1U4eNhPjgLbwOT-_g76KIsC8U)

oh it's fine maybe it's my connection? i'll try once again later thx for the info
