### ISSUE TITLE
[bug] FMD inaccesible after changing main monitor

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [dazedcat19/FMD#1740]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 11 23H2

### Describe the bug

I seem to had had FMD open on my secondary monitor until I changed which one was my primary to make things a bit easier for me. Now, when I open FMD, any pop-up windows show up besides the edge of the screen, FMD won't show up and trying to get it to fullscreen (a method I use with other programs when their position is corrupted), it's like if an empty transparent window fills the screen and I just can't click anything behind it.

### To Reproduce

Seemingly, unless the cause is not what I believe:

- Open FMD.
- Set it on the secondary screen.
- Close it.
- Change your primary screen.
- (Optional) Reset your computer.
- Open FMD.

### Expected behavior

- FMD is relocated to any of the screens (primary or new secondary).
- Otherwise, getting it into fullscreen from the task manager should show a correctly displayed interactible fullscreen version of the program which should allow dragging for repositioning.

**Comment by l-l-l-l-l-l** [comment]
After trying to find a fix by renaming my userdata folder, it seems like the issue lies on the fact that the "form" table in settings.json somehow disappeared. "droptarget" also seems to have been moved from before "general" to after it.

PS. Trying to just add the missing table to the json just prevents FMD from running, you have to just copy your db lists (downloaded chapters, downloads and favorites) to the new userdata folder and manually edit the new settings.json to recover any custom settings.
PS2. Found why it didn't work with the original: "form" hadn't vanished, it had been moved to after "logger". And the values were way over the edge.

**Comment by NhKPaNdA** [comment]
Can you send the values of "form" or your entire settings.json file since I don't have a second screen to replicate myself.

**Comment by Slasar41** [comment]
@l-l-l-l-l-l Could you test it?
[fmd.zip](https://github.com/user-attachments/files/17477282/fmd.zip)

**Comment by Slasar41** [comment]
Fixed in version 2.0.34.0
