### ISSUE TITLE
[bug] failed, try resuming this task

### ISSUE THREAD

**Issue by Kharlitoz21** [dazedcat19/FMD#1768]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 11 pro 23h2

### Describe the bug

Help please, I'm trying to download from TMO but this always comes out, I think I don't know how to use the program

### To Reproduce

a

### Expected behavior

a

### Screenshots

![image](https://github.com/user-attachments/assets/5ea17751-e320-41c0-bb9f-a74961d1267b)

### Additional context

a

**Comment by Slasar41** [comment]
It's because TMO module is broken and hard to fix.
https://github.com/dazedcat19/FMD2/issues/522
