### ISSUE TITLE
[bug] desaparecieron todos los sitios web de favoritos

### ISSUE THREAD

**Issue by Jacobo-Estanol-Hernandez** [dazedcat19/FMD#1777]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

windows 11 pro

### Describe the bug

abri el programa y me salto una ventana con un error 
![Captura de pantalla 2024-10-29 004612](https://github.com/user-attachments/assets/6d3ee831-1d53-46e4-b20f-65792e55dbd0)
di clic en la opcion si y ahora tengo mi lista de favoritos pero no funciona nada 

### To Reproduce

ejecutar el programa me muestra mi informacion pero no hace nada 
![Captura de pantalla 2024-10-29 005421](https://github.com/user-attachments/assets/eb67ca0c-3253-4806-86ac-69472b21713b)

### Expected behavior

que buscara automaticamente si hay nuevos capitulos 

### Additional context

espero me puedan ayudar a resolverlo o si es error de mi parte como lo resuelvo 
de antemano gracias

**Comment by Slasar41** [comment]
Go to Options -> Websites -> Modules, update it from there.

**Comment by Jacobo-Estanol-Hernandez** [comment]
si me rosolvio lo de los sitios web, pero me borro todos los favoritos, me dejo la lista vacia, ¿hay modo de recuperar la lista de favoritos?
![Captura de pantalla 2024-10-29 235100](https://github.com/user-attachments/assets/15cbfa96-ca72-4d84-952d-b606d48483bb)
![Captura de pantalla 2024-10-29 235114](https://github.com/user-attachments/assets/9a92226a-d4cf-416b-a206-a6f3ba1ea482)

**Comment by Slasar41** [comment]
You can restore your data from `backup` folder.

**Comment by Jacobo-Estanol-Hernandez** [comment]
no funciona 
al restaurar desde un backup, si aparace la lista de favoritos de nuevo, pero el programa deja de funcionar ya que desaparecen los sitios web y ya no me deja descargarlos.
al final baje de nuevo el fmd y me puse a buscar los mangas de nuevo.
asumo que el probema esta en las versiones del programa

**Comment by Slasar41** [comment]
I forgot to tell. You just need to extract the `downloadedchapters.db`, `downloads.db`, and `favorites.db`.
You just need these files to restore your data. Don't replace the other files.

**Comment by Jacobo-Estanol-Hernandez** [comment]
pues lo hecho, hecho esta. y ya borre la version anterior del programa
gracias por la info espero me sirva a futuro
