### ISSUE TITLE
[website module request] manhwatoons

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1779]
### Name

manhwatoons

### Root URL

https://www.manhwatoons.com/

### Directory list URL

https://www.manhwatoons.com/

### Example manga info URL

https://www.manhwatoons.com/manhwa/addicted-to-my-stepmom/

### Example chapter URL

https://www.manhwatoons.com/manhwa/addicted-to-my-stepmom/addicted-to-my-stepmom-chapter-67/

### Language

English

### Scanlation

No

### Website relationship

manhwatoons.com is 18+ content manga manhwa from manhwatoon.com
include for EN + RAW scan

**Comment by Slasar41** [comment]
Duplicate of https://github.com/dazedcat19/FMD2/issues/1778
