### ISSUE TITLE
[bug] Manga name not appeared when downloading

### ISSUE THREAD

**Issue by jokosablenk** [dazedcat19/FMD#1795]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 22H2 x64

### Describe the bug

manga name, status, etc. not appeared when downloading

### To Reproduce

just download any manga from supported site

### Expected behavior

manga name, status, etc. appeared

### Screenshots

![ui error](https://github.com/user-attachments/assets/fb59b840-c865-44ac-b69a-894ee1a3fe98)

**Comment by Slasar41** [comment]
Check here:
![image](https://github.com/user-attachments/assets/03d2d622-74c8-4408-ab3f-be8897d3a467)
