### ISSUE TITLE
[website module request] Temple Scans

### ISSUE THREAD

**Issue by inheritno** [dazedcat19/FMD#1798]
### Name

Temple Scans

### Root URL

https://templetoons.com

### Directory list URL

https://templetoons.com/comics

### Example manga info URL

https://templetoons.com/comic/age-of-arrogance

### Example chapter URL

https://templetoons.com/comic/age-of-arrogance/19253-chapter-36

### Language

English

### Scanlation

Yes

**Comment by Slasar41** [comment]
Temple Scans already supported. Please create a new issue to change the domain.
