### ISSUE TITLE
[website module request] Thunder Scans

### ISSUE THREAD

**Issue by jokosablenk** [dazedcat19/FMD#1799]
### Name

Thunder Scans

### Root URL

https://en-thunderscans.com/

### Directory list URL

https://en-thunderscans.com/comics/

### Example manga info URL

https://en-thunderscans.com/comics/demonic-emperor/

### Example chapter URL

https://en-thunderscans.com/demonic-emperor-chapter-0/

### Language

English

### Scanlation

Yes

**Comment by Qizmo** [comment]
If can have Thunder Scans, it will be really great ^^
