### ISSUE TITLE
[bug-website module] Nicomanga.com can't download chapters

### ISSUE THREAD

**Issue by TienVer** [dazedcat19/FMD#1801]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Somewhere around the 5th of November, chapter downloads from Nicomanga.com started to fail. No image whatsoever successfully downloads. I seem to remember there being a nicomanga module update not that long ago, but I don't know if it's the root of the current problem or if something changed in how the images are stored/named/etc.

In the meantime, I made sure that the parameter values (such as PHPSESSID, hash, userId, _GPSLSC) in FMD2's website settings were still up to date (using developer tools on my browser to check cookie contents) and sure enough, nothing seems to have changed - everything still matches. I even updated my userAgent value just to be sure, but no dice.

Downloads still fail.

![NCMERR](https://github.com/user-attachments/assets/c5c947c5-41c6-47c2-b45c-d8bd21efda29)

**Comment by Slasar41** [comment]
You don't have to do manual cookie again. The site don't have the protection anymore.
