### ISSUE TITLE
[bug-website module] hipertoon

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1808]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 11 64bit lastest build update

### Describe the bug

https://hipertoon.com/
got na when capture.
i think the cloud, bcs trying monitoring the phyton can't go trought.

**Comment by Slasar41** [comment]
Yeah it's cloudflare. You can do manual cookie workaround.
