### ISSUE TITLE
[feature request]MangaLib account

### ISSUE THREAD

**Issue by LordARTOG** [dazedcat19/FMD#1834]
**Is your feature request related to a problem? Please describe.**
MangaLib has some manga closed for people without account

**Describe the solution you'd like**
Add MangaLib to Websites->Accounts
![image](https://github.com/user-attachments/assets/cf33edca-9bc3-4c33-85d5-020baef862cd)

**Describe alternatives you've considered**
Don't know any alternative

**Additional context**
Mange page when loged in
![image](https://github.com/user-attachments/assets/a06cf220-42b8-4bcf-9b94-988a90940a28)
Manga page without login
![image](https://github.com/user-attachments/assets/a5b42d16-2008-4581-a1f4-403cbdc7d357)

**Comment by Slasar41** [comment]
No option to create an account with just email and password?
![image](https://github.com/user-attachments/assets/b2b0770a-1d7f-4994-8cf7-0dc8765c4881)

**Comment by LordARTOG** [comment]
> No option to create an account with just email and password? ![image](https://private-user-images.githubusercontent.com/28888646/387456354-b2b0770a-1d7f-4994-8cf7-0dc8765c4881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5ODY2NjUsIm5iZiI6MTczMTk4NjM2NSwicGF0aCI6Ii8yODg4ODY0Ni8zODc0NTYzNTQtYjJiMDc3MGEtMWQ3Zi00OTk0LThjZjctMGRjODc2NWM0ODgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDAzMTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWYzOTExM2Q4NzI3MjQ0MGQxOTdiNjRjYjk5MjE1NWViZTU1YTA1NDgxYzM2Y2JkMmE5M2Y2NzM3MDYxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dJufSoef95Sfum-zC6N_CuJsDY8AQI_IZf_V43hDo6s)

After registration you can add email and password in security settings. But registration only by social

**Comment by LordARTOG** [comment]
> No option to create an account with just email and password? ![image](https://private-user-images.githubusercontent.com/28888646/387456354-b2b0770a-1d7f-4994-8cf7-0dc8765c4881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTUyMjMsIm5iZiI6MTczMTk5NDkyMywicGF0aCI6Ii8yODg4ODY0Ni8zODc0NTYzNTQtYjJiMDc3MGEtMWQ3Zi00OTk0LThjZjctMGRjODc2NWM0ODgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA1NDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjNlNjhmYWRkZmFmNGUxYzIwM2E2MWFmZDVmOTU4NGFkZmIxMTY4OTAxYjRhZTYyMzdkMTQ2ZjNhMmZmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gTj9Maft0IkEYoC21qSH8fphBhP0Hsa_jmwege9q9Qo)

if you want i can create account(email and password) for for you just for testing

**Comment by Slasar41** [comment]
Yes, please. Do you have discord?

**Comment by LordARTOG** [comment]
> Yes, please. Do you have discord?

I have but it blocked in my country, so not working correctly

**Comment by Slasar41** [comment]
Send to this email:

**Comment by LordARTOG** [comment]
> Send to this email: 

sended

**Comment by Slasar41** [comment]
thanks, will test it later

**Comment by Slasar41** [comment]
Sorry, I can't make it work.
Even though the status is already OK, the chapter list is still empty.
Manual cookies doesn't work either.
![image](https://github.com/user-attachments/assets/4f703900-0b77-4d0f-8eb5-29b9a243d9f0)

**Comment by LordARTOG** [comment]
Ok then. Will download this manga by hands. Thanks

**Comment by LordARTOG** [comment]
> Sorry, I can't make it work. Even though the status is already OK, the chapter list is still empty. Manual cookies doesn't work either. ![image](https://private-user-images.githubusercontent.com/28888646/387720069-4f703900-0b77-4d0f-8eb5-29b9a243d9f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzA5NDAsIm5iZiI6MTczMjAzMDY0MCwicGF0aCI6Ii8yODg4ODY0Ni8zODc3MjAwNjktNGY3MDM5MDAtMGI3Ny00ZDBmLThlYjUtMjliOWEyNDNkOWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZTMwMThkNDJhZDJhOWRiZjk0Y2JmYmZjZTk0ZTFiMzgxZTBiNjM1MjdkYzYyNDAyNmJkZmU5NTM4NDAxNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rVoZNWImkrbY9W7O6GdAc0XRC6dkYrxW-dMtDFHoKmY)

Wait. Can you try no MangaLibOrg but MangaLibMe? Maybe this is problem?

**Comment by Slasar41** [comment]
It's the same. I just use .org because I don't have to use a VPN.

**Comment by LordARTOG** [comment]
> It's the same. I just use .org because I don't have to use a VPN.

Ok. I close the request then. Thanks for helping

**Comment by Slasar41** [comment]
Now I have a way to show the chapter list.
You need to get the authorization code manually from browser but it's working.
![image](https://github.com/user-attachments/assets/a413844d-c6fa-4a09-aa1c-18121a44302a)

**Comment by LordARTOG** [comment]
> Now I have a way to show the chapter list. You need to get the authorization code manually from browser but it's working. ![image](https://private-user-images.githubusercontent.com/28888646/403007259-a413844d-c6fa-4a09-aa1c-18121a44302a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NzIwNTksIm5iZiI6MTczNjg3MTc1OSwicGF0aCI6Ii8yODg4ODY0Ni80MDMwMDcyNTktYTQxMzg0NGQtYzZmYS00YTA5LWFhMWMtMTgxMjFhNDQzMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDE2MjIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YjY0YmU2ZjZhMmYxMmU5ZmU2NWYxM2UxYjdkMDlmMGJkN2RlNzM0MzM1MWYxMTUyOWE0MTU0ZTY4MGVhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fIMxpRenyXD_nYESNspYhn2PIhqT4Pa6fZ1nIWG4sfo)

I need a guide how to do it and i will be glad to test it myself and even asks friends to test this feature

**Comment by Slasar41** [comment]
- Login your account.
- Go to series page and then press F12.
- Select `Fetch/XHR` and then select manga name.
- Search for `Authorization`, copy all.
- In FMD go to `Options -> Websites -> Options -> MangaLib`, paste to `Authorization`.
- After that press `Apply`.
![image](https://github.com/user-attachments/assets/affb0517-858d-4259-96f6-414cc9622aa6)
