### ISSUE TITLE
[bug-website module] Manhwadesu

### ISSUE THREAD

**Issue by klinnxz** [dazedcat19/FMD#1835]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7

### Describe the bug

I've been waiting a very long time

![image](https://github.com/user-attachments/assets/fb0e7375-9b14-4f4b-a85a-deac259d0e49)

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://github.com/user-attachments/assets/310907ea-9dd6-464c-b7e9-d889492dc747)
