### ISSUE TITLE
[bug] Dont work list website

### ISSUE THREAD

**Issue by Alla183** [dazedcat19/FMD#1837]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 10 22H2 x64

### Describe the bug

Downloaded the release and installed fmd.exe. But there is no list of websites at all. I need to configure some modules or download something else? I did not find the instructions for use. Help figure it out.

### To Reproduce

Options - Websites.

### Expected behavior

List of website.

### Screenshots

![image](https://github.com/user-attachments/assets/065a516c-c901-4c24-a2db-95917eb4250f)

![image](https://github.com/user-attachments/assets/e11651c3-ecd5-43bf-93b1-ccda8aa54cbd)

### Additional context

Help.

**Comment by Slasar41** [comment]
What FMD version?

**Comment by Alla183** [comment]
> What FMD version?

fmd_2.0.33.1_x86_64-win64.7z

**Comment by Slasar41** [comment]
Clicking the `Check update` button do nothing?
Try go to Options -> Misc -> Log, enabled it, try clicking the `Check update` button again and see the log.

**Comment by Alla183** [comment]
Click "Check update" - nothing.
Log 
![image](https://github.com/user-attachments/assets/28470d79-ace5-42f3-a431-0f167484237a)

**Comment by Alla183** [comment]
> Натискання `Check update`кнопки нічого не робить? Спробуйте перейти до Параметри -> Різне -> Журнал, увімкніть його, спробуйте натиснути `Check update`кнопку ще раз і переглянути журнал.

![image](https://github.com/user-attachments/assets/a54164c4-6cff-4fa1-abad-92c633b58c0f)

**Comment by Slasar41** [comment]
You need to check `Enable logging` then press `Apply` first.

**Comment by Alla183** [comment]
> Вам потрібно перевірити, `Enable logging`а потім натиснути `Apply`спочатку.

this?
![image](https://github.com/user-attachments/assets/e79ebfe1-1370-4745-88e2-d6db9725e9d6)

**Comment by Slasar41** [comment]
There you go, an error listed there. Something about FMD don't have the permission to write.
Try moving FMD folder elsewhere, maybe to D: drive.

**Comment by Alla183** [comment]
> Ось помилка в списку. Щось про ящур не маю дозволу писати. Спробуйте перемістити папку FMD в інше місце, можливо, на диск D:.

Only disk C

**Comment by Alla183** [comment]
> There you go, an error listed there. Something about FMD don't have the permission to write. Try moving FMD folder elsewhere, maybe to D: drive.

I put it on the disk C, and this appeared
![image](https://github.com/user-attachments/assets/049542ec-ae10-4a99-baa8-07a0f7980109)

**Comment by Slasar41** [comment]
Press `Yes` and after it done FMD should restart.

**Comment by Alla183** [comment]
> Натисніть `Yes`, і після цього ящур має перезапуститися.

falied
![image](https://github.com/user-attachments/assets/fe05d5a3-6662-46a9-8a08-67a9b22a5759)

**Comment by Slasar41** [comment]
Sorry, I'm not sure anymore. Your drive have the limitation that make FMD unable to write.

**Comment by Alla183** [comment]
> Sorry, I'm not sure anymore. Your drive have the limitation that make FMD unable to write.

and what am I supposed to do? Is there any way to fix it?

**Comment by Slasar41** [comment]
The fix is you need to find out why FMD unable to write. Is there any software like antivirus that have folder restriction, etc.

**Comment by Alla183** [comment]
> The fix is you need to find out why FMD unable to write. Is there any software like antivirus that have folder restriction, etc.

Run this process. This good?
![image](https://github.com/user-attachments/assets/ce5843aa-af00-4e85-91b4-07f21b18cfb8)

**Comment by Slasar41** [comment]
Maybe.
You don't have to update manga list, you can just copy the manga link from browser to FMD.

**Comment by Alla183** [comment]
> можливо. Вам не потрібно оновлювати список манги, ви можете просто скопіювати посилання на мангу з браузера до FMD.

It's working, thank you so much for your help.
