### ISSUE TITLE
[bug-website module] Cannot Update Manga List for Pururin.me

### ISSUE THREAD

**Issue by Redevil387** [dazedcat19/FMD#1839]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 11 23H2

### Describe the bug

(I'm assuming this is a module error)
When I  select "Update Manga List" for Puruin.me the loading bar on the bottom of the page flickers that it's updating the list "1/2138" before stopping.

I also tried to Download Manga List from sever to see if that resolves the issue to similar effect since, though I suspect that's because I already downloaded from the server a few days ago with the module update.

Update Manga List does work for other modules.

**Comment by Slasar41** [comment]
Try removing all titles from the list before updating manga list again.

**Comment by Slasar41** [comment]
FMD will only get new titles if you already have the manga list.
Let me know if you believe some titles are missing from manga list.

**Comment by Redevil387** [comment]
I'd already downloaded the manga list, but I do seem to be a few titles missing.

**Comment by Slasar41** [comment]
Please list a few titles.

**Comment by Redevil387** [comment]
A few I picked out with a casual search:
Enkou Ojisan / 円光おじさん
Mail-Order Elf
Sister Coin / シスターコイン

**Comment by Slasar41** [comment]
Okay I think I found the issue. FMD only got 2138 directory pages which should be 2610 like in the website. Will try to fix it.

**Comment by Slasar41** [comment]
You need to be logged in to be able to see more titles from directory. I already updated the manga list so you can redownload from server.

Also did you know you can paste a link containing `/tags/`? Example: `https://pururin.me/browse/tags/collection/17968/rito-san-no-harem-seikatsu`. FMD will load all titles into chapter list.

**Comment by Redevil387** [comment]
Thanks for the help!

I tried linking my account but I keep getting invalid.
The username and password are the same ones UI use on my browsers so it should link but no success. Is it me or not working for others as well?

**Comment by Slasar41** [comment]
Same thing happened to me and I have to try multiple time to succeed. I've pushed an update to minimalize the issue.
