### ISSUE TITLE
Add support for MangaDemon

### ISSUE THREAD

**Issue by dcostaz** [dazedcat19/FMD#1853]
### Name

MangaDemon

### Root URL

https://demonicscans.org

### Directory list URL

https://demonicscans.org/lastupdates.php

### Example manga info URL

https://demonicscans.org/manga/The-Heavenly-Demon-Wants-a-Quiet-Life

### Example chapter URL

https://demonicscans.org/title/The-Heavenly-Demon-Wants-a-Quiet-Life/chapter/1/1

### Language

English

### Scanlation

No

**Comment by Slasar41** [comment]
Already supported. https://github.com/dazedcat19/FMD2/commit/9b2d341595b778de6f376391eb6d798944ba4b18
