### ISSUE TITLE
[bug-website module] MangaLib download error

### ISSUE THREAD

**Issue by LordARTOG** [dazedcat19/FMD#1855]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2 x64

### Describe the bug

When i try to download manga from mangalib i have an error.
If i checked correctly error exist cause of extra **/** in url like 
`https://img2.imglib.info//**/**manga/tetsuwan-badi/chapters/3360941/ca2ea01b-b317-4c7a-a84a-68fca5f61f3d.jpg`
because i checked this URl on manga site and it was 
`https://img2.imglib.info//manga/tetsuwan-badi/chapters/3360941/ca2ea01b-b317-4c7a-a84a-68fca5f61f3d.jpg`
As you can see the is only two / and not three.

### Log

Part of log:
22:48:48:191 WARNING: TTaskThread.CheckForFinish failed 7 of 19 [MangaLib] "Tetsuwan Birdy Evolution" > "/manga/26740--tetsuwan-badi/chapter?number=35&volume=3&branch_id=19552"
[002] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/ca2ea01b-b317-4c7a-a84a-68fca5f61f3d.jpg
[006] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/8427acfd-9038-4e80-8bdb-44cca5ef59e5.jpg
[008] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/80dffd6b-e77b-4266-bf49-669dc5bcbfe8.jpg
[009] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/36a281d3-bdd5-4731-a4f2-affb50266959.jpg
[015] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/2b7c6839-8c09-4190-815d-22c4b81fc81b.jpg
[016] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/1857e74c-9299-4a3d-918f-c1f926caa561.jpg
[017] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/96fca627-ecb6-46fd-8e7c-835a7a0b787f.jpg

**Comment by LordARTOG** [comment]
Also i have change for ReadManga and MintManga modules(sites change their names and links) hopw i can give it to you guys?

**Comment by Slasar41** [comment]
Server issue. You also can't see it in website.
![image](https://github.com/user-attachments/assets/0ef3a638-945f-4dca-8f9b-71a95d93e585)

Sure. You can make a pull request for these sites.

**Comment by LordARTOG** [comment]
> Server issue. You also can't see it in website. ![image](https://private-user-images.githubusercontent.com/28888646/390634993-0ef3a638-945f-4dca-8f9b-71a95d93e585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzI2NDcsIm5iZiI6MTczMjc3MjM0NywicGF0aCI6Ii8yODg4ODY0Ni8zOTA2MzQ5OTMtMGVmM2E2MzgtOTQ1Zi00ZGNhLThmOWItNzFhOTVkOTNlNTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGE0OGM4MGIxOWNiMmZlMGY1MjZkZTUwZjI5ODYzOWJmMzAzNjE0N2QyYjUzYjkzZmM2NGE4NmRiMjAwODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T0fFGoXrNvFtGwBmdamiTdhFD-jFa2Voka3pDdxekAI)
> 
> Sure. You can make a pull request for these sites.
Can see it on website and by url, FMD also on main server
![image](https://github.com/user-attachments/assets/2708eb04-3417-4bf6-900f-37572fcf1189)
![image](https://github.com/user-attachments/assets/2ad73104-2173-48f8-bc3b-55555444efb0)
![image](https://github.com/user-attachments/assets/46df897c-9d8f-4107-a643-a22daf9346ac)

 But in logs
08:43:48:116 WARNING: TTaskThread.CheckForFinish failed 7 of 19 [MangaLib] "Tetsuwan Birdy Evolution" > "/manga/26740--tetsuwan-badi/chapter?number=35&volume=3&branch_id=19552"
[002] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/ca2ea01b-b317-4c7a-a84a-68fca5f61f3d.jpg
[006] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/8427acfd-9038-4e80-8bdb-44cca5ef59e5.jpg
[008] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/80dffd6b-e77b-4266-bf49-669dc5bcbfe8.jpg
[009] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/36a281d3-bdd5-4731-a4f2-affb50266959.jpg
[015] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/2b7c6839-8c09-4190-815d-22c4b81fc81b.jpg
[016] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/1857e74c-9299-4a3d-918f-c1f926caa561.jpg
[017] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/96fca627-ecb6-46fd-8e7c-835a7a0b787f.jpg
So it hard to tell it only server issue

**Comment by LordARTOG** [comment]
> > Server issue. You also can't see it in website. ![image](https://private-user-images.githubusercontent.com/28888646/390634993-0ef3a638-945f-4dca-8f9b-71a95d93e585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzI2NDcsIm5iZiI6MTczMjc3MjM0NywicGF0aCI6Ii8yODg4ODY0Ni8zOTA2MzQ5OTMtMGVmM2E2MzgtOTQ1Zi00ZGNhLThmOWItNzFhOTVkOTNlNTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA1MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNGE0OGM4MGIxOWNiMmZlMGY1MjZkZTUwZjI5ODYzOWJmMzAzNjE0N2QyYjUzYjkzZmM2NGE4NmRiMjAwODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T0fFGoXrNvFtGwBmdamiTdhFD-jFa2Voka3pDdxekAI)
> > Sure. You can make a pull request for these sites.
> > Can see it on website and by url, FMD also on main server
> > ![image](https://private-user-images.githubusercontent.com/52236081/390654919-2708eb04-3417-4bf6-900f-37572fcf1189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNDMsIm5iZiI6MTczMjc4NTA0MywicGF0aCI6Ii81MjIzNjA4MS8zOTA2NTQ5MTktMjcwOGViMDQtMzQxNy00YmY2LTkwMGYtMzc1NzJmY2YxMTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA5MTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NTI1OGMyMDQ2ZDQyZjkwZDVjM2U5MzljOWU2NTk3YmUyNmQ2MjBiNmY5NzRjOTk5Y2EwN2FiOTZkY2QwZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QFw5lsx6VkFVJvOoNIYTqTk2RPgOd8Y0HAaaicRzfy4)
> > ![image](https://private-user-images.githubusercontent.com/52236081/390654969-2ad73104-2173-48f8-bc3b-55555444efb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNDMsIm5iZiI6MTczMjc4NTA0MywicGF0aCI6Ii81MjIzNjA4MS8zOTA2NTQ5NjktMmFkNzMxMDQtMjE3My00OGY4LWJjM2ItNTU1NTU0NDRlZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA5MTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNjIyNjE1ZjRmNmQ3MTcxYjM1NzBjOGY2YTliYmY5MzUxZDE4ZjQ4MjFlZTQwMzg3NWM3MGU2ZGU1NDk5ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IhzP3HJM-hoM-27eFSHomiURfZLTwpL6Pejwnk3F0zA)
> > ![image](https://private-user-images.githubusercontent.com/52236081/390655281-46df897c-9d8f-4107-a643-a22daf9346ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODUzNDMsIm5iZiI6MTczMjc4NTA0MywicGF0aCI6Ii81MjIzNjA4MS8zOTA2NTUyODEtNDZkZjg5N2MtOWQ4Zi00MTA3LWE2NDMtYTIyZGFmOTM0NmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA5MTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYmI5MTI5ZDNmNjA2ODhjZTMxOWQyZDdkMGM1NzYzZTI0OGNkNzZjMmNiNzBhNTkyYjY0NWY3MWU2M2M1YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.12CNSnkrAQrpZv9hgeKZdmxlzkDyYGB3NR9Q2KaOH8M)
> 
> But in logs 08:43:48:116 WARNING: TTaskThread.CheckForFinish failed 7 of 19 [MangaLib] "Tetsuwan Birdy Evolution" > "/manga/26740--tetsuwan-badi/chapter?number=35&volume=3&branch_id=19552" [002] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/ca2ea01b-b317-4c7a-a84a-68fca5f61f3d.jpg [006] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/8427acfd-9038-4e80-8bdb-44cca5ef59e5.jpg [008] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/80dffd6b-e77b-4266-bf49-669dc5bcbfe8.jpg [009] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/36a281d3-bdd5-4731-a4f2-affb50266959.jpg [015] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/2b7c6839-8c09-4190-815d-22c4b81fc81b.jpg [016] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/1857e74c-9299-4a3d-918f-c1f926caa561.jpg [017] https://img2.imglib.info///manga/tetsuwan-badi/chapters/3360941/96fca627-ecb6-46fd-8e7c-835a7a0b787f.jpg So it hard to tell it only server issue

Semms to work, but one page still was not downloade so i download it by hands

**Comment by Slasar41** [comment]
Looks like it's fine now.
![image](https://github.com/user-attachments/assets/ba98702c-d0e5-421b-9169-e4cf8f36c01b)
