### ISSUE TITLE
[bug-website module] Utoon

### ISSUE THREAD

**Issue by jpwong2** [dazedcat19/FMD#1856]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

Series chapter listing for Utoon has never really worked for me, if you put in the URL for a series it just ends up returning Title: N/A and no chapter list.

I tried to look into how the LUA pulls the data up, but I couldn't see anything obviously wrong with how it works so I'm wondering if there's something I need to do to get this to work.

Example: For the Musical Genius 
https://utoon.net/manga/for-the-musical-genius/
![Capture2](https://github.com/user-attachments/assets/ac8f1daa-64cc-4168-bed4-24176815bdc5)

**Comment by Slasar41** [comment]
Works fine here. Try use a VPN.
![image](https://github.com/user-attachments/assets/d0f10acf-4fc8-4602-8c94-a15bbfb090a8)

**Comment by jpwong2** [comment]
Oh that's so strange, their site works on every browser I have properly, just not in FMD.  I'm not entirely sure what a VPN would change unless it forcibly overwrites the request headers to look like the request comes from a web browser.

**Comment by Slasar41** [comment]
So it's working with a VPN?
Do you change DNS somewhere like in browser, Windows, or router?

**Comment by jpwong2** [comment]
I didn't work with a VPN, but I downloaded the application again clean, and the URL worked, so I moved all my userdata over to the new install and it seems to be functioning properly.  I'm not sure why since all the LUAs and everything seem to be the same.  I'm just going to chalk it up to being one of those weird issues windows has sometimes.
