### ISSUE TITLE
[bug-website module] Pururin has been seized. Please pull from FMD2

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD#1871]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 22H2

### Describe the bug

Pururin been seized by the US Government so please pull this site from FMD2.  

### Log

verified here https://www.reddit.com/r/animepiracy/comments/1g17n39/pururin_is_now_gone/  and https://boards.4chan.org/h/thread/8251046/pururin-is-seized

**Comment by Slasar41** [comment]
The one gone is domain .to and there's a new domain .me.
I've updated the module. https://github.com/dazedcat19/FMD2/pull/1830/commits/b04d00e64eb9981afe1a2a99f3456a6e032ebed3
