### ISSUE TITLE
[bug-website module] ManyToon.org and ManyToon.com, too many toons

### ISSUE THREAD

**Issue by Plegmatis** [dazedcat19/FMD#1873]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Win 10 64bit 

### Describe the bug

2 months ago there was a domain change from ManyToon.com to ManyToon.org and lord Slasar fixed it #1738 
So, my favorite list that contain ManyToon.com automatically changed its domain to ManyToon.org
Now we have both of Toon.org and Toon.com and both accessible via websites but both of them not working on FMD, while Toon.com not supported (probably because old script changed domain) and Toon.org gives me blank N/A page.

NB: 
- ManyToon.com website style is the same old .com and when they first changed domain to.org
- ManyToon.org has a new style (i think iirc)
- I dont know if it's only on my side but ManyToon.org didn't give me cookies (F12-Network-Header). I cant find any cookie related
- I just realize .org url directory changed from /comic/ to /manga/ but it still gives me N/A blank page on FMD

Thank you for the time, cheers!

**Comment by Slasar41** [comment]
So revert the current module to .com and create a new module for .org. How about it?

**Comment by Plegmatis** [comment]
> So revert the current module to .com and create a new module for .org. How about it?

I think that is the best way, I dont know much about modules but judging by how the sites look and the url directories, current module more suitable for .com

Thank you for the reply, cheers!
