### ISSUE TITLE
[bug-website module] ArvenComics

### ISSUE THREAD

**Issue by dcostaz** [dazedcat19/FMD#1883]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Microsoft Windows 11 Pro 10.0.22631 Build 22631

### Describe the bug

not loading
![image](https://github.com/user-attachments/assets/1a656a35-613d-4087-ab71-221362519c4a)

**Comment by Slasar41** [comment]
You need to do cookies workaround.
![image](https://github.com/user-attachments/assets/cb53d9c0-6787-4fb3-a0f8-6f56403b51e8)
