### ISSUE TITLE
[bug-website module] hiperdex

### ISSUE THREAD

**Issue by darkflee** [dazedcat19/FMD#1886]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 11 64bit lastest build update

### Describe the bug

hipertoon revert back to hiperdex.com

**Comment by Slasar41** [comment]
Has been fixed yesterday. https://github.com/dazedcat19/FMD2/commit/1de46c3c9fa172dbbb6b97dfc321c4ca0c3e7e9e
