### ISSUE TITLE
[bug] No website list and update button not working

### ISSUE THREAD

**Issue by Salathorn** [dazedcat19/FMD#1901]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not a website module issue.

### System information

Windows 11 24H2 x64

### Describe the bug

Years ago, I was using FMD and now I need to download mangas again and I noticed FMD2. I tried everything I could but failed to work it. I didnt use FMD2 before so there might be something Im doing wrong. Please help me.
Error 1: I cant see any manga website in list so even if I click update manga list, nothing happens.
Error 2: Another strange thing is, Check for latest version button not working either. 
I tried 2.0.33.1 x64 version but when I failed, I downloaded older versions too. But still getting same errors.
Tried 33.0 , 32.0 , 25.0 , 15.0 , even 2.0.0.0 but nothing.
Probably Im missing something, maybe its not working on win11 24h2 or I dont have some programs to run it, I dont know. Please help me. Thank you.

### To Reproduce

A1. Go to Manga Info
A2. Click the list 
A3. Nothing to see
A4. Click the "Update manga list" button
A5. Choosing anything
A6. Not working
B1. Go to About
B2. Click the "Check for latest update" button
B3. Not working

### Expected behavior

To see manga list...

**Comment by Slasar41** [comment]
Options -> Misc -> Log, Enable logging then click Apply.
Repeat the errors and then upload the log here.

**Comment by Salathorn** [comment]
> Options -> Misc -> Log, Enable logging then click Apply. Repeat the errors and then upload the log here.

https://github.com/user-attachments/assets/e75bcce0-cbbe-450a-ab29-cfcc61113770

[fmd.log](https://github.com/user-attachments/files/18159783/fmd.log)

**Comment by Slasar41** [comment]
Enable this, then press `Apply`.
![image](https://github.com/user-attachments/assets/ccbe368b-28be-4173-a2bd-9c0d2deecf40)
After that, go to `Options -> Websites -> Modules`, click `Check update` and then see the log again.

**Comment by Salathorn** [comment]
> Enable this, then press `Apply`. ![image](https://private-user-images.githubusercontent.com/28888646/396346381-ccbe368b-28be-4173-a2bd-9c0d2deecf40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTAxNzgsIm5iZiI6MTczNDQwOTg3OCwicGF0aCI6Ii8yODg4ODY0Ni8zOTYzNDYzODEtY2NiZTM2OGItMjhiZS00MTczLWEyYmQtOWMwZDJkZWVjZjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA0MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MGEwYmUwNzE1NDA1NGFjYWNmZDQ5OTFmNGIwMWZmODFmMGJiNDVkMDhjMWQxYTBmMWEzMDZiODRkZTk3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RW8V6QrgMb9Bb0nAqQtBAXv-v4MxaUKsDIHsKIubd5o) After that, go to `Options -> Websites -> Modules`, click `Check update` and then see the log again.

I already did mate. Yes I know, its only showing opening and closing of fmd in logs. Have no idea why but other things not showing. Here another video.
[fmd.log](https://github.com/user-attachments/files/18160114/fmd.log)

https://github.com/user-attachments/assets/cc1a10a9-b432-48d3-b53a-239143058ad3

**Comment by Slasar41** [comment]
You still haven't do this: `Options -> Websites -> Modules`

**Comment by Salathorn** [comment]
[fmd.log](https://github.com/user-attachments/files/18160477/fmd.log)
My bad, didnt saw the message under picture. But its still same.

https://github.com/user-attachments/assets/eeb1e3e8-462e-4867-8b1a-56ecd7d191e5

**Comment by Slasar41** [comment]
Something is broken with getting the module.
Try extract new fmd to another folder like in D:.

**Comment by Salathorn** [comment]
.... Damn.... Changing location fixed my problem :D Now I can see modules. Im trying to fix this for 3 days and failed all times. 
My folder has non english letter "ı", ("i" without dot). Probably its because of that. 
Thanks a lot mate...
