### ISSUE TITLE
[bug-website module] mgeko keep changing between .com and .cc

### ISSUE THREAD

**Issue by Qizmo** [dazedcat19/FMD#1906]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Home 22H2

### Describe the bug

When downloading, the site sometimes download from mgeko.com while other download from mgeko.cc
If it is download from .cc there is no problem as every chapter is download correctly.
However if it is download from .com every chapters will combine into 1 chapter with the name "%CHAPTER%". So I have to go to manga info and change from .com to .cc so that I can download all the chapter correctly.
Can this be fixed?

**Comment by Slasar41** [comment]
Where do you get .com url?

**Comment by Qizmo** [comment]
It change by itself. 

When I put it up for download I put in as .cc, however when it is downloaded it keep changing between .cc and .com
If it should download from .com, the whole list of auto download will be from .com
If it should download as .cc , the whole list will be downloaded as .cc
This can continue for the whole day (like the next few auto download will also be like this)
![Delete1](https://github.com/user-attachments/assets/ffbc6dfa-8c9c-4d97-bcce-628f2b79674e)
Their website also different. From this picture it download as mgeko and the download page on the right doesn't have chapter listed, also it can only goes up to 50

![Delete2](https://github.com/user-attachments/assets/9939ce6c-c916-4da1-bf00-6872be17cbdc)
When it is correct it's website change to mangageko and info page show every chapter with chapter number listed down correctly

I didn't do anything to the FMD file at all. It keep changing by itself.

**Comment by Qizmo** [comment]
I'm not sure it is affected in this 
FMD2/lua/modules/Mangageko
or not. It's inside at moment is 

function Init()
	local m = NewWebsiteModule()
	m.ID                         = 'd297f1eb6b784ded9b50d3b85cee5276'
	m.Name                       = 'Mgeko'
	m.RootURL                    = 'https://www.mgeko.com'
	m.Category                   = 'English'
	m.OnGetDirectoryPageNumber   = 'GetDirectoryPageNumber'
	m.OnGetNameAndLink           = 'GetNameAndLink'
	m.OnGetInfo                  = 'GetInfo'
	m.OnGetPageNumber            = 'GetPageNumber'
	m.SortedList                 = true

I will look at it again when the auto download is loaded from mgeko.cc, whether there is a change in this file or not.

**Comment by Slasar41** [comment]
Why do you have the .com module?
It should only have one module named `lua\modules\MReader.lua` and that have .cc url.

**Comment by Qizmo** [comment]
Ah! So that's why. Thank you very much. Yes, this is really the problem. After deleting Mangageko.lua now my FMD is downloading from mgeko.cc like normal.

PS. I don't know why I got this module too. I download everything like everyone else since I don't know anything about all these IT stuff (only know how to use it lol) I don't even know that there is another MReader.lua file for mgeko.
