### ISSUE TITLE
[bug-website module] batotoo and mirror module sites are not working

### ISSUE THREAD

**Issue by salomone-ctrl** [dazedcat19/FMD#1907]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10

### Describe the bug

This bug started today, when you try to view the chapter in FMD it's empty without any cover or chapters structure list.
Checking the list of your favorites shows 0 chapters now to marked works.
Yesterday it worked fine.
I tried to input cookie fvt in advanced setting manually but it just goes back to some default number one where I see that it has different number now than one on the said website.

### Log

14:16:43:592 WebsiteBypass[cloudflare]: no Cloudflare solution found!
https://batotoo.com/series/172024/heart-of-thorns

**Comment by Slasar41** [comment]
Doing cookies workaround works fine here.
![image](https://github.com/user-attachments/assets/17b26e7b-d29e-45b1-a2fa-13f227c39a42)

**Comment by salomone-ctrl** [comment]
Honestly I don't know what I'm doing wrong.
I'm using Firefox newest version, worked fine till yesterday, now I only see blank page.
![3](https://github.com/user-attachments/assets/185a7533-893c-4574-ba7f-80a847982d93)
I cleared all old cookies from browser cache, accessed the site, i got new number and in advanced FMD setting I put newest cookie number I got today.
![1](https://github.com/user-attachments/assets/244fbd6b-558d-4e9f-939a-20dc581a2384)
But after checking it reverts automatically to old cookie number and shows null chapters.
![2](https://github.com/user-attachments/assets/298826a1-5d21-471d-a4c6-441c501d1901)

**Comment by salomone-ctrl** [comment]
Reinstalled Firefox, gone to all bato sites to get new cookies, installed new FMD, just imported favorites from old FDM one, and surprisingly it worked again for all bato mirror sites. 
Strange, I honestly don't know why it didn't work and why it works again.
Case closed.
