### ISSUE TITLE
[bug-website module] Neox Scans not Finding chapters.

### ISSUE THREAD

**Issue by ayanamichie** [dazedcat19/FMD#726]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Can't find chapters and updates, possible download too.

**Additional context**
here is the link [Neox Scans](https://neoxscans.net/manga/release-that-witch) what i was looking for, you can acess it in the site, but FMD2 is not finding chapters.

**Comment by Trollam** [comment]
The issue come from Cloudflare:
```
12:03:32:913 ERROR: WebsitBypass[cloudflare]: Cloudflare has blocked this request (Code 1020 Detected)
https://neoxscans.net/manga/release-that-witch

12:03:33:007 ERROR: WebsitBypass[cloudflare]: Cloudflare has blocked this request (Code 1020 Detected)
https://neoxscans.net/manga/release-that-witchajax/chapters

12:03:33:085 ERROR: WebsitBypass[cloudflare]: Cloudflare has blocked this request (Code 1020 Detected)
https://neoxscans.net/wp-admin/admin-ajax.php
```

For this website Cloudflare do not use the cookies, so the workaround will not work.

**Comment by Slasar41** [comment]
It's working just fine now.
