### ISSUE TITLE
[bug-website module] MangaDex seems broken again(?)

### ISSUE THREAD

**Issue by God-damnit-all** [dazedcat19/FMD#727]
**Prerequisite**
- [Y] I'm using the latest version.
- [Y] All website modules are up to date.
- [Y] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Upon trying to get any manga info with MangaDex:

![image](https://user-images.githubusercontent.com/53661808/133473589-6c92d906-80c5-413f-bf13-4f341272174b.png)

This started just a couple days ago. I figured a module fix was inbound so I waited. I'm a little concerned that no one else has filed an issue about it, could it just be me somehow?

**Log**
```
=== Log Session Started at 2021-09-15 11:37:45 by Free Manga Downloader ===
11:37:45:915 INFO: "Free Manga Downloader" started [PID:22332]
11:37:45:915 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.31.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 19043
               FPC Version       : 3.3.1
               LCL Version       : 2.1.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2021/03/21 14:33:22
               Path              : D:\FMD2\fmd.exe
               Process ID        : 22332
               MainThread ID     : 25192
11:38:00:766 INFO: MangaDex: Legacy ID Mapping has been executed. The new ID is: 
11:38:01:875 EXCEPTION: LUA>DoGetInfo("MangaDex.lua")> LuaCallFunction("GetInfo") LUA_ERRRUN: D:\FMD2\lua\modules\MangaDex.lua:251: attempt to perform arithmetic on a nil value
```

**Comment by hypomaniak** [comment]
No problems on my side.

I checked my mapping, I have at least 1 link in common with yours and it works, but I notice you have that one 6 times and empty in your file.
Your file:
26293;

Mine:
26293;5a90308a-8b12-4a4d-9c6d-2487028fe319

**Comment by God-damnit-all** [comment]
> No problems on my side.
> 
> I checked my mapping, I have at least 1 link in common with yours and it works, but I notice you have that one 6 times and empty in your file.
> Your file:
> 26293;
> 
> Mine:
> 26293;5a90308a-8b12-4a4d-9c6d-2487028fe319

Thanks for the insight. It looks like the database for it got corrupted somehow. I redownloaded the manga list from the server and it works fine now.
