### ISSUE TITLE
[bug-website module] Blogtruyen doesn't view manga list

### ISSUE THREAD

**Issue by xike-hub** [dazedcat19/FMD#732]
Prerequisite

    I'm using the latest version.
    [x ] All website modules are up to date.

    This is not temporary server issue.

System information
Windows 10

Describe the bug
Getting Pop-up error - Failed to finish: BlogTruyen: 404 Not Found

To Reproduce

    Go to 'Manga Info'
    Click on 'BlogTruyen' to view manga list
    Click on 'Do you want to download manga list from the server'
    See error

Expected behavior
To view then download the list

Screenshots
![image](https://user-images.githubusercontent.com/8916625/134170791-0fbc9eae-6deb-4461-bda8-6b1a2263c63b.png)

**Comment by Trollam** [comment]
You can access the manga list by declining the downloading of the list from the server.
After that you should do the action 'Update manga list'
![image](https://user-images.githubusercontent.com/12254735/134411485-80653cf8-59ec-42e7-b7d9-a80194edbf7b.png)
It is slow but it work.
