### ISSUE TITLE
[bug-website module] Can't see manga info Mangadex

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#733]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7-64 bit system

### Describe the bug

When I click a manga, says cannot get manga info.

![image](https://user-images.githubusercontent.com/24958560/134312426-ab843d66-6c56-4eb6-b387-d21096b36de1.png)

**Comment by Slasar41** [comment]
Redownload the manga list from server.
