### ISSUE TITLE
[bug-website module] Toonily age-check bypass not working

### ISSUE THREAD

**Issue by otakuakiba** [dazedcat19/FMD#736]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7

### Describe the bug

Toonily working fine until yesterday. i'm not sure if its vpn/proxy issues on my part, i already tried to work-around the location  of my vpn, but still failed to show chapter list.

sorry to bother you, but i hope you wouldn't mind to check them.
and sorry for my engrish.
thanks in advance

**Comment by otakuakiba** [comment]
seems like i already found the solution. usually if i want to download the latest chapter i go from the list at downloaded manga/manhwa and "view manga info". but somehow now fmd failed to show chapter list. after i add/put "**/**" at the rear of url page of manga/manhwa. now its working
anyway thanks for keep to maintain/develop the program.
i use fmd since the first/original developer era, akarin.
should i "close issue" myself?

**Comment by Slasar41** [comment]
Nice you got it resolved.
Unfortunatelly there's no active main dev right now and more websites became broken as the main app need to be fixed (cloudflare issue).
