### ISSUE TITLE
[bug-website module] mangasushi.net dont redirct to new links

### ISSUE THREAD

**Issue by alzamer2** [dazedcat19/FMD#745]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

win11 pro 22463.10000 x64

### Describe the bug

old links that have already been added to the program only load manga description (Title,Author,Artist,Genre,Status,Summary, cover) load correctly but the chapter list don't load
for example : if you already added manga 
100-nin no Eiyuu o Sodateta Saikyou Yogensha wa, Boukensha ni Natte mo Sekaijuu no Deshi kara Shitawarete Masu
the list will load 
https://mangasushi.net/manga/100-nin-no-eiyuu-o-sodateta-saikyou-yogensha-wa-boukensha-ni-natte-mo-sekaijuu-no-deshi-kara-shitawarete-masu/
with description +cover without chapter list

while it should redirect to the new link
https://mangasushi.net/manga/100-nin-no-eiyuu-o-sodateta-saikyou-yogensha-wa-boukensha-ni-natte-mo-sekaijuu-no-deshi-kara-shitawarete-masu-1901/

### Log

no log as the program don't consider it as error
and no page source as the lua code work with redirected page

**Comment by Slasar41** [comment]
I think the solution is to just use the new url.
Create a new manga list (not download from server) and if you already have saved favorites then change the urls in the favorites database.
