### ISSUE TITLE
[bug] I get alerts about missing libgcc_s_dw2-1.dll (X2), but FMD2 starts

### ISSUE THREAD

**Issue by Baltazar500** [dazedcat19/FMD#755]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win 7 x64 SP1

**Describe the bug**
I get alerts about missing libgcc_s_dw2-1.dll (X2), but FMD2 starts

**To Reproduce**
1. Download, unpack fmd_2.0.31.0_i386-win32.7z and start FMD2 
2. Update modules
3. Restart

**Expected behavior**
No errors at start

**Screenshots**
![SNAGIT_2021 10 06_18 40 42_0034](https://user-images.githubusercontent.com/12525093/136171736-41a473e7-2ee2-40ae-a835-905c32840804.jpg)

**Comment by Slasar41** [comment]
Try download [this](https://github.com/dazedcat19/FMD2/blob/master/dist/i386-win32/libwebp.dll) and replace it to your FMD 32bit folder.

**Comment by Baltazar500** [comment]
libwebp.dll? Not libgcc_s_dw2-1.dll? It didn't work. After replacing the dll, I got the same error as in #756 (before that FDM started after messages about "libgcc_s_dw2-1.dll", but now it won't start)

![SNAGIT_2021 10 09_13 30 45_0038](https://user-images.githubusercontent.com/12525093/136643209-0e74ba38-e570-4af6-9cb5-0d72c4c83d3b.jpg)

**Comment by Slasar41** [comment]
So by having the latest version of that file will make FMD 32 bit can't be opened at all.
I don't know how to solve this. The file has been compiled by someone else.

**Comment by Inareous** [comment]
could you try with this? [libwebp.zip](https://github.com/dazedcat19/FMD2/files/7317040/libwebp.zip)

It's made with microsoft c++ compiler instead of gcc (because honestly, I forgot how to do it using gcc), and linked against vc runtime and ucrtbase so you might still need vc++ redistributable 2015 or above.

**Comment by Baltazar500** [comment]
By checking the module files, I found the source of the problem - the MangaPlus.lua module (it was loaded at startup like 209 more modules). After removing it, the error did not appear

**Comment by Inareous** [comment]
https://github.com/dazedcat19/FMD2/blob/master/dist/i386-win32/pb.dll seems to be the problem then. Well both linked to libgcc_s_dw2-1.dll so I'll have to recompile all later @Slasar41 .

**Comment by Slasar41** [comment]
Yeah, if the updated version doesn't cause any issue again on OP system then I'll make a new FMD build.
The issue seems to affect only 32 bit version.

**Comment by Slasar41** [comment]
@Baltazar500 Try this release:
[fmd_2.0.32.0_i386-win32.zip](https://github.com/dazedcat19/FMD2/files/7341733/fmd_2.0.32.0_i386-win32.zip)

**Comment by Baltazar500** [comment]
@Slasar41, Works without errors even with the MangaPlus.lua module in the modules folder, but also does not load the page as well as the build fmd_2.0.32.0_x86_64-win64 https://github.com/dazedcat19/FMD2/issues/756#issuecomment-940027473
