### ISSUE TITLE
[bug] x86-64 version does not work due to "Cannot load WebP codec library" error, although libwebp.dll is in place

### ISSUE THREAD

**Issue by Baltazar500** [dazedcat19/FMD#756]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Win 7 x64 SP1

**Describe the bug**
x86-64 version does not work due to "Cannot load WebP codec library" error, although libwebp.dll is in place

**To Reproduce**
1. Download, unpack fmd_2.0.31.0_x86_64-win64.7z and start FMD2
2. See error

**Expected behavior**
Run the program without errors

**Screenshots**
![SNAGIT_2021 10 06_18 40 17_0033](https://user-images.githubusercontent.com/12525093/136172313-f50fb01e-16f0-4bfc-8579-5e39745e3bea.jpg)

**Comment by Slasar41** [comment]
Download [this](https://github.com/dazedcat19/FMD2/blob/master/dist/x86_64-win64/libwebp.dll) and replace it to your FMD folder.

**Comment by Baltazar500** [comment]
@Slasar41
>Download this and replace it to your FMD folder.

Thank you, it worked

**Comment by Baltazar500** [comment]
Should I close the ISSUE? Will the dll be replaced in the next release?

**Comment by Slasar41** [comment]
Yeah I'll make a new build later.
Could you test it before I push the update for all users?

**Comment by Baltazar500** [comment]
>Could you test it before I push the update for all users?

OK. Attach the archive with the new release in this thread;)

**Comment by Slasar41** [comment]
Here:
[fmd_2.0.32.0_x86_64-win64.zip](https://github.com/dazedcat19/FMD2/files/7316212/fmd_2.0.32.0_x86_64-win64.zip)
Test it with a few websites.

**Comment by Baltazar500** [comment]
On version fmd_2.0.32.0_x86_64-win64 nothing is loaded from the attachment (all modules are loaded), version fmd_2.0.31.0_i386-win32 from releases successfully loads everything

https://mintmanga.live/dorohedoro__A201cc7
https://readmanga.live/van_pis__A5327
![001](https://user-images.githubusercontent.com/12525093/136797566-f25a5f1a-5a03-44e3-a0e6-478d8f4322d2.jpg)
![002](https://user-images.githubusercontent.com/12525093/136797930-6ea9884c-5306-4399-a33a-5197731f385f.jpg)
![003](https://user-images.githubusercontent.com/12525093/136797646-80167bff-2ee9-461b-9f07-0267cf1c0c42.jpg)
![004](https://user-images.githubusercontent.com/12525093/136797672-6de997a0-6689-4ff9-b285-f631deb9d10c.jpg)

**Comment by Slasar41** [comment]
You're right.
Looks like because I use the latest version for all of the components.
I need to track down the issue and downgrade the problematic component.
