### ISSUE TITLE
[bug] Manga missing Asurascans.com

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#760]
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 7-64 bit
**Describe the bug**
The manga "The constellation that returned from hell" is missing from FMD asurascans. The manga is active on the site though.
https://www.asurascans.com/comics/the-constellation-that-returned-from-hell/

I updated the manga list and it's still missing.

**Comment by Slasar41** [comment]
I've updated the manga list database, you can download from server again.
