### ISSUE TITLE
[website module request] Dragon Tea

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#779]
**Website Information**
* Name: Dragon Tea
* Root URL: https://dragontea.ink/
* Directory list URL: https://dragontea.ink/novel/

* Example manga info URL: https://dragontea.ink/novel/my-sister-is-a-superstar/
* Example chapter URL: https://dragontea.ink/novel/my-sister-is-a-superstar/chapter-2/

**Languages**
English

**Comment by jillybeans** [comment]
still hoping for this to work on fmd
