### ISSUE TITLE
[bug-website module] kirishimafansub

### ISSUE THREAD

**Issue by Lenoyr** [dazedcat19/FMD#780]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 PRO 21H1

### Describe the bug

Name: kirishimafansub
Root URL:  https://www.kirishimafansub.net/
Updated Directory list URL:  https://www.kirishimafansub.net/reader/manga/
Olded Directory list URL:         https://kirishimafansub.net/lector/series/

Example of new manga info URL: https://www.kirishimafansub.net/reader/manga/komisan-wa-c0myush0u-d3su
Example of old manga info URL : https://kirishimafansub.net/lector/series/komisan_wa_komyushou_desu/

**Comment by Slasar41** [comment]
What's wrong?
It's working fine.
![image](https://user-images.githubusercontent.com/28888646/139737440-dfc5db17-3bc0-49d4-8d17-4c89ebcb72e6.png)

**Comment by Lenoyr** [comment]
Title information and chapters in N/A
![image](https://user-images.githubusercontent.com/65477084/139843593-035d8865-2cf1-44b4-b041-9c49ab3a7841.png)

**Comment by Slasar41** [comment]
The manga list database need to be updated.
You need to copy the link from browser and paste it into FMD for now.
