### ISSUE TITLE
[bug-website module] Flame Scans

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [dazedcat19/FMD#781]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

There are 12 series on this platform that have a special naming system; they are the following:
- A Returner's Magic should be Special
- Dungeon Reset
- Hero has Returned
- Jungle Juice
- Konjiki no Wordmaster
- Peerless Dad
- Skeleton Soldier couldn't protect the Dungeon
- Solo Leveling
- The Legendary Moonlight Sculptor
- The Villainess is a Marionette
- Trapped in a Webnovel as a Good-for-Nothing
- Trinity Seven – The 7 Magicians

The issue here is that their series link follows the usual https://flamescans.org/series/ pattern, but when it comes to the part of the series name, it gets appended a seemingly random 10-digit number at the start that changes every few hours (but all series seem to get the same one, it seems to be increasing, and I have the hunch that it's a consistent addition).
If you try an old link with a browser, it gets redirected to the new one, but if you have a countermeasure against broken links (like a wayback machine extension), it still flags it as broken; however, FMD2 just receives the broken flag and shows an empty chapter list (and the series title becomes N/A in the series list).

As an example, what around half a day ago were these links:
- https://flamescans.org/series/1635631321-a-returners-magic-should-be-special/
- https://flamescans.org/series/1635631321-skeleton-soldier-couldnt-protect-the-dungeon/
- https://flamescans.org/series/1635631321-trinity-seven/

are currently:
- https://flamescans.org/series/1635674521-a-returners-magic-should-be-special/
- https://flamescans.org/series/1635674521-skeleton-soldier-couldnt-protect-the-dungeon/
- https://flamescans.org/series/1635674521-trinity-seven/

I'll try to check in a couple hours if the difference between numbers in the next batch is still 43200.

**Comment by l-l-l-l-l-l** [comment]
The current prefix is 1635760922, after two refreshes, so it's a difference of 86401. This means that the prefix changes half a day by adding a value of usually 43200, but sometimes 43201. That, or the value added to the prefix grows by 1 every few updates.

**Comment by l-l-l-l-l-l** [comment]
It's now 1635804121, which returns us to the "21" at the end by adding just 43199.

**Comment by Trollam** [comment]
I'm not sure if it will work in FMD, but in the browser if we remove the numbers in the url we are redirected directly to the correct url without any javascript.
Exemple : https://flamescans.org/series/a-returners-magic-should-be-special/

**Comment by Trollam** [comment]
I tried something and I think it's working, but I prefer to have some testing done before pushing so here is the modified lua file.
[MangaShiro.txt](https://github.com/dazedcat19/FMD2/files/7463721/MangaShiro.txt)
Change the file extension to .txt (GitHub don't allow me to upload lua file)
And place it in "lua/modules".

**Comment by l-l-l-l-l-l** [comment]
Thanks, it seems to work.
