### ISSUE TITLE
[bug-website module] manhwa18.com become manhwa18.net

### ISSUE THREAD

**Issue by alisanbox** [dazedcat19/FMD#783]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 20h2 x64

### Describe the bug

manhwa18.com become manhwa18.net
when trying to download, LOG says

### Log

00:30:36:928 ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://manhwa18.net/manga-silent-war.html
00:30:38:319 ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://manhwa18.net/manga-silent-war.html
00:30:39:778 ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://manhwa18.net/manga-silent-war.html
00:30:41:258 ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://manhwa18.net/manga-silent-war.html
00:30:42:645 ERROR: WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://manhwa18.net/manga-silent-war.html

**Comment by Slasar41** [comment]
Looks like we need to remove manhwa18.com.
manhwa18.net works fine with cookies workaround.
Do you know how to do it?

**Comment by alisanbox** [comment]
> Looks like we need to remove manhwa18.com. manhwa18.net works fine with cookies workaround. Do you know how to do it?

do you mean, log in at manhwa18.net, then copy paste cookies "PHPSESSID">content to FMD > Option >advanced ?
i tried there, but it didn't work, cookies in the black bar, please teach me if i'm wron
![Image 3](https://user-images.githubusercontent.com/42301898/139798898-a07633ec-1126-4f0e-8b01-d4dac8324831.png)
![Image 2](https://user-images.githubusercontent.com/42301898/139798907-36c13fbc-eaee-45f0-8424-c327bc69a30f.png)
g

**Comment by darkflee** [comment]
same happened to me

> Looks like we need to remove manhwa18.com. manhwa18.net works fine with cookies workaround. Do you know how to do it?

actually manhwa18.net get error on mine as well
i do the cookies n useragent but still N/A
if i'm not do the advanced it's always looping loading without ending bcs failed solve cloud challange
even using proxy or ssh or vpn doesnt attach it as well, i'm try using diff browser that's still the same
it's my ss 
![Screenshot 2021-11-03 042925](https://user-images.githubusercontent.com/89280778/139954703-56c2b8b5-33f2-4066-9c33-606f9c69985e.jpg)

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/commit/9d8dde2a5d320abbe5575425db06f0ef4301515e
