### ISSUE TITLE
[bug-website module] 

### ISSUE THREAD

**Issue by siroarer** [dazedcat19/FMD#793]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10

### Describe the bug

i am not sure if this the right directory to report the issue. i am not familiar enough with term used in internet. i just want to say that several days ago manhwa18.com is under construction and now it's back. i used to be using proxy to open and download manhwa and manga from there. i try to download again few hours ago and failed. sorry for my english. is there a forum where fmd user speak in indonesia? btw anybody can help me step by step setting using workaround (bypass cloud flare)? It will be good if the tutorial is written or spoken in indonesian. i upload the image of error downloaded task below (most bottom). thanks a lot fmd team and anybody who help to improve this software.

### Log

![fmd rep](https://user-images.githubusercontent.com/36293851/140607278-110f6c63-53b2-4da5-ae8a-8a74af31822c.png)

**Comment by Slasar41** [comment]
This shouldn't be an issue anymore.
