### ISSUE TITLE
[bug-website module] welovemanga site change

### ISSUE THREAD

**Issue by masaton6** [dazedcat19/FMD#802]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 x64

### Describe the bug

welovemanga.net seems change the web site structure and that causing below issues (it was working till last week).

1. Download manga list from server doesn't work (can't get a list with all mangas)

2. Can't get manga info
    e.g. each manga URL used to be https://welovemanga.net/40/ but now it is like https://welovemanga.net/luvmg-40/ and even put this URL, manga info is not shown

3. New chapter check doesn't work.

Please help for welovemanga issue.

**Comment by TienVer** [comment]
Even the chapters' URL scheme has changed.

Series page = https://welovemanga.net/luvmg-2281/
Individual chapter = https://welovemanga.net/rcluv-2281/68704/

EDIT: downloads are working again today; the site had been malfunctioning for almost a half-week (recent updates page and chapters only visible as blank pages, etc), but it seems the site owner has finally come around to fixing it this morning.

**Comment by masaton6** [comment]
Hi TienVer,

Thank you for checking.
I can see the issue resolved myself as well.
