### ISSUE TITLE
[CONVERTER] I cant import Favorites Databse from v. 0.9.161.0

### ISSUE THREAD

**Issue by joewono2011** [dazedcat19/FMD#803]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
I Was downloaded Converter File , which is provided by this website
And extract to old FMD Folder
When I run this program, there's an Error "syntax error"

Even if its error, Converted Folder was created
And I copy+paste to New FMD Folder
and nothing happened to New FMD 

Result = I cant import my favorites database of Old FMD to new FMD
"sorry for my bad english

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by joewono2011** [comment]
"
![image](https://user-images.githubusercontent.com/25032354/141410185-72af8d08-ee78-4704-aa74-9da09ed7264b.png)

**Comment by Slasar41** [comment]
Your FMD is too old.
- Download the latest version of FMD1 from [here](https://github.com/fmd-project-team/FMD/releases).
- Copy `config` and `works` folder from old FMD to FMD1 folder.
- Then run the converter in FMD1 folder.

**Comment by joewono2011** [comment]
> 
> 
> Your FMD is too old.
> 
>     * Download the latest version of FMD1 from [here](https://github.com/fmd-project-team/FMD/releases).
> 
>     * Copy `config` and `works` folder from old FMD to FMD1 folder.
> 
>     * Then run the converter in FMD1 folder.

okay thanks
thats working on me

thanks so much
