### ISSUE TITLE
[bug] Can't update MangaDex list

### ISSUE THREAD

**Issue by fahmyrm** [dazedcat19/FMD#804]
**Prerequisite**
✅ I'm using the latest version (2.0.31.0).
✅ All website modules are up to date.
✅ This is not temporary server issue.

**System information**
Windows 10 x64.

**Describe the bug**
After I finish updating MangaDex list, not a single new manga appeared.

**To Reproduce**
1. Go to `Manga Info` tab and pick MangaDex on the list
2. Click on `Update manga list`
![image](https://user-images.githubusercontent.com/4697451/141603550-6dc58638-1cff-4ad4-bbc7-f071e74b9137.png)
3. Wait for the update to finish 
![image](https://user-images.githubusercontent.com/4697451/141603537-4a9b6301-d87c-4fa6-85f5-a8af9bdfe213.png)
4. Not a single new manga appeared, and I can't find the manga I want to download. Example: [Tenkosaki](https://mangadex.org/title/7873dd0e-131f-4f40-8a92-32601713e1da/tenkosaki-the-neat-and-pretty-girl-at-my-new-school-is-a-childhood-friend-of-mine-who-i-thought-was-a-boy)
![image](https://user-images.githubusercontent.com/4697451/141603633-7ae42b60-551f-4efc-9604-7294c3d57fea.png)

**Expected behavior**
The list is updated with new manga.

**Screenshots**
Already included above.

**Additional context**
- This was already happening since a few weeks ago.
- Other sites can update just fine. 
- I can download existing manga from MangaDex just fine.

Is this really a bug or am I just doing something wrong? 😅

**Comment by fahmyrm** [comment]
For anyone else having this issue, I managed to solve it by directly modifying the lua file.

So in `MangaDex.lua`, there is this code around line 116:
```
local results for results in x.XPath('json(*).results()').Get() do
  LINKS.Add('title/' .. x.XPathString('data/id', results))
  NAMES.Add(x.XPathString('data/attributes/title/en', results))
end
```
Replace it with:
```
local mangadata for mangadata in x.XPath('json(*).data()').Get() do
  local mangaid = x.XPathString('id', mangadata)
  local mangatitle = x.XPathString('attributes/title/en', mangadata)
							
  LINKS.Add('title/' .. mangaid)
  NAMES.Add(mangatitle)
end
```

This fix the issue because now the code will parse the response correctly. The response itself look like this:
![image](https://user-images.githubusercontent.com/4697451/144582547-ac7ed841-611a-4c72-b03b-2ce367195be0.png)

I probably should make a PR for this, but since there is no other thread talking about this and this thread didn't get any traction, maybe it's just me who get a different response from MangaDex? It couldn't be no one else actually ever update their MangaDex list right? 😅

**Comment by hjp78** [comment]
Thanks, I had this problem too. Now the list is finally updating

**Comment by Slasar41** [comment]
@fahmyrm Do you want to create a PR?
I'll accept it.

**Comment by fahmyrm** [comment]
@Slasar41 I tried for a bit and was confused with GitHub layout lol (I usually use GitLab). I think it'd be faster if you just fix it directly.
