### ISSUE TITLE
[feature request] Mass change path of current mapped favorites

### ISSUE THREAD

**Issue by xx255q** [dazedcat19/FMD#805]
**Is your feature request related to a problem? Please describe.**

I want to change the location my current favorites are mapped to but since I have a few hundred it would take a good deal of time to switch the path

**Describe the solution you'd like**
A button that changes the current path of all existing favorites to new location

ex:

current: \\Server1\Manga\(comic)

Change all favorites to

New: \\Server2\Manga\(comic)

**Describe alternatives you've considered**
Manually change each one

**Additional context**

**Comment by Slasar41** [comment]
Select all the entries, right click and then select "Change "Save to"".
