### ISSUE TITLE
[bug-website module] manga-raw.club not downloading anything from fmd

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#811]
**Prerequisite**
I'm using the latest version.
 All website modules are up to date.
I Check the website first with browser and everything seems fine
This is not temporary server issue.

**Describe the bug**
fmd isnt downloading mangas from manga-raw.club even with work around. it worked in the afternoon but it stopped working now

https://www.manga-raw.club/manga/supreme-spirit-master/

**Comment by xx255q** [comment]
All my bookmarks/downloads for this site failed starting this morning
