### ISSUE TITLE
[website module request] Bato.to

### ISSUE THREAD

**Issue by adesetia** [dazedcat19/FMD#818]
**Website Information**
* **Name:** Bato.to
* **Root URL:**https://batotoo.com
* **Directory list URL:**https://batotoo.com/browse

* **Example manga info URL:**https://batotoo.com/series/95521/lillien-of-turin
* **Example chapter URL:**https://batotoo.com/chapter/1802754

**Languages**
Indonesia

**Comment by Slasar41** [comment]
Already supported.
