### ISSUE TITLE
[bug-website module] fmd not downloading anything from asurascans.com

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#829]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

fmd isnt downloading mangas from asurascans even with work around. it worked in the afternoon but it stopped working now. i get info just when it comes to the download i get nothing or it fails

https://www.asurascans.com/comics/worn-and-torn-newbie/

**Comment by Qizmo** [comment]
Same, can't load from asura too.

**Comment by hesoyamma785** [comment]
same here

**Comment by Qizmo** [comment]
Hi, NercCode, I got a silly question please. How do I make use of these Update MangaShiro.lua? I have never done this before.

Sorry for not replying to your message above, I can't find function to answer to a person above. Only see this "Comment" to the post itself.

**Comment by NecrCode** [comment]
[MangaShiro.zip](https://github.com/dazedcat19/FMD2/files/7697125/MangaShiro.zip)
Hi Qizmo, download this, extract it, then copy MangaShiro.lua to lua/modules. hope that helps.

as for the update is yet to be approved by the repository owner, so there is nothing we can do about it.
