### ISSUE TITLE
[bug-mangacrab module] mangacrab

### ISSUE THREAD

**Issue by djgerman10** [dazedcat19/FMD#831]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Enterprice LTSC

### Describe the bug

When downloading a manga this manga "NA".
That is the bug, it does not download with the name of the manga and all the manga go to the same folder.

Excuse my English, greetings from Argentina

![all the manga downloaded from the web end up having the name "NA"](https://user-images.githubusercontent.com/48584512/145325581-aa54e13c-2534-48d5-abe9-9b584b3c4336.png)

### Log

[https://mangacrab.com/manga/mi-hija-es-una-genia-musical/](https://mangacrab.com/manga/mi-hija-es-una-genia-musical/)

[https://mangacrab.com/manga/a-partir-del-dia-de-hoy-trabajare-como-un-senor-de-la-ciudad-2/](https://mangacrab.com/manga/a-partir-del-dia-de-hoy-trabajare-como-un-senor-de-la-ciudad-2/)

**Comment by Slasar41** [comment]
Fixed https://github.com/dazedcat19/FMD2/commit/d0ccd7a5d2ae5cf2408089bfe83970ba832f6af3.
