### ISSUE TITLE
[feature request] manga folder is named by id

### ISSUE THREAD

**Issue by gcfvfhg** [dazedcat19/FMD#834]
I hope to add the function of naming with id

![sdf](https://user-images.githubusercontent.com/77856066/145670934-c4e3d0a7-59ca-4f9e-a54e-65afca492012.png)

example
https://batotoo.com/series/90121
Its folder name is 90121

My trouble is similar to the issue below
 I have two mangas that share a name 
https://github.com/dazedcat19/FMD2/issues/270

My English is not good, please understand

**Comment by Slasar41** [comment]
Which other manga that share the same title?

**Comment by gcfvfhg** [comment]
ex:
https://batotoo.com/series/14035/dragon-sister
https://batotoo.com/series/14976/dragon-sister

There are many other examples

so i want this feature to be added(manga folder is named by id)

**Comment by Slasar41** [comment]
But those urls have the same content.
Maybe the website owner need to clean up the duplicate titles.

If you want to add the ID number to the manga title, add this to line 38 in `Batoto.lua` file:
```
MANGAINFO.Title     = x.XPathString('//h3[contains(@class, "item-title")]/a') .. GetLanguageCodeSuffix(x.XPathString('//h3[contains(@class, "item-title")]/parent::*/em/@data-lang')) .. ' (' .. x.XPathString('//div[@class="mt-2"]/span/substring-after(.,": ")') .. ')'
```
![image](https://user-images.githubusercontent.com/28888646/154856677-df65c037-72b0-4801-8452-9d39ad93868e.png)
Note: If there will be an auto update to the file in the future, you need to re-apply the change.

**Comment by gcfvfhg** [comment]
Because the quality of the pictures provided by different uploaders will be different, I will download them all

**Comment by gcfvfhg** [comment]
If you want to add the ID number to the manga title, add this to line 38 in Batoto.lua file:

MANGAINFO.Title     = x.XPathString('//h3[contains(@class, "item-title")]/a') .. GetLanguageCodeSuffix(x.XPathString('//h3[contains(@class, "item-title")]/parent::*/em/@data-lang')) .. ' (' .. x.XPathString('//div[@class="mt-2"]/span/substring-after(.,": ")') .. ')'

manga title (id)➡️id 

i want the latter 
how to write

**Comment by Slasar41** [comment]
Remove `' (' .. ` and ` .. ')'`

**Comment by gcfvfhg** [comment]
thank you

**Comment by gcfvfhg** [comment]
@Slasar41 

Sorry to bother you.
I didn’t open a new issue because I’m not sure this is worth one.

May I ask how I could do the same thing for MangaGo?
How should I modify it?

```
For example:

https://www.mangago.me/read-manga/i_reincarnated_as_a_faint_hearted_countess/

Current title:
I Reincarnated as a Faint Hearted Countess

Change it to:
i_reincarnated_as_a_faint_hearted_countess
```

**Comment by Slasar41** [comment]
Edit line 197 to `MANGAINFO.Title     = URL:match('/([^/]+)/?$')` in `lua\modules\MangaGo.lua` file.
