### ISSUE TITLE
[bug] Flamescans - Downloads all chapters for every title update

### ISSUE THREAD

**Issue by liohunter** [dazedcat19/FMD#840]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Every time there is a chapter update for any favorite on flamescans it downloads every single chapter for the title. This doesnt happen for any other source. 

**Expected behavior**
It should just download the latest/undownloaded chapters. 

Thanks!

**Comment by Slasar41** [comment]
Have you tried to let FMD finish downloading all of them?
FMD should skip the chapters that are already been downloaded.

**Comment by liohunter** [comment]
Hi, 

It skips downloaded chapters with every other source, but its downloaded every available chapter for the Flamescans favorites for months.

**Comment by alatnet** [comment]
Have the same issue.  I believe it stems from the random number they now insert in all of their manga url's.  If you use a url that does not have a number in it, it will auto redirect to one that has a number in the url and may freak FMD out about it.
Example:
https://flamescans.org/series/a-returners-magic-should-be-special/
redirects to
https://flamescans.org/series/1639929721-a-returners-magic-should-be-special/

**Comment by Slasar41** [comment]
Looks like this fixes https://github.com/dazedcat19/FMD2/commit/c14c623e1962cc097f6185dd5babe86947268ba3 need to be applied for manga info.
Not sure if it'll fix this issue though.

**Comment by liohunter** [comment]
Unfortunately this isn't resolved yet, it still downloads all available chapters for this site and for a lot of similarly built ones like LeviatanScans, mm-scans, etc.
