### ISSUE TITLE
[website module request] scyllascans

### ISSUE THREAD

**Issue by inheritno** [dazedcat19/FMD#841]
**Website Information**
* **Name:**  ScyllaScans
* **Root URL:** https://scyllascans.org
* **Directory list URL:** https://scyllascans.org/work/all

* **Example manga info URL:** https://scyllascans.org/work/en/redline
* **Example chapter URL:** https://scyllascans.org/read/redline/en/0/3.0

**Languages**
English

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/commit/21f0b0bedeab4d48458e895befca9ab5db2ff057
