### ISSUE TITLE
[bug] Cannot download new manga from hentai2read.com

### ISSUE THREAD

**Issue by zartzaku** [dazedcat19/FMD#842]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
windows 7

**Describe the bug**
If download old manga from hentai2read.com its work, but if it new manga like https://hentai2read.com/love_sharing/ then the chapter not show, so cannot download it.

**To Reproduce**
1. try download https://hentai2read.com/love_sharing/
2. the chapter not show so cannot download

**Expected behavior**
I hope new manga ca be downloaded like old manga on hentai2read.com

**Screenshots**
![github](https://user-images.githubusercontent.com/14165907/146772965-4507cbbb-1682-47a7-b057-47f883c138a5.jpg)

**Additional context**

**Comment by Slasar41** [comment]
Are you able to read it on browser?

**Comment by zartzaku** [comment]
Yes, I can read it at firefox.
![001](https://user-images.githubusercontent.com/14165907/147053785-2bd078bc-baff-49e6-a071-700877edc0e2.jpg)
![002](https://user-images.githubusercontent.com/14165907/147053801-0a76c9b2-c123-4b81-a864-56a648a1e60d.jpg)

**Comment by Slasar41** [comment]
Do you have to be logged in to read it?
Because I don't see any chapter.

**Comment by zartzaku** [comment]
I remember that i always login to my account on hentai2read.com. so where should i put my login username and password for hentai2read on fmd.

**Comment by Slasar41** [comment]
There's no account login on FMD for hentai2read yet, someone need to implement it.
If you're already logged in on browser, you can do cookies workaround.

**Comment by zartzaku** [comment]
Can i ask how to do cookies workaround on firefox?

**Comment by Slasar41** [comment]
Open the link, press F12, refresh the page, select `Network` tab, select the first item, scroll until you see `Cookie:` and `User-Agent`, copy both of them.
Open FMD, go to Options -> Websites -> Advanced, search Hentai2Read, change `Enabled` option to `(True)`, paste to `Cookies` and `UserAgent`, remove `Cookie: ` and `User-Agent: ` text, press Apply.
![image](https://user-images.githubusercontent.com/28888646/147417784-c93505a5-a43a-40ee-a908-5c122a6eaafb.png)
