### ISSUE TITLE
[bug-website module] Mangaboss.org

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#848]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

FMD2 doesn't support mangaboss org 

### Log

https://mangaboss.org
https://mangaboss.org/manga/
https://mangaboss.org/manga/it-starts-with-a-mountain/chapter-1/
![SharedS creenshot](https://user-images.githubusercontent.com/77359705/147540121-5b517c3d-a0b4-4789-bc57-1c7cc1a0aaea.jpg)

**Comment by Slasar41** [comment]
It's not a bug, FMD just doesn't support it.
You should make a website request instead.
