### ISSUE TITLE
[website module request] mangaboss.org

### ISSUE THREAD

**Issue by hesoyamma785** [dazedcat19/FMD#851]
**Website Information**
* **Name Mangaboss:** 
* **Root URL: https://mangaboss.org/**
* **Directory list URL: https://mangaboss.org/manga/**

* **Example manga info URL: https://mangaboss.org/manga/lightning-degree-all-chapters/**
* **Example chapter URL: https://mangaboss.org/manga/lightning-degree-all-chapters/chapter-1/**

**Languages**
English

**Website relationship**
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...")

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Lenoyr** [comment]
The site has been renamed to Mangavisa.
