### ISSUE TITLE
[bug-website module] manga-raw.club is not working

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#858]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

the info doesnt load in fmd now and and no downloads. it worked this morning and afternoon. stopped working now at this time.

https://www.manga-raw.club/manga/the-dragon-slaying-knight-longs-for-a-clean-slate-after-kissing-the-evil-dragon/

**Comment by Qizmo** [comment]
Same for me. All my manga-raw are grey out....
