### ISSUE TITLE
How to export my favorites from FMD to FMD2[feature request]

### ISSUE THREAD

**Issue by DrPolash** [dazedcat19/FMD#859]
I was using FDM V1.3,3 and I want to shift from there to FMD2. 

The problem is i have 404 Favorites save to it. Re input them one by one is a big problem. 

I saw some tools to export favorites from one's FMD but right now after search a while in internet i couldn't find one with easy ones like before. 

So im asking the community as well as the dev's if there is an easy solution for my problem. 

Thanks for your time and help

**Comment by hesoyamma785** [comment]
I think they explain here
https://github.com/dazedcat19/FMD2/issues/16#issuecomment-638398784
