### ISSUE TITLE
[bug-website module] Welovemanga - URL/domain change

### ISSUE THREAD

**Issue by TienVer** [dazedcat19/FMD#873]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H2 x64

### Describe the bug

I noticed something peculiar when perusing the WLM website through its welovemanga.**net** URL: even _days_ after being uploaded, the latest updates are not added to their respective series' chapter lists (as viewed through the browser) or are discoverable through FMD2's right-click->"Check for new chapters" function in the favorites tab. FMD2 can't see them and therefore can't download them.

However, when switching to the new URL Welovemanga.**one**, those "phantom updates" correctly appear on the chapter lists (on the browser) and therefore should make themselves available for download.

Case in point: 
https://welovemanga.net/luvmg-179/ <---- Latest chapter is ch.14.2
https://welovemanga.one/luvmg-179/ <---- Latest chapter is ch.15

Could you please add welovemanga.**one** to the welovemanga/LHScans module? *.ONE is simply up to date, whereas *.NET no longer is. Thanks.

**Comment by Slasar41** [comment]
So which one is the main website, .net or .one?
Maybe the admin just forgot to update to the .net one.

**Comment by TienVer** [comment]
Maybe - or maybe welovemanga.one is still a work in progress, because it's exhibiting some curious little tweaks: for example, on the "latest updates" page (https://welovemanga.one/manga-list.html?sort=last_update), there are no longer direct links to the latest chapters, even though they are still available on https://welovemanga.net/manga-list.html?sort=last_update.

To be honest, I'm not sure what's going on with WLM/LHScans. Whoever's behind the website has been tinkering a lot with it in the past couple of months, especially the anti-DDOS system.

EDIT: now I just noticed they once again modified the URL scheme. *sigh*
https://welovemanga.one/luvmg-179/ ---> https://welovemanga.one/179/

**Comment by TienVer** [comment]
Sorry, have been away from my personal PC for a while now and got back in the saddle today.

I think it'd be better to actually consider .ONE as the **main** website now. It's been weeks since .NET no longer shows latest updates in its chapter lists, and I no longer think it's an omission...I think it got deprecated and the owner moved on to .ONE.

Case in point: Googling "WeLoveManga" returns the **.ONE** website, not the .NET. First on the results list is Weloma.art, but I'm willing to wager it's not owned by the LHScans/WLM admin and is just a copycat website - there isn't even a login button and the latest updates page is blank. WeLoveManga.ONE, on the other hand, shares the same user/login database as .NET, so that's the legit site and, from the looks of it, the main one thenceforth.

Can you please add support for the .ONE links (in the Manga Info page, for the address bar), too? The URL scheme changed a bit, omitting the rcluv- and luvmg- prefixes. For example:
Series - https://welovemanga.one/965/
Chapter - https://welovemanga.one/965/74247/

**Comment by Slasar41** [comment]
Should I add the .one as a new website or replacing the .net?
If I just replace it, then users need to readd their favorites.

**Comment by TienVer** [comment]
Is there no way to add some converter function that can turn links like _https://welovemanga.net/luvmg-179/_ into _https://welovemanga.one/179/_ or _https://welovemanga.net/rcluv-179/74408/_ into _https://welovemanga.one/179/74408/_ ?

You'll have to excuse me, as I don't know Lua and the inner workings of each module.

I do understand that replacement would foist the nuisance of manually re-favoriting [a possibly long list of] favorites to every WLM user out there (me included), but it seems to me that the *.net website has been deprecated; those latest chapter updates are still not reflected in the series' chapter lists and I don't think the webmaster has any intention of fixing that. Personally, I'd move on, but, well, I...only...have 150 WLM favorites. Others might be more annoyed than me.

At the end of the day...we should choose whichever solution is the most painless (read: least annoying or most practical) for everyone.

**Comment by Slasar41** [comment]
There's a way to convert the url (by removing like the `rcluv-`) with DB Browser, but it's still hard to do.
I think the best way is to just add the .one as a new website.
Then users can transfer the favorites from WeLoveMangaNET to WeLoveMangaONE, of course need to create the manga list first.
The transfer website feature just need to match the title name of the manga.

**Comment by TienVer** [comment]
Sounds good.

Thanks!
