### ISSUE TITLE
[bug-website module] manga-raw.club is not downloading or getting the info

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#875]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

the info loads in fmd now but no downloads. it worked this morning and afternoon. stopped working now at this time.
might be the site since it worked again previously without a fix but that took a week or so i think, but currently same issue but site works fine just not on fmd, so i dunno if that counts as temporary or if it will even fix itself again.

https://www.manga-raw.club/manga/i-ll-save-this-damn-family/

**Comment by Slasar41** [comment]
According to the log it's because of cloudflare and there's no fix yet.

**Comment by Qizmo** [comment]
Hope this get fixed soon ^^

**Comment by xx255q** [comment]
This is my main site, a fix would be great

**Comment by jillybeans** [comment]
its fixed now, the site fixed itself and it works with the work around, but you gotta re update the cookie every few min for it to work at least on my end

**Comment by jillybeans** [comment]
nvm the work around stopped working now too

**Comment by xx255q** [comment]
Still broken for me also

**Comment by jillybeans** [comment]
site has fixed itself, dont know if its temporary, but it currently works on fmd

**Comment by jillybeans** [comment]
the info loads now but no downloads
