### ISSUE TITLE
[bug-website module] Update mangahasu.se list

### ISSUE THREAD

**Issue by Souravi785** [dazedcat19/FMD#878]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7-64 bit system

### Describe the bug

The mangahasu manga list needs to be updated. It takes too long for a manual update

![image](https://user-images.githubusercontent.com/24958560/149931066-7f6ea8e8-845c-45fb-9d62-5726435e2920.png)

This is after leaving it to update for more than 2 hours. With how it's going it'll take forever to update.

**Comment by Slasar41** [comment]
You can try increasing the connection number for updating manga list.
Options -> Connections -> Misc.

And if you done, you can help uploading the updated manga list to [here](https://github.com/dazedcat19/FMD2-DB).

Edit:
I found out the chapter list is broken and already fixed it, so you need to redo the update manga list or else there will be 0 number beside the title name on the list.

**Comment by Slasar41** [comment]
I've updated the manga list to the server.
