### ISSUE TITLE
[bug] Downloads from Readcomiconline.li are failing intermittently

### ISSUE THREAD

**Issue by calex-xor** [dazedcat19/FMD#880]
**Prerequisite**
- [X] I'm using the latest version.
- [X] All website modules are up to date.

- [X] This is not temporary server issue.

**System information**
Win 8.1 x64

**Describe the bug**
After a number of downloads from the website (~30-40) without any issue, FMD suddenly becomes unable to download further comics from the website - with any further downloads repeatedly failing no matter which comic it is.
However, when I tried downloading again after a break of around 24 hours or so, FMD was once more able to download comics from the site - before the downloads once again started to fail after a number of successful attempts.

**To Reproduce**
1. Search for a comic with large number of issues (>50) under ReadComicOnline and download all of them.
2. If download is successful try with another comic with large number of issues.
3. Downloads start failing after a number of issues are downloaded.

**Expected behavior**
All the downloads should be successful as long as the issues themselves are present on the site.

**Screenshots**
![readcomiconline](https://user-images.githubusercontent.com/92451839/150099874-64feba8e-45b2-4c8c-9d4d-65846ce9579e.png)

**Additional context**
Log file - 
[fmd.log](https://github.com/dazedcat19/FMD2/files/7895819/fmd.log)

**Comment by ahmadi3d** [comment]
This happens because of the site it self, try going to "options -> websites -> advance", search for the site, and enable it, set max tax limit, max thread per task limit and max connection limit to 1
The problem occurs because the site limits your ip, in fact if you change your ip (using vpn) you can continue to download but a good way to avoid this problem is only using a single connection for download like what i described.

**Comment by calex-xor** [comment]
Trying it now but since it's downloading the pages one by one it will probably take some time to see if the issue crops up again. Will update and/or close this issue depending on the result.

Thanks.

**Comment by calex-xor** [comment]
@ahmadi3d Unfortunately, this doesn't seem to work on my end.

Even with keeping max task limit, max thread per task limit and max connection limit to 1 under ReadComicOnline and enabling it, the downloads start failing after a while

**Comment by Slasar41** [comment]
I'm able to reproduce it after reaching 60+ chapters.
Lets see if adding a delay will fix it.

**Comment by Slasar41** [comment]
Could you test it?
[ReadComicOnline.zip](https://github.com/dazedcat19/FMD2/files/7915974/ReadComicOnline.zip)

**Comment by calex-xor** [comment]
Yeah this seems to work. I tried it and the downloads have yet to fail.

**Comment by Slasar41** [comment]
I'll update it then.

**Comment by Slasar41** [comment]
Also, there's an option in websites settings to download low quality images.

**Comment by shedman214** [comment]
I have the same issue. I have followed all the steps present on this page and I still cannot download a single comic from the site. is the site blocking me? 
![image](https://user-images.githubusercontent.com/32603273/173964082-33227290-728d-4c65-866a-ee921ca5f670.png)
