### ISSUE TITLE
[bug-website module] mangadex

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#897]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

https://mangadex.org/title/1f1dbbf1-831c-40f4-b0c1-ff9a781c2987/taizi

chapter list are not showing up for download

**Comment by Slasar41** [comment]
For chapters that's from bilibili comics, you have to use bilibili url to FMD.

**Comment by jillybeans** [comment]
> 

that was a bad example, my bad even non bilibili ones arnt working

https://mangadex.org/title/d9419bf1-97f3-4fc8-a33c-6f55363047b4/the-time-of-the-terminally-ill-extra

https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere
