### ISSUE TITLE
[website module request] ManhwaIndo

### ISSUE THREAD

**Issue by Office48** [dazedcat19/FMD#898]
### Name

ManhwaIndo

### Root URL

https://manhwaindo.id/

### Directory list URL

https://manhwaindo.id/series/list-mode/

### Example manga info URL

https://manhwaindo.id/series/my-daughter-is-music-genius/

### Example chapter URL

https://manhwaindo.id/my-daughter-is-music-genius-chapter-1/

### Language

Indonesian

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/commit/c51450b882f8067d9866127dee9b49ada894dcde
