### ISSUE TITLE
[bug-website module] mangadex

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#899]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

that was my mistake the issue was closed because i used a bad example. the other comics on mangadex arnt working as well. they dont load the chapters on fmd.

https://mangadex.org/title/35b9f818-926b-4f4a-aa2b-0ac068986a73/kabushiki-gaisha-magi-lumiere

https://mangadex.org/title/d9419bf1-97f3-4fc8-a33c-6f55363047b4/the-time-of-the-terminally-ill-extra

**Comment by Slasar41** [comment]
Check your FMD settings for MangaDex language option.

**Comment by jillybeans** [comment]
> Check your FMD settings for MangaDex language option.

welp. this is embarrassing, dunno when it got changed to french from english

thank you for patience and the help
