### ISSUE TITLE
[bug-website module] manhuascan

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#905]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

it doesnt download anything

https://manhuascan.com/manga-a-cute-girl-with-bad-eyesight.html

**Comment by Slasar41** [comment]
Duplicate of https://github.com/dazedcat19/FMD2/issues/535.
