### ISSUE TITLE
[feature request]Can e-hentai login function be added?

### ISSUE THREAD

**Issue by gcfvfhg** [dazedcat19/FMD#914]
I can't access a exhentai website
can e-hentai login function be added?
![s (1)](https://user-images.githubusercontent.com/77856066/154843449-4d8ef9b9-672c-4481-a9cc-1f6e945423c6.png)

Otherwise, does the original image download function currently work? 
![s (2)](https://user-images.githubusercontent.com/77856066/154843465-84c21493-79cd-4ead-a810-461cba995c5d.png)

**Comment by Slasar41** [comment]
Not sure, you can test it by changing this option:
![image](https://user-images.githubusercontent.com/28888646/154856157-462f2c53-afae-4392-a589-c6cd4fd25818.png)

**Comment by gcfvfhg** [comment]
There is no login function for e-hentai in fmd2(only exhentai)
i can't test

If I want to download the original image, I need to log in

my English is not good 
Hope it didn't offend you

**Comment by gcfvfhg** [comment]
Can I ask another question? 

ex:https://e-hentai.org/g/1933968/c55f21432b/
manga title➡1933968-c55f21432b

I want the latter
how to write
similar to https://github.com/dazedcat19/FMD2/issues/834

**Comment by Slasar41** [comment]
I don't know how to add E-Hentai account support but I managed to let FMD download the original images.

If you use Edge/Chrome:
- Make sure you're already logged-in in the browser
- Press F12 -> select `Network` tab
- In the `Name` section, select the first one -> see `Headers` tab and search for `cookie` and `user-agent`, copy all of it
- In FMD, go to Options -> Websites -> Advanced -> E-Hentai, change `Enabled` option to `True`, paste the `cookie` and `user-agent` from browser
![image](https://user-images.githubusercontent.com/28888646/155014990-5b1b38b0-c89d-4f4c-b123-5e1f9551a5cd.png)
- Press Apply
- Move to Options tab (like in my first comment) and set it to `Original`
- Press Apply

For title, add this after line 100: `local body = HTTP.Document.ToString()`
Then add this to the end of MANGAINFO.Title: ` .. ' ' .. body:match("var gid = (.-);") .. '-' .. body:match('var token = "(.-)"')`
![image](https://user-images.githubusercontent.com/28888646/155018089-e5cadf6b-3dd7-4cb7-84d6-249edcc7fea0.png)

**Comment by gcfvfhg** [comment]
Thank you for your reply.
