### ISSUE TITLE
[bug-website module] asurascans info and download not working

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#916]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

info not loading and download not happening on fmd

https://asurascans.com/comics/47-return-of-the-disaster-class-hero/

**Comment by 7h3Cub3** [comment]
Tried to find if there was something wrong with how the LUA was loading the content, found nothing the site didn't changed, i looked at FMD log and here is the issue.

WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://asurascans.com/manga/list-mode/

Looked into a bit more and perused the issues thread and found the one talking about the firefox based webdriver to bypass CF, but it seems that in the end the new cloudflare method doesn't use the cookie method so the cookie info copy method and the webdriver method don't work either

15:53:14:086 WebsitBypass[cloudflare]: webdriver can't find cookie 'cf_clearance'
https://asurascans.com/comics/doctors-rebirth/

hopefully a fix can be made but i wonder how it can be done without those cookies, sadly my meager skills can't imagine one, good luck ! ^.^

**Comment by Slasar41** [comment]
Should be working again now.
![image](https://user-images.githubusercontent.com/28888646/193368709-b9da393f-4f57-4e0c-8fc4-c30ce51bded3.png)
