### ISSUE TITLE
[bug-website module] Hentaidexy unable to pull chapters

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD#917]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 20H2 x64

### Describe the bug

Hentaidexy has stopped pulling any chapters. It pulls cover and description only.

### Log

=== Log Session Started at 2/28/2022 19:15:36 by Free Manga Downloader ===
19:15:36:912 INFO: "Free Manga Downloader" started [PID:12468]
19:15:36:912 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 2.0.31.0
               Product Version   : Win64
               Host Machine      : Windows 10 64-bit Build 19042
               FPC Version       : 3.3.1
               LCL Version       : 2.1.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2021/03/21 14:33:22
               Path              : C:\DOS\fmd_2.0\fmd.exe
               Process ID        : 12468
               MainThread ID     : 9560
19:17:26:856 INFO: TMainForm.FormClose
19:17:26:903 VALUE: NormalExit = True
19:17:27:010 INFO: "Free Manga Downloader" exit normally [PID:12468]

**Comment by Slasar41** [comment]
Works fine on my end.
![image](https://user-images.githubusercontent.com/28888646/156239151-8371521a-2e37-40ea-ac29-78b58de332d8.png)

**Comment by molitar** [comment]
Can you tell me what the problem maybe than?  I even tried to delete all the data folder and redownload.. Not working.
