### ISSUE TITLE
[bug] IMHentai will not finish updating manga list

### ISSUE THREAD

**Issue by molitar** [dazedcat19/FMD#920]
**Prerequisite**
- [x] I'm using the latest version.
- [ ] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 20H2

**Describe the bug**
It has been stuck at the final count now for a full day.  This is my 2nd attempt.

**To Reproduce**
1. Go to 'IMHentai'
2. Click on 'Update manga list'

**Expected behavior**
Update should finish.  Screenshot shows the numbers are finished but it never finishes.

**Screenshots**
[If applicable, add screenshots to help explain your problem.
[http://prntscr.com/nSa2h-bcKlTK](http://prntscr.com/nSa2h-bcKlTK)

**Comment by Slasar41** [comment]
You need to lower the connection numbers.
I set it to 2 and it's working.
![image](https://user-images.githubusercontent.com/28888646/156942944-11ef7d79-ab17-4d14-bfb3-02513f557cb6.png)

**Comment by molitar** [comment]
I reduced it down to 2 threads and it still will not finish.  This is now over 6 attempts and I have firewall disabled and no antivirus so nothing blocking it.

![Screenshot_4](https://user-images.githubusercontent.com/16074561/156970659-cfda9398-e238-4ecb-abdc-643b5a9da0bb.jpg)
