### ISSUE TITLE
[bug-website module] yugenmangas

### ISSUE THREAD

**Issue by djgerman10** [dazedcat19/FMD#923]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Enterprice LTSC

### Describe the bug

A few days ago the yugenmangas module stopped working

![1](https://user-images.githubusercontent.com/48584512/157321155-ed1e0454-74b4-4d8c-8d81-351cfe346fec.png)

![2](https://user-images.githubusercontent.com/48584512/157321248-cf00ee27-9c9d-4274-b46a-d4275bc5e2c1.png)

### Log

https://yugenmangas.com/series/en-esta-vida-sere-la-matriarca/

**Comment by djgerman10** [comment]
still not walking

![hh](https://user-images.githubusercontent.com/48584512/158081367-047d5788-601d-46f5-96c3-dfb2590c5871.png)

**Comment by Slasar41** [comment]
If you see this screen, that means you need to do cookies workaround.
![image](https://user-images.githubusercontent.com/28888646/158084113-f3eccd84-7969-406f-b667-05b3b76611c1.png)

**Comment by exborn** [comment]
works perfectly
![Clipboard01](https://user-images.githubusercontent.com/18037700/158087685-e5c8cb6f-a546-42cd-920a-041c1a810f2a.jpg)

**Comment by exborn** [comment]
It works with the above settings and cookies. https://github.com/dazedcat19/FMD2/commit/e6c49a9be2852d7f44fdc097da7adb7520167597

You only have to reload the cookies from time to time.
