### ISSUE TITLE
[feature request] Replace the OPM version of VirtualTreeView with the one come from Lazarus itself

### ISSUE THREAD

**Issue by Kagamma** [dazedcat19/FMD#929]
**Is your feature request related to a problem? Please describe.**
Reduce 1 dependency by using the package provided by Lazarus itself. Nothing should change except we need to add 'Laz.' prefix.

Patch: [laz.virtualtreeview.zip](https://github.com/dazedcat19/FMD2/files/8239098/laz.virtualtreeview.zip)

**Comment by Kagamma** [comment]
I notice I haven't made changes to .lfm file so here's a more complete patch: [laz.virtualtreeview.zip](https://github.com/dazedcat19/FMD2/files/8241628/laz.virtualtreeview.zip)

**Comment by Slasar41** [comment]
Is this need to be changed too?
![image](https://user-images.githubusercontent.com/28888646/158241640-336cf21e-860c-4170-8be6-ffc7943f82b4.png)

**Comment by Kagamma** [comment]
The first one is just my habit, it should be omitted. Basically it tells the IDE to not save working session.
The 2nd one is useful. It sets the GDB symbols to DWARF2 which is the most stable one for debugging FPC binaries at the moment.

**Comment by Slasar41** [comment]
Okay, I'll do that.
Thanks!
