### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by thorio2002** [dazedcat19/FMD#943]
I reiterate an order already made since it has been malfunctioning for almost 1 year.

**Prerequisite**
- I'm using the latest version. (2.0.31.0 rev 5274)
- All website modules are up to date. (I have the update on automatic so it should be up to date.)
- This is not temporary server issue. (The problem takes almost a year and is changed in the structure of the page.)

**System information**
Window 10

**Describe the bug**
There was a directory change

**Name:** Knight no Fansub
Root URL: https://knightnoscanlation.com/
Directory list URL: https://knightnoscanlation.com/biblioteca/

**BEFORE**
Example manga info URL: https://knightnoscanlation.com/bl/dark-lady/
Example chapter URL: https://knightnoscanlation.com/bl/dark-lady/capitulo-122/

**AFTER**
Example manga info URL: https://knightnoscanlation.com/sr/dark-lady/
Example chapter URL: https://knightnoscanlation.com/sr/dark-lady/capitulo-122/

**Languages:**
Spanish

**Log**
No response

**Comment by djgerman10** [comment]
you didn't describe the problem. the problem is that the title appears as Title N/A, right?
![1](https://user-images.githubusercontent.com/48584512/159626896-cf408144-1049-4277-aa49-be82e7e4697b.png)

![2](https://user-images.githubusercontent.com/48584512/159626909-3a3d7e0f-0fe2-416e-92a6-ddc876bebeb9.png)

**Comment by Slasar41** [comment]
@djgerman10 How your FMD able to load the chapter list?
There's cloudflare issue on my log but I don't see cloudflare page on the browser.
![image](https://user-images.githubusercontent.com/28888646/160186311-98359d9a-3e5e-419b-87ee-ae87be80b3aa.png)

**Comment by djgerman10** [comment]
> Hay un problema de cloudflare en mi registro, pero no veo la página de cloudflare en el navegador.

I am using vpn from Germany.
thank you very much for fixing the problem
![1](https://user-images.githubusercontent.com/48584512/160226415-6b12f20f-f1c6-4b3e-b3df-f1b223ecb557.png)

**Comment by Slasar41** [comment]
> I am using vpn from Germany.

You're right, a VPN connection to Germany can be used as a workaround.

@thorio2002 Try using a VPN from Germany.

**Comment by thorio2002** [comment]
> > I am using vpn from Germany.
> 
> You're right, a VPN connection to Germany can be used as a workaround.
> 
> @thorio2002 Try using a VPN from Germany.

**that is, the suggestion is that you use a vpn?**
When I click on a manga from the list after downloading the list from the server, it doesn't show anything in the chapters part and the list starts reading N/A(0). It didn't even update before.
**which vpn do you suggest me?**

**Comment by thorio2002** [comment]
after trying a lot I was able to make a capture. to show. 
https://ibb.co/3WRz2zd
It was a pain at some point windows changed how it was done to add a more sophisticated tool that I didn't know about.

**Comment by Slasar41** [comment]
@thorio2002 I use Windscribe app.
Your screenshot indicating FMD is still blocked accessing the website.

**Comment by thorio2002** [comment]
> I use Windscribe app

ok i'll try that one, because i tried a "free" one but i can't connect through germany, only from the netherlands and the problem persists. I will report tomorrow.

**Comment by thorio2002** [comment]
> @thorio2002 I use Windscribe app. Your screenshot indicating FMD is still blocked accessing the website.

Funcionará con un proxy de alemania?

**Comment by djgerman10** [comment]
> > @thorio2002 I use Windscribe app. Your screenshot indicating FMD is still blocked accessing the website.
> 
> Funcionará con un proxy de alemania?

Yo por mi parte recomiendo esta VPN que esta crackeada a premium https://lrepacks.net/repaki-programm-dlya-interneta/141-avira-phantom-vpn-repack.html

Otra recomendación es cerrar la aplicación FMD e ir a la dirección donde está el programa y borrar la carpeta "lua" cuando inicies nuevamente te va a pedir para descargar todos estos módulos les das que sí que descargue después de descargar te va a pedir para reiniciar la app esto hará un reseteo en las cookies que suele trabarse.
