### ISSUE TITLE
[bug-website module] TraduccionesAmistosas

### ISSUE THREAD

**Issue by djgerman10** [dazedcat19/FMD#944]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 Enterprice LTSC

### Describe the bug

Problem with titles appearing as N/A
![1](https://user-images.githubusercontent.com/48584512/159623657-51acea36-f6a6-4ad1-8e4c-5fcf764791dc.png)

![2](https://user-images.githubusercontent.com/48584512/159623688-756543b3-3965-45ca-b754-e0dc68e0cf08.png)

### Log

[https://nartag.com/bl/cirujano-perfecto/](https://nartag.com/bl/cirujano-perfecto/)

**Comment by CloudBladed** [comment]
There are several sites that are like this that use the Madara system, especially the Spanish ones

**Comment by horacio881** [comment]
Mismo problema, lo que hago es descargar 1 solo capitulo y luego en **Favoritos** busco el que aparece como N/A y le dio **Boton Derecho --> Renombrar** (y le pongo en nombre correspondiente), luego de nuevo **Boton Derecho --> Cambiar "Guardar En**" Cambio solo donde dice **N/A** por el nombre del manga para futuros capitulos vayan a la carpeta correspondiente. Finalmente procedo a descargar todos los capitulos y borro la carpeta N/A.

**Comment by djgerman10** [comment]
> Mismo problema, lo que hago es descargar 1 solo capitulo y luego en **Favoritos** busco el que aparece como N/A y le dio **Boton Derecho --> Renombrar** (y le pongo en nombre correspondiente), luego de nuevo **Boton Derecho --> Cambiar "Guardar En**" Cambio solo donde dice **N/A** por el nombre del manga para futuros capitulos vayan a la carpeta correspondiente. Finalmente procedo a descargar todos los capitulos y borro la carpeta N/A.

Muchas gracias por el tip lo haré cuando me aparezca este error nuevamente, usualmente pasa cuando actualizan la pagina

**Comment by djgerman10** [comment]
Thank you very much [Slasar41](https://github.com/Slasar41)
