### ISSUE TITLE
[bug-website module] leviatanscans titles are not loading

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#947]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

https://leviatanscans.com/lmb/manga/the-descent-of-the-demonic-master/

info and downloads work, just all title comes out as N/A

**Comment by Slasar41** [comment]
https://github.com/dazedcat19/FMD2/commit/7d2e011c9e6f21a2082b4930894e5a642e742227
