### ISSUE TITLE
[bug] FMD2 will sometimes download files as Manga -.- Chapter Title despite settings not reflecting

### ISSUE THREAD

**Issue by majora2007** [dazedcat19/FMD#949]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
This issue is not consistent, but the issue is that for different manga, usually via MangaDex, the resulting file output is showing as:
"My Charms Are Wasted on Kuroiwa Medaka -.- Ch. 038 - That Bastard and Tomo.cbz" when it should be "My Charms Are Wasted on Kuroiwa Medaka - Ch. 038 - That Bastard and Tomo.cbz".

However, sometimes files download correctly, like within the same series, we can see:
"My Charms Are Wasted on Kuroiwa Medaka - Vol. 02 Ch. 018.5 - Volume 2 Extras.cbz"

I have noticed that this occurs after the main download and when there are new chapters downloaded, but not confirmed it is only in this case. 

I am looking for help if it's just my settings messed up or if there is a renaming bug.

**To Reproduce**
1. Ensure your settings match the above
2. Download a series (all chapters minus 1) from MangaDex, like "DEAD Tube" and add to Favorites
3. Observe downloads are correct and do not have -.-
4. Wait for new chapter to download, see -.-

**Expected behavior**
I would expect -.- to not be produced.

**Screenshots**
My settings are as follows:
![image](https://user-images.githubusercontent.com/735851/160248394-495e285a-8270-44f5-b4e1-facd4cc5fa69.png)

**Additional context**
N/A

**Comment by NhKPaNdA** [comment]
What are your settings below the chapter name for the filename?

**Comment by majora2007** [comment]
This actually works now, let me close it.
