### ISSUE TITLE
[bug-website module] manga-raw.club downloaded chapters becoming loading images

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#955]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

https://www.manga-raw.club/manga/virtual-world-close-combat-mage-mg1/
![001](https://user-images.githubusercontent.com/52017476/160543096-cb636f00-fbee-47e1-a1f2-7a0502ccae81.gif)

the chapters were downloading fine for awhile then all of a sudden every chapter was only one image, the same loading image i uploaded

not sure if its just me, but it just started happening. the site works and i can read the chapters just fine on the site

**Comment by Slasar41** [comment]
What's your connection number?
Maybe try lowering it.

**Comment by jillybeans** [comment]
im not sure what that is but i think its already at 1?
![1](https://user-images.githubusercontent.com/52017476/160707868-b663cab8-e59b-4855-a6fd-3bd5984574db.png)

**Comment by jillybeans** [comment]
fmd works on the site now, i didnt change anything so i dunno what fixed it
