### ISSUE TITLE
[bug-website module] Traduciones Amistosas (nartag.com) information and download not working

### ISSUE THREAD

**Issue by horacio881** [dazedcat19/FMD#956]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.
- [x] This is not temporary server issue.

**System information**
Windows 10 Enterprise LTSC x64 21H2

**Describe the bug**
Info not loading and download not happening for several days.

**Screenshots**
![Sin título](https://user-images.githubusercontent.com/24598871/160957653-f29ad69a-0804-4585-9c72-ff3c77894781.png)

**Comment by Slasar41** [comment]
You need to do cookies workaround and it'll working again.
![image](https://user-images.githubusercontent.com/28888646/165161647-1b063ded-2ebe-4bf4-ad5d-ca8221ee0bd8.png)

**Comment by horacio881** [comment]
> You need to do cookies workaround and it'll working again. 

How do I do that? Is there a tutorial or something I can watch?

Thank you for your reply

**Comment by Slasar41** [comment]
[Example](https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964).

**Comment by horacio881** [comment]
I really tried and nothing happened. I tried the steps in the tutorial and it didn't work.

Is there another step I'm missing?

I always update the cookies.

![Sin título](https://user-images.githubusercontent.com/24598871/165634467-3f76f3e2-1925-4cb4-9595-9f10e8e6577a.png)

**Comment by Slasar41** [comment]
You put the wrong cookies.
Should be like this:
![image](https://user-images.githubusercontent.com/28888646/165635242-6ac1655e-d67b-415b-84d4-25b0a22a2d38.png)

**Comment by horacio881** [comment]
Finally got it to work. What I needed was a VPN, with it it worked immediately.

The cookie values were fine. I tested them both ways and they worked.

Thanks a lot.
