### ISSUE TITLE
[bug] FlameScans kept repeat downloading again and again.

### ISSUE THREAD

**Issue by Qizmo** [dazedcat19/FMD#957]
- [yes] I'm using the latest version.
- [yes] All website modules are up to date.
- [yes] This is not temporary server issue.

Your operating system.
Windows 10 Home 21H1

**Describe the bug**
The app kept downloading the manga again and again non-stop

**To Reproduce**
1. Open "Free Manga Downloader" app. 

**Expected behavior**
Wait for the app to auto check for new chapter
the same manga that have already been loaded will reload the whole serie again.
while the app is still working, if the app "auto check for new chapter" again, it will still reload the whole same serie (that it just reload earlier) again.

example:
https://flamescans.org/series/reincarnation-of-the-murim-clans-former-ranker/

**Screenshots**
<a href="https://ibb.co/7z4d304"><img src="https://i.ibb.co/ZJmpQbm/Delete2.png" alt="Delete2" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>grab all images from a webpage</a><br />

**Comment by l-l-l-l-l-l** [comment]
AFAIK it does that with the series that have a variable suffix: some series have a time-dependent suffix added to their url and that previously broke the list by mistakenly detecting them as different series, but was fixed for both Favorites and Downloads. 

My guess is that the fix doesn't extent to the Downloaded Chapters database and therefore, every time the suffix changes, it detects the changed urls as new.
