### ISSUE TITLE
[website module request] manga-1001.com to doki1001.com

### ISSUE THREAD

**Issue by siak123** [dazedcat19/FMD#959]
### Name

doki1001.com

### Root URL

https://doki1001.com

### Directory list URL

https://doki1001.com/?s=&post_type=wp-manga

### Example manga info URL

https://doki1001.com/manga/rwby-the-official-manga-raw-free/

### Example chapter URL

https://doki1001.com/manga/rwby-the-official-manga-raw-free/rwby-the-official-manga-raw-%e3%80%90%e7%ac%ac19%e8%a9%b1%e3%80%91/

### Language

Raw

### Additional details

manga-1001.com change your domain to doki1001.com
has many raws!
Thanks, great job you do.

**Comment by Slasar41** [comment]
Next time create a `[bug-website module]` issue instead.
