### ISSUE TITLE
[bug-website module] Doujindesu can't update manga list after change domain

### ISSUE THREAD

**Issue by manhwalover** [dazedcat19/FMD#965]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 7 Pro

### Describe the bug

https://doujindesu.id/ website move domain to https://212.32.226.234/ and can't update manga list

### Log

log on but this logs empty

**Comment by manhwalover** [comment]
I try change domain from file MangaShiro.lua, from list item https://doujindesu.id/ to https://212.32.226.234/ and success link to website, but i try update manga list, this aplication not update this list.

**Comment by Slasar41** [comment]
That's because the list version is empty https://212.32.226.234/komik-list/?list.
