### ISSUE TITLE
[bug-website module] zeroscans does not show downloads 

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#970]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

the downloads are not showing up but the part of the info does, no titles

https://zeroscans.com/comics/star-martial-god-technique

**Comment by jokosablenk** [comment]
same problem here.
the site is updated, so that's why

**Comment by Slasar41** [comment]
They changed it to API based: https://zeroscans.com/swordflake/comics
Looks complex...

**Comment by Slasar41** [comment]
Got some function to working.
![image](https://user-images.githubusercontent.com/28888646/165859827-302907c3-85e5-4fb8-8243-abbfc32b43da.png)

**Comment by Slasar41** [comment]
Fixed.
There's an option to change the images quality between high and good. The default is high quality.
