### ISSUE TITLE
[bug] readcomiconline not showing chapters 

### ISSUE THREAD

**Issue by icefour33** [dazedcat19/FMD#972]
**Prerequisite**
- [y ] I'm using the latest version.
- [ y] All website modules are up to date.

- [ y] This is not temporary server issue.

**System information**
Windows 10 21H2 x64

**Describe the bug**
The chapter list for every series on readcomiconline.li is showing as empty. 

**To Reproduce**
1. Go to 'Manga Info'
2. Click on 'Any Series'
3. Scroll down to 'No need to scroll.'

**Expected behavior**
A list of the chapters, same as the site. 

**Screenshots**

**Additional context**

**Comment by Slasar41** [comment]
You need to do cookies workaround.
