### ISSUE TITLE
[bug-website module] mangahere.cc

### ISSUE THREAD

**Issue by gylz12** [dazedcat19/FMD#976]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

Website : mangahere.cc
title : all manga title and chapter
to reproduce this issue start downloading a chapter from mangahere.cc and see the downloading status. its always looping between preparing and downloading without single image downloaded, just empty chapter folder in the directory ex: hitman by seo kouji chapter 93 its just folder 93 without any image inside the folder
downloading from other website is normal
hope this is enough information. sorry for my bad englis
[downloads.zip](https://github.com/dazedcat19/FMD2/files/8523619/downloads.zip)
h

**Comment by zillafox** [comment]
Got similar issue here, watching it
