### ISSUE TITLE
[bug-website module] manga-raw.club changing site 

### ISSUE THREAD

**Issue by jillybeans** [dazedcat19/FMD#979]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

they are changing sites soon, so the page info isnt getting grabbed

their new sites is gonna be https://www.mcreader.net/

https://www.mcreader.net/manga/the-unstoppable-hellbreaker/

currently some chapters can still be grabbed but a few are converted to new site

https://www.manga-raw.club/manga/the-adventurers-that-dont-believe-in-humanity-will-save-the-world/

**Comment by xx255q** [comment]
This is needed

**Comment by Qizmo** [comment]
Need help with this too.

**Comment by jillybeans** [comment]
there is a work around but its super tedious

https://www.mcreader.net/manga/the-unstoppable-hellbreaker/

replace the new site with the old site and it will grab the chapters in FMD until they stop the old site completely, but for now it at least downloads the new chapters

https://www.manga-raw.club/manga/the-unstoppable-hellbreaker/

**Comment by Slasar41** [comment]
MangaRaw still works fine.
Should I replace it or create a new site instead?

**Comment by jillybeans** [comment]
can you create a new site instead? since they still use the old one, until its completely gone. the search function on their site still goes to old one but every link goes to new one. so its better to have it as a separate one until its completely gone

**Comment by Slasar41** [comment]
I've added MCReader. https://github.com/dazedcat19/FMD2/commit/3b8681afe1048f6dfbde470b1d59b1b20c6e5441
Because MangaRaw is still working, I'll close this issue.

**Comment by xx255q** [comment]
Well my current understanding of the site is that it redirects to the new
site. If this redirects stops working are you able to update the current
module to get old favorites still working or will we have to re favorite
our series?

**Comment by Slasar41** [comment]
@xx255q Try to use `Transfer Website` function.
If it doesn't work then follow [this](https://github.com/dazedcat19/FMD2/issues/1013#issuecomment-1272648516).
