### ISSUE TITLE
[bug-website module] ninemanga.com

### ISSUE THREAD

**Issue by stonechitlin** [dazedcat19/FMD#980]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H1 x64

### Describe the bug

I think ninemanga.com has become ninemanga.org, as ninemanga.org works but .com 404's. Cant find any definite answers from google either way.

**Comment by CloudBladed** [comment]
I thought ninemanga was dead until I saw the request hahahaha

**Comment by molitar** [comment]
Ok the URL has not changed what has changed is instead of + in file names it now has become - in the filename. 

http://ninemanga.org/manga/Dorei+Tensei%3A+Sono+Dorei%2C+Saikyou+no+Moto+Ouji+ni+Tsuki.html

Now 

http://ninemanga.org/manga/dorei-tensei-sono-dorei-saikyou-no-moto-ouji-ni-tsuki

and no .html after name either.

**Comment by Slasar41** [comment]
.com is still fine, .org is a different site and isn't supported by FMD.
If you want it to be added to FMD, create a website request issue.

**Comment by molitar** [comment]
Did you even try to go to come it redirects to org!  Site is not fixed and you close this request?  WTF???  Maybe Ninemanga was having a problem and temporarily redirected to .org.  But that still does not address the face that Ninemanga does not work at all!  Ninemanga has fixed there redirect but the site still does not work!

**Comment by Slasar41** [comment]
@molitar Yeah I did tried it and no there's no redirect.
.com still works fine.
![image](https://user-images.githubusercontent.com/28888646/167286475-892e7747-e0c4-44b6-a648-4755c47f693f.png)

**Comment by molitar** [comment]
Seems whatever happened corrupted the lua.  I had to completely delete the ninemanga and than let it redownload.
