### ISSUE TITLE
[bug-website module] nhentai.net

### ISSUE THREAD

**Issue by JayAyyBee** [dazedcat19/FMD#983]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 21H1 x64

**Describe the bug**
nhentai.net URLS result in a "Please turn JavaScript on and reload the page." result/error in the Manga Info tab. Attempting to download results in an error.

**Comment by ericvlog** [comment]
yes , me too . please fix it ,

thanks

**Comment by Black-Dalek** [comment]
Same error, the website was showing cloudfare screen before load. maybe was temporal

**Comment by ericvlog** [comment]
now it okay, thanks
