### ISSUE TITLE
[bug-website module] mangadex

### ISSUE THREAD

**Issue by Black-Dalek** [dazedcat19/FMD#984]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

windows 10 21H2 64 bits compilation 19044.1682

### Describe the bug

massive number of titles show no chapters on favorites since april 30th , also, don't get updated for the same reason, the site is working on browser.
![imagen](https://user-images.githubusercontent.com/36430844/166342268-3ff73d89-3178-4e81-89c2-f5e8f609b087.png)
![imagen](https://user-images.githubusercontent.com/36430844/166342291-26c0dc37-954e-4776-bed2-d1505d1f49e7.png)

**Comment by Black-Dalek** [comment]
19:15:31:637 LUA>DoGetInfo("MangaDex.lua")> LuaCallFunction("GetInfo") LUA_ERRRUN: Desktop\Apps\fmd2\lua\modules\MangaDex.lua:252: attempt to perform arithmetic on a nil value (No Items)

**Comment by Slasar41** [comment]
Could you upload your favorites database?

**Comment by Black-Dalek** [comment]
>

**Comment by Black-Dalek** [comment]
I tried but: 
![imagen](https://user-images.githubusercontent.com/36430844/166588252-0d2fdcec-1a6d-425a-8dd8-74a1a9233c98.png)

**Comment by Black-Dalek** [comment]
> I tried but: ![imagen](https://user-images.githubusercontent.com/36430844/166588252-0d2fdcec-1a6d-425a-8dd8-74a1a9233c98.png)

![imagen](https://user-images.githubusercontent.com/36430844/166588347-e5c85bc9-9743-4ee3-8b7a-dabc84c02ffe.png)

**Comment by Black-Dalek** [comment]
sorry , i closed the issue by mistake

**Comment by Black-Dalek** [comment]
https://www.mediafire.com/file/sa37a0qir0vx83v/favorites.zip/file

**Comment by Black-Dalek** [comment]
> Could you upload your favorites database?

i find the cause: the prefered language for mangadex was changed from english to chinese! so, no chinese translation, no chapters. I find the last downloaded were in chinese and checked the files on directory: they were duplicated english & chinese :/
