### ISSUE TITLE
[bug-website module] BiliBiliComics can't download chapters

### ISSUE THREAD

**Issue by kuso-ge** [dazedcat19/FMD#995]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [X] This is not temporary server issue.

### System information

Windows 10 21H2

### Describe the bug

Okay, so I noticed that around April 15 up until today, 
I haven't been able to download chapters from BiliBiliComics

Website: BiliBiliComics
Title: Please Spare me Apprentice
URL: https://www.bilibilicomics.com/detail/mc149

Although there doesn't seem to be a problem retrieving the chapter list from the site. 

### Log

```
14:03:20:030 EXCEPTION: LUA>DoGetPageNumber("BiliBiliComics.lua")> LuaCallFunction("GetPageNumber") LUA_ERRRUN: ...fmd_2.0.30.0_x86_64-win64\lua\modules\BiliBiliComics.lua:74: attempt to index a nil value (global 'x')
14:03:22:055 WARNING: TTaskThread.CheckForFinish failed 1 of 1 [BiliBiliComics] "Please Spare Me! Apprentice!" > "/161084"
[001] W

14:03:22:055 WARNING: TTaskThread.Execute end with failed chapter(s)
```

**Comment by Slasar41** [comment]
Which chapter?

**Comment by kuso-ge** [comment]
I believe all of them. I haven't been able to download any chapters. You could try these series:

![image](https://user-images.githubusercontent.com/12083007/170656910-1ac78917-a76e-481a-899e-128396095abe.png)

https://www.bilibilicomics.com/detail/mc116
https://www.bilibilicomics.com/detail/mc149

> 15:59:23:226 INFO: 1: need buy episode
> 15:59:23:226 EXCEPTION: LUA>DoGetPageNumber("BiliBiliComics.lua")> LuaCallFunction("GetPageNumber") LUA_ERRRUN: ...fmd_2.0.30.0_x86_64-win64\lua\modules\BiliBiliComics.lua:74: attempt to index a nil value (global 'x')
> 15:59:23:231 INFO: 1: need buy episode
> 15:59:23:232 EXCEPTION: LUA>DoGetPageNumber("BiliBiliComics.lua")> LuaCallFunction("GetPageNumber") LUA_ERRRUN: ...fmd_2.0.30.0_x86_64-win64\lua\modules\BiliBiliComics.lua:74: attempt to index a nil value (global 'x')
> 15:59:25:251 WARNING: TTaskThread.CheckForFinish failed 1 of 1 [BiliBiliComics] "I, the Strongest Demon, Have Regained My Youth?!" > "/172610"
> [001] W
> 
> 15:59:25:251 WARNING: TTaskThread.CheckForFinish failed 1 of 1 [BiliBiliComics] "Please Spare Me! Apprentice!" > "/169761"
> [001] W
> 
> 15:59:25:960 INFO: 1: need buy episode
> 15:59:25:961 EXCEPTION: LUA>DoGetPageNumber("BiliBiliComics.lua")> LuaCallFunction("GetPageNumber") LUA_ERRRUN: ...fmd_2.0.30.0_x86_64-win64\lua\modules\BiliBiliComics.lua:74: attempt to index a nil value (global 'x')
> 15:59:25:977 INFO: 1: need buy episode
> 15:59:25:978 EXCEPTION: LUA>DoGetPageNumber("BiliBiliComics.lua")> LuaCallFunction("GetPageNumber") LUA_ERRRUN: ...fmd_2.0.30.0_x86_64-win64\lua\modules\BiliBiliComics.lua:74: attempt to index a nil value (global 'x')
> 15:59:27:982 WARNING: TTaskThread.CheckForFinish failed 1 of 1 [BiliBiliComics] "Please Spare Me! Apprentice!" > "/169761"
> [001] W
> 
> 15:59:27:983 WARNING: TTaskThread.Execute end with failed chapter(s)
> 15:59:27:998 WARNING: TTaskThread.CheckForFinish failed 1 of 1 [BiliBiliComics] "I, the Strongest Demon, Have Regained My Youth?!" > "/172610"
> [001] W
> 
> 15:59:28:034 WARNING: TTaskThread.Execute end with failed chapter(s)
>

**Comment by Slasar41** [comment]
I can't download the latest chapter but that's expected like in the log, you need to buy the chapter.
If you already bought it, you can use cookies workaround to make FMD able to download it.
