### ISSUE TITLE
[bug-website module] Can't access Nhentai

### ISSUE THREAD

**Issue by zim267** [dazedcat19/FMD#996]
I'm using the latest version.
All website modules are up to date.
This is not temporary server issue.

**System information**
Windows 10.

**Describe the bug**
I'm suddenly unable to download from Nhentai. It works just fine yesterday. I don't know what happened, i guess it have something to do with Cloudflare, judging from the log. I'm no tech savvy, so i don't understand what the problem is. But i can access it just fine from the web browser. I'm using a modified host file, by Bebasid, if that matters, since the website is blocked in my country

**Screenshot**
If I don't use 1.1.1.1 desktop client, i only got a blank screen
![Capture 2](https://user-images.githubusercontent.com/53287050/168533612-8d7ddb02-c540-402f-8ba5-ef888770c527.PNG)
If i use 1.1.1.1 desktop client. this shows up
![Capture 3](https://user-images.githubusercontent.com/53287050/168626692-ff5b387d-f554-4515-9e2b-36d9809556f4.PNG)

**Log**
13:30:27:431 WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://nhentai.net/g/401753/
13:30:29:950 WebsitBypass[cloudflare]: no Cloudflare solution found!
https://nhentai.net/g/401753/
13:30:28:815 WebsitBypass[cloudflare]: detected the new Cloudflare challenge, not supported yet
https://nhentai.net/g/401753/

**Comment by kuso-ge** [comment]
You're gonna have to use the CF bypass. 

It works, here's a sample I just tried when I used the CF bypass:

![image](https://user-images.githubusercontent.com/12083007/168812291-2d545e58-9ff6-4e71-91c3-c17cc08de996.png)

Here's how, go to Chrome/Firefox,
1. Go to desired website (i.e. Nhentai.com)
2. Right click anywhere and click [Inspect]
3. Go to [Network] Tab,
4. Copy Cookies containing "cf_clearance=xxx...xxx" 
5. Copy user-agent aswel
6. Paste those in FMD>Options>Websites>Advance(nhentai):

![image](https://user-images.githubusercontent.com/12083007/168813032-094fda4e-e453-48b7-b5c3-0f288c9167d5.png)

**Comment by nopolare** [comment]
yeah same for me need turn on javascript?  where i can turn on java script

**Comment by zim267** [comment]
> You're gonna have to use the CF bypass.
> 
> It works, here's a sample I just tried when I used the CF bypass:
> 
> ![image](https://user-images.githubusercontent.com/12083007/168812291-2d545e58-9ff6-4e71-91c3-c17cc08de996.png)
> 
> Here's how, go to Chrome/Firefox,
> 
> 1. Go to desired website (i.e. Nhentai.com)
> 2. Right click anywhere and click [Inspect]
> 3. Go to [Network] Tab,
> 4. Copy Cookies containing "cf_clearance=xxx...xxx"
> 5. Copy user-agent aswel
> 6. Paste those in FMD>Options>Websites>Advance(nhentai):
> 
> ![image](https://user-images.githubusercontent.com/12083007/168813032-094fda4e-e453-48b7-b5c3-0f288c9167d5.png)

Sorry, i just noticed the reply, how do i look for the cf_clearance on chrome? I'm not finding it unfortunately

**Comment by zim267** [comment]
> You're gonna have to use the CF bypass.
> 
> It works, here's a sample I just tried when I used the CF bypass:
> 
> ![image](https://user-images.githubusercontent.com/12083007/168812291-2d545e58-9ff6-4e71-91c3-c17cc08de996.png)
> 
> Here's how, go to Chrome/Firefox,
> 
> 1. Go to desired website (i.e. Nhentai.com)
> 2. Right click anywhere and click [Inspect]
> 3. Go to [Network] Tab,
> 4. Copy Cookies containing "cf_clearance=xxx...xxx"
> 5. Copy user-agent aswel
> 6. Paste those in FMD>Options>Websites>Advance(nhentai):
> 
> ![image](https://user-images.githubusercontent.com/12083007/168813032-094fda4e-e453-48b7-b5c3-0f288c9167d5.png)

thank you very much, it worked.
